### ISSUE TITLE
Standalone Version

### ISSUE THREAD

**Issue by Wipsly** [thekordy/ticketit#1]
Hi,

do you have standalone Version? The package is create but I would like to see a full example app.

Greets
Wipsly

**Comment by thekordy** [comment]
Hi Wipsly,
I have not finished it yet, it may take another week to be ready. And yes, I could upload a standalone version when the system is done.

Best Regards,
Kordy

**Comment by Wipsly** [comment]
Wow, that sounds great! Thank you so far!
