### ISSUE TITLE
User can comment on other's tickets. SECURITY BUG

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#10]
Every user in the system can *view* and *comment* on tickets that were not created by them. Ok, the tickets are not listed at the My tickets page, but ticket ID-s are easy-to-guess. Tickets should be only allowed to be viewed by the owner, agents and admins. It's a serious security bug!!

**Comment by thekordy** [comment]
You are right, it is on the top of my to do list and i was planning to cover it in the next patch
