### ISSUE TITLE
View not found, and no config file?

### ISSUE THREAD

**Issue by aske-cph** [thekordy/ticketit#104]
Hi, thanks for the system!

I just installed. I get two errors after the initial redirect after installation: 

```
InvalidArgumentException in FileViewFinder.php line 137:
View [] not found.


ErrorException in FileViewFinder.php line 137:
View [] not found. (View: /home/vagrant/Code/sus/vendor/kordy/ticketit/src/Views/index.blade.php)
```

Also there is no config file present anywhere corresponding to the one mentioned in the wiki.
Neither config/ticketit.php (in my own folder). The folder "vendor/kordy/ticketit/src/Config/ticketit.php'" is not present?

Thanks in advance!

**Comment by thekordy** [comment]
probably the master view file path is not set, and we use the database instead of the config file for settings.
To solve this, you have to fire the installation process again, you may do migrate rollback then visit again http://projecturl/tickets-install  .. and make sure to choose the right master view file.

**Comment by aske-cph** [comment]
Thanks for the quick answer!
You were right.
For some reason both "master_template" values were empty.

But setting them manually deosn't help. 

My Laravel app serves all views from the public folder. (not default, because angular app).
Is that maybe why the view finding fiails? Is the path hardcoded somehow to resources?

Anyways, i have placed master.blade.php file in both resource/views, and in my main views folder: public/master.blade.php.

I have tried all kinds of paths, none of them works:

master.blade.php,
public/master.blade.php,
../public/master.blade.php,
/../../public/master.blade.php

etc.

**Comment by thekordy** [comment]
How do you extend the master template? as in a child view we use `@extend('master')` , so in your case what do you write in place of "master"?

**Comment by aske-cph** [comment]
Thanks for the help!

I made it work by just writing "master" in both columns (in the template setting row) in the database.

AND running the command:

```
php artisan cache:clear
```

**Comment by thekordy** [comment]
Glade to see it works for you, and thank you for the feedback.

**Comment by halfbug** [comment]
i resolved it by updating database table 
UPDATE `ticketit_settings` SET `value` = 'layouts.app', `default` = 'layouts.app' WHERE `ticketit_settings`.`id` = 5;

**Comment by ShifanThawfeek** [comment]
Hi, when i try this link, "http://ticketit.dd/tickets-install" I got an error "404 Sorry, the page you are looking for could not be found." What could be the issue, could you please let me know.

**Comment by rohansaaram** [comment]
@ShifanThawfeek use 
php artisan config:clear
php artisan clear-compiled
php artisan cache:clear
