### ISSUE TITLE
rich text

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#116]
Have you considered implementing some markdown, bbcode or some other wysiwyg editor functionality?

It"s not important at all, just an idea for later when there's nothing with higher priority to do

**Comment by thekordy** [comment]
I think a small bbcode editor would be nice

**Comment by balping** [comment]
I implemented this, using summernote, I'll update readme, wiki, etc. tomorrow, because it's setup is not that trivial. After that it's time for a new release I think

**Comment by thekordy** [comment]
Are their further required steps to get it work?

**Comment by thekordy** [comment]
I tried it and I had some issues that we need to work on it:

1) I get error because the installer failed to spot the new inactive migrations and I fixed it here 031098491221094102900d852f3abd9f1cb36c07

2) When it tries to install the new migrations I get this error
![2016-01-15 13-51-46](https://cloud.githubusercontent.com/assets/11343048/12352667/b2852768-bb90-11e5-9c3e-b5ea91422e95.png)

That could be get fixed if you set the new ticketit column as nullable

``` php
 $table->longText("html")->nullable()->after("content");
```

This will set a default null for html column for all previous posts and the add_htmlcontent migration will be installed correctly, but that will make another problem, in which showing the html content of old posts will be only null :) .. might be a simple if condition to check if null and show the old text instead will solve it.

3) when I succeeded to install the migration, I couldn't get the editor to be shown
![ticketit-summernot](https://cloud.githubusercontent.com/assets/11343048/12352651/8825eafc-bb90-11e5-827c-4ee39e009d8f.png)

**Comment by balping** [comment]
Hi!

Sorry for the delayd reply. So basically there are 3 things to do for upgrading:

1) run migrations - you've already done this. Also, thanks for the migration fix

2) run the settings seeder since there are some new settings added. I dont know if it can be run without modifying the existing settings

3) running `php artisan ticketit:htmlify` This copies existing content data to html

These instructions should be included in the docs, that's why I said, it's mot trivial.

Also the package needs jquery, I thought it was included by default. I'll make an optional jquery include when I get home (the user can set of ticketit should include it or not, if its already included outside of ticketit, theres no need to include it again)

**Comment by thekordy** [comment]
Hi
I will make sure 1, 2, and 3 will be done automatically through the installation process.

**Comment by thekordy** [comment]
finally works in chrome .. but it is broken in firefox

![ticketit - new ticket form 2016-01-15 17-21-48](https://cloud.githubusercontent.com/assets/11343048/12356682/8a8fb2d4-bbac-11e5-9c58-2b703615d840.png)
![ticketit - ticket minima voluptas dolor vero illum rerum sit 2016-01-15 17-21-30](https://cloud.githubusercontent.com/assets/11343048/12356683/8a92ed96-bbac-11e5-9cf6-27a229f6f15a.png)

**Comment by balping** [comment]
I'll check it

**Comment by balping** [comment]
jquery included, works now in firefox

https://github.com/thekordy/ticketit/commit/920e08a9dd21ba2eddb7a33495892b43e2bfa433

**Comment by balping** [comment]
Ok, so now I found this in the readme:

> ## Requirements
> 
> **First Make sure you have got this Laravel setup working:**
> ...
> 5. Jquery

So assuming that jquery is installed was not groundless... Anyway, once implemented, I won't remove it, but maybe we should set the default to 0

**Comment by thekordy** [comment]
yes, we probably should ..  and yes, jquery should be included by the requirements

**Comment by thekordy** [comment]
After I updated to your last commits, it works only if I turned the include_jquery off (set to 0) ..

**Comment by balping** [comment]
It was because `show.blade.php` used jquery before it was included in `summernote.blade.php`

Since it's not easy to manipulate blade's include order, it is cleaner if I completely  remove jquery option from ticketit. Users should read the readme anyway.

https://github.com/thekordy/ticketit/commit/1b1aeecdf4b1205d8536067adc8051fa5930efa5

**Comment by thekordy** [comment]
That's awesome, now the only thing left is to make Ticketit since the new settings added and to set them up automatically, I will do that by the weekend.

**Comment by balping** [comment]
BTW, with this editor users can now upload images, you could include this on the feature list

**Comment by tmcdon89** [comment]
Looks good guys. 
Will the attached images save in the same place as the other attachment options in v1.x?

**Comment by balping** [comment]
No, there's no connection between these two. Now each comment/ticket has a LONGTEXT column in the database which can store data up to 4 GB. If you attach an image using the editor, it will be stored base64 encoded together with the text. You can limit the size of course if you want. There's actually another column that stores only plain text, it can be used for text-based search (if someone implements  a better search)

**Comment by thekordy** [comment]
I really prefer filesystem over database for files upload, and if we already have file upload settings (like what @tmcdon89 added to 1.0 configuration), they should apply for all system uploads (like allowed extensions, upload path, maximum size)

**Comment by balping** [comment]
One can easily switch this database file upload off. I'll add the necessary docs for that
