### ISSUE TITLE
Undefined variable: main_route

### ISSUE THREAD

**Issue by christopherdev** [thekordy/ticketit#121]
hi,

I am relatively new to laravel and I have this issue ErrorException in routes.php line 3:
Undefined variable: main_route.

any idea what have I missed?

tnx

**Comment by thekordy** [comment]
That's OK but you have to make sure you fulfilled all [requirements](https://github.com/thekordy/ticketit/blob/0.2/README.md#requirements)  and follow every step from the [four steps](https://github.com/thekordy/ticketit/blob/0.2/README.md#installation-4-8-minutes) to make it work, if you miss any of these,  you will only get errors and nothing will work.

For this issue, I think you missed the [second step in the installation](https://github.com/thekordy/ticketit/blob/0.2/README.md#installation-4-8-minutes)

**Comment by lucenarenato** [comment]
I do not know what to do.
