### ISSUE TITLE
auth Problem - Then undefined function get

### ISSUE THREAD

**Issue by Devsome** [thekordy/ticketit#122]
Hello,

I followed the tutorial and this didn't worked for me.
I needed to uncomment in TicketitServiceProvider.php line 112 & 116 the middleware => auth.
After that I was able to migrate the database with the post request.

Changes where made in the database and I hoped it worked, but sadly not.
Then I located to the /tickets page and 
Call to undefined function get() on line 5 

Thanks for your time and sorry for my english.

Regards

**Comment by thekordy** [comment]
Make sure you have [all requirements](https://github.com/thekordy/ticketit/blob/0.2/README.md#requirements) set up correctly .. to install Ticketit you have to have a user account and to be logged in.

**Comment by Devsome** [comment]
@thekordy : Thanks for your reply.
 I am using the newest Laravel version.
Got the User tables and also logged in (added the Acl Service from Kodeine)
Laravel is using the mailgun server (works)
Bootstrap and jQuery installed.

// update: When i am not logged in and trying to call /tickets-install/ I need to login, after that again nothing happens.

**Comment by thekordy** [comment]
We are not yet compatible with laravel 5.2

**Comment by Devsome** [comment]
@thekordy : Guess thats the error then. 
Thanks for your time

**Comment by balping** [comment]
This package works for me with Laravel 5.2 (using dev branch). All compatibity issues have been solved, hopefully you'll be able to use ticketit in laravel 5.2 when the next release comes which will happen in few days

**Comment by Devsome** [comment]
@balping : Thats sounds amazing. Waiting for the release then :+1:

**Comment by larasoft-io** [comment]
@balping looking forward to this release.  in need of a ticketing package for my L5.2 project!

**Comment by balping** [comment]
@thekordy makes releases

**Comment by balping** [comment]
@ajs87  But you can use dev until he makes the new release:

```
"require": {
        "kordy/ticketit": "0.2.x-dev"
},
```

**Comment by larasoft-io** [comment]
Thanks @balping, I'll take a look.

**Comment by balping** [comment]
Just clean everything related to ticketit before installing. Upgrading doesn't work (yet), but a fresh install should

**Comment by larasoft-io** [comment]
sure thing, I'll make sure it's fresh.  Thanks for your help

**Comment by balping** [comment]
I'll try this with a fresh 5.2 install as well. Although I'm using L 5.2 in my own project as well, I upgraded it from 5.1 (and before from 5.0), so my install might be a bit different, so I'll try this now to be sure it works with a fresh 5.2

**Comment by balping** [comment]
Ahh wait! Now I see your problem. I'll correct this issue now

**Comment by larasoft-io** [comment]
Thanks! :+1:

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/commit/4ee42a1518342026c04f007463a37c6ddb9ecbf9

**Comment by larasoft-io** [comment]
Nice work. Let's have a play. :+1:

**Comment by balping** [comment]
Now agents table not found for me, another issue is coming....

**Comment by balping** [comment]
I made another few commits, everything should work now

**Comment by balping** [comment]
Yeah, now I tested as many features as I could and it seems that now we really have full L5.2 support :-)

**Comment by larasoft-io** [comment]
Great Work @balping.

**Comment by drtzack** [comment]
I have 2 different Auth
One for user and other one for admins and they completely different table

And my admin auth name is "panel"  So In middleware I use "auth:panel"

I think you should allow something like that.
