### ISSUE TITLE
Coding convention, StyleCI?

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#123]
While making several commits to this repo, I tried to follow the coding style I found in the given file I was editing. However I have the impression that not all lines of this code follow (a) / (the same) coding convention. I might be wrong anyway. The majority of the code seems well formatted, but I don't recognize the convention. I'm actually not familiar with popular conventions, in my own projects I usually follow my own style. But since there are several people working on this repo, I think it's time to agree on something.  After googl'ing a bit, I found that Laravel uses a convention called psr 2. Maybe we could stick to this. But it's just an idea.

I've also seen on github, many repos use a service called StyleCI that automatically checks the style of pull requests and commits. It's free for open projects, maybe we could try it. https://styleci.io/

What do you think?

**Comment by tmcdon89** [comment]
I'm inclined to agree that having a "style" would be beneficial.

**Comment by thekordy** [comment]
PSR-2 would be fine for a code convention. and I agree with you, StyleCI would help a lot, and I am subscribing right now.

**Comment by balping** [comment]
:thumbsup:
