### ISSUE TITLE
unserialize error

### ISSUE THREAD

**Issue by tmcdon89** [thekordy/ticketit#125]
I'm attempting to merge the latest v.2 enhancements into my copy of v1 but I am running into the following error while attempting to add a comment to a ticket.

ErrorException in Setting.php line 61:
unserialize(): Error at offset 256 of 255 bytes

I am getting a similar error when attempting to access the purifier setting from the settings configuration pages.

unserialize(): Error at offset 256 of 255 bytes (View: /var/www/html/AeroControl/vendor/kordy/ticketit/src/Views/admin/configuration/edit.blade.php)

Any ideas?

**Comment by balping** [comment]
Could you `var_dump($setting->value)` just before this ?

**Comment by tmcdon89** [comment]
This is the return I'm seeing if I var_dump before the if statement in question.

string(7) "tickets" string(13) "tickets-admin"

**Comment by balping** [comment]
I don't really understand, one variable has only one value, not two

**Comment by tmcdon89** [comment]
I'm not sure if I messed something up in the process of attempting to put the branches together. But its definitely a strange thing to happen.

**Comment by tmcdon89** [comment]
OK, so it was something going on with the current installation. Clearing everything out and installing my branch fresh resolved that issue.

**Comment by thekordy** [comment]
That's very interesting, I was going to try the same to merge the new changes in 0.2 into 1.0. I am wondering if you have succeeded to merge them.

**Comment by tmcdon89** [comment]
I am making progress on the merge but I do not have it completely working yet. On a clean install I am getting the error with the settings table which is odd because the fix that you commited is in place so I need to see why it's not using it.
