### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by thekordy** [thekordy/ticketit#129]
After a fresh install, I get this error when I try to access any ticketit-admin pages

![ticketit 1 0 classnot found error](https://cloud.githubusercontent.com/assets/11343048/12493483/dc50ea12-c08d-11e5-9778-502dc787dc97.png)

**Comment by thekordy** [comment]
this only happens with v1.0 and laravel 5.1 .. I have not found any problem for v1.0 with laravel 5.2 as well as v0.2 with laravel 5.1 and 5.2

**Comment by tmcdon89** [comment]
I'm taking a look at what might cause this. I know the reflexion exception errors are often related to a name spacing issue. Did you notice this before or after updating to the psr-4?

**Comment by thekordy** [comment]
The problem is somewhere in this commit d3c38f5a0a2c6acb81576af312c26d6df8dd117b

**Comment by tmcdon89** [comment]
I originally had issues with the 'web' class in the laravelhelpers file. It could be there. I'll try that next.

**Comment by tmcdon89** [comment]
Yah my issue goes away if I set it to at line 87:

public static function authMiddleware()
    {
        return ['auth'];
    }

**Comment by thekordy** [comment]
You are right about the reason. but Laravel 5.2 uses web middleware instead of auth, so this solves 5.1 problem but makes another problem with authentication and session handling in 5.2

**Comment by thekordy** [comment]
So I used your suggestion in this way so something like function below might solve it, I tried it with both 5.1 and 5.2

``` php
public static function authMiddleware()
    {
        if (static::min('5.2') && app(Router::class)->resolveMiddlewareClassName('web') != 'web') {
            return ['web', 'auth'];
        } else {
            return ['auth'];
        }
    }
```

**Comment by tmcdon89** [comment]
That works for me also. Which I'm on Laravel version 5.2.10 currently.

**Comment by thekordy** [comment]
That is perfect, thank you for help :+1:
