### ISSUE TITLE
Preview URL

### ISSUE THREAD

**Issue by FusionDesign** [thekordy/ticketit#13]
http://ticketit.fusiondesign.me/

I've taken the time to put together a preview page with two logins (admin@demo.com && user@demo.com) -- password for both accounts are "demo".

If you choose not to use it, that's fine; just let me know so I can take it down. Just helping out!

**Comment by thekordy** [comment]
I like it thank you. Are you going to keep it up for others to try? That would be great :)

**Comment by FusionDesign** [comment]
Yeah I'll host it for the life of the project, as long as it doesn't grow crazy popular then I may switch it to another server. I'm watching this project and I'll do pulls on the repo and tweaks as time goes on. I use this is my main website so I'm all about it.

**Comment by thekordy** [comment]
That's great, Thank you. 

Let's see if you need a feature from the To do list (or a new one), let me know, and we may think of some collaboration to build the feature together.

**Comment by thekordy** [comment]
Hello :)

Is it possible to add more accounts to the demo? Just to demonstrate multiple users/agents environment

**Comment by FusionDesign** [comment]
Yeah, I just finished converting my site to Bootstrap so I can finally give this project the love it needs!

**Comment by thekordy** [comment]
:)

By the way, I sent you an email, did you get it?

**Comment by thekordy** [comment]
Hello @FusionDesign , how are you doing? 

This seeder would help you with demo site :+1:

**Comment by thekordy** [comment]
Dear Brian, how do you do?

Just to get things ready for the v0.2.0 release, I set up the new demo at ticketit.kordy.info temporary until you can find the time to upgrade the live demo you generously offers.

**Comment by fusiondesign** [comment]
Yeah, I'll update this now!

**Comment by fusiondesign** [comment]
I'm pulling in the project locally to update the template and navigation. Will be up shortly.

**Comment by fusiondesign** [comment]
Preview url has been updated at ticketit.fusiondesign.me

**Comment by fusiondesign** [comment]
@thekordy

**Comment by fusiondesign** [comment]
@thekordy Can you share your database seeder? Or did you do all these tickets manually? I like your demo clone better but I don't want to re-create the wheel if I don't have to :)
