### ISSUE TITLE
Fatal error: Class 'App\User' not found. (Custom folder for Models).

### ISSUE THREAD

**Issue by RVisal** [thekordy/ticketit#135]
Hello
I keep all models in the App\Models.
So there is an error "FatalThrowableError in InstallController.php line 53: Fatal error: Class 'App\User' not found".

I can replace all namespace 'App\User' to 'App\Models\User'. But this is not an option because your package will be updated. How to solve this problem?

Thank you

**Comment by balping** [comment]
That's maybe becuase the main namespace of your app is not `App`. You can change this via an artisan command. But it's a bug anyway, this `App` namespace shouldn't be hardcoded in ticketit

**Comment by balping** [comment]
I'll fix this, I've already found how it can be done

http://stackoverflow.com/questions/29319088/get-the-app-namespace-in-laravel-5

**Comment by RVisal** [comment]
The main namespace is App. 
        "psr-4": {
            "App\": "app/"
        }

I moved models to another folder due to the fact that the models become too much in my app.
In ticketit the model User is called as 'use App\User;', but I need call it as 'use App\Models\User;'.

In config/auth.php can get actual path to User model.
'model' => App\Models\User::class,

**Comment by balping** [comment]
Thanks for the config/auth.php hint. I'll integrate this then.

But until you could try creating an alias to User

For example: yourproject/app/User.php:

```
<?php

namespace App;

class User extends Models\User {
//leave this empty
}
```

**Comment by RVisal** [comment]
Alias is working, thank you!

**Comment by balping** [comment]
I tried but I don't know how dynamic includes could be done. I'll include this alias solution in the wiki in case if someone else has a similar problem
