### ISSUE TITLE
Swift_TransportException in AbstractSmtpTransport.php line 383: Expected response code 250 but got code "553", with message "553 5.7.1 Sender address rejected: not owned by auth user. "

### ISSUE THREAD

**Issue by RVisal** [thekordy/ticketit#141]
Hello
When trying create new ticket i get this error:

Swift_TransportException in AbstractSmtpTransport.php line 383:
Expected response code 250 but got code "553", with message "553 5.7.1 Sender address rejected: not owned by auth user.

I use SMTP mail driver, and smtp server does not allow to send emails except from my e-mail address. While ticketit using e-mail address from user who creates a ticket.

In config/mail.php - parameter Global "From" Address.

**Comment by thekordy** [comment]
Hello,

I don't remember we are altering the $from other than the one configured in config/mail.php .. make sure you already configured this parameter in `config/mail.php`

``` php
'from' => ['address' => null, 'name' => null],
```

**Comment by RVisal** [comment]
Of course, this option is already configured.

**Comment by thekordy** [comment]
Yes, Ticketit sends notifications from the notifications owner address, and that is not right.

https://github.com/thekordy/ticketit/blob/0.2/src/Controllers/NotificationsController.php#L96

I am sorry for that, I will work on this, so it will look first for
1. Ticketit default_outgoing_email setting
2. then the Laravel email from setting
3. then the smtp address
4. the notification owner address as the last lookup

This will be a patch for v1.0

**Comment by thekordy** [comment]
Resolved in 0.2.7
