### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by marciocelebri** [thekordy/ticketit#142]
Follow as doc https://github.com/thekordy/ticketit/wiki/How-to-install-Ticketit and the following errors appear :

[ Illuminate \ Database \ QueryException ]
SLQSTATE [ 42S02 ] : Base table or view not found : 1146 Table ' ticket.migrations ' does not exist (SQL : select \* from migrations )

[ PDOException ]
SLQSTATE [ 42S02 ] : Base table or view not found : 1146 Table ' ticket.migrations ' does not exist

Note : I created a clean laravel the project 5.1 *.

**Comment by balping** [comment]
Please run `php artisan migrate` first.

You need to do this before adding the service provider to your config/app.php file

**Comment by marciocelebri** [comment]
It was made this way. Now , first ran the two migrations of laravel project and the other ran normally.

But when accessing the url redirects to auth / login and shows error page NotFoundHttpException .

**Comment by balping** [comment]
Maybe because you haven't set up auth routes and views

https://laravel.com/docs/5.1/authentication#authentication-quickstart

**Comment by marciocelebri** [comment]
Thanks! After logging in, to which file / route should redirect?

**Comment by marciocelebri** [comment]
After logging in, accessing the ticket route or ticket -admin :

Ticketit needs upgrade, admin should login and visit ticketit install route

**Comment by tmcdon89** [comment]
The default install route is /tickets-install

It will only be available if you are logged in as an admin account or if there hasn't been an admin account created yet.

**Comment by marciocelebri** [comment]
Put the user as admin ( int 1). Now the error is:

View [master] not found. (View: /var/www/html/ticketit/vendor/kordy/ticketit/src/Views/index.blade.php)

Help me, please.

**Comment by marciocelebri** [comment]
After adding the master template which you can see is this picture here .

Trying to register a ticket and will not appear priority and neither category. The database does not have any registered .
![ticketit-access](https://cloud.githubusercontent.com/assets/16846814/12556500/ed85da8e-c364-11e5-98cb-10d013cd15e9.PNG)

**Comment by thekordy** [comment]
You need to include the jquery and bootstrap in your master template header .. also don't forget to add `@yield('footer')` last thing after jquery.js in your html footer

**Comment by thekordy** [comment]
review this https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template

**Comment by marciocelebri** [comment]
![master-blade](https://cloud.githubusercontent.com/assets/16846814/12556886/ee0fc81e-c366-11e5-803c-2176ff5e69a9.PNG)

![error-01](https://cloud.githubusercontent.com/assets/16846814/12556976/60c7fbba-c367-11e5-9989-83d36babdda1.PNG)
1. Where are the css / js files? It is to put in my public folder?
2. After registered a ticket , it does not appear in the list, but is being informed at the top.

**Comment by thekordy** [comment]
you haven't added bootstrap to your view yet

http://getbootstrap.com/getting-started/

**Comment by marciocelebri** [comment]
I had already been added , sorry .

But the settings menu stopped working. And the servants tickets do not appear in the table.

![bootstrap](https://cloud.githubusercontent.com/assets/16846814/12557973/14f4b516-c36c-11e5-9bc2-efa380044284.PNG)

**Comment by balping** [comment]
bootstrap js must be included after jquery

**Comment by marciocelebri** [comment]
@balping Thanks ! But still keeps the data without appearing. 3 tickets have created and no list.
![tickets-saved](https://cloud.githubusercontent.com/assets/16846814/12562437/ef4f736a-c383-11e5-86dc-d31e69b0d65b.PNG)

**Comment by thekordy** [comment]
You need to do some debug inspection, if you are using firefox or chrome, do a right click and choose inspect and look for the **console** and for the **network** logs, see if the datatables ajax call is working correctly or what is the response from the server

![ticketit-debugging](https://cloud.githubusercontent.com/assets/11343048/12562847/ed7484dc-c3af-11e5-81b2-129622f7868f.png)

**Comment by marciocelebri** [comment]
@thekordy Thanks ! Here's how it is. The database contains 5 records.
![degug](https://cloud.githubusercontent.com/assets/16846814/12563884/2561bf1a-c38b-11e5-9557-567639fdb096.PNG)

**Comment by thekordy** [comment]
and what about the console tab? is it empty?

**Comment by marciocelebri** [comment]
POST 500 when insert new record. But, listing nothing appears on the console.

**Comment by thekordy** [comment]
hmmm .. and you are logged in with the same account who created the tickets, right?

**Comment by marciocelebri** [comment]
Exactly!

**Comment by thekordy** [comment]
you should not get Post 500 when creating tickets .. my last suggestion for tonight is to try to reinstall Ticketit again (or just do migrate rollback and hit tickets-install again)

**Comment by marciocelebri** [comment]
I will make a migrate:reset, if it does not reinstall . Inform if it works (or not)

**Comment by marciocelebri** [comment]
I will reinstall and see if that resolves the problem.

**Comment by marciocelebri** [comment]
Just signed up a status and now lists the registered tickets. Many thanks to all who have booked a little time out of your day to collaborate.

ps: did not need to reinstall .
pps: Very cool project.

**Comment by thekordy** [comment]
I am very happy you liked our project, if you could please explain more what was the problem? and how did you resolve it?

**Comment by marciocelebri** [comment]
Yes of course. After the settings here guided by you, the ticktes were not being displayed by not having registered status.

It was not really for show ? Would not it be interesting not allow the registration ?

**Comment by thekordy** [comment]
So there was no statuses created yet in the admin section, but you were able to create tickets with empty status? Sorry for that, I will look into this issue to make sure that won't happen.

Thank you for your feedback :+1:

**Comment by marciocelebri** [comment]
Registration was carried out and recorded in the database , but was not listed in my tickets. It is now running as well . I am available to help with anything you need . Thanks!
