### ISSUE TITLE
All Tickets were adressed to admin

### ISSUE THREAD

**Issue by jetwes** [thekordy/ticketit#144]
Since the update to 0.23 all new tickets were pushed to administrator instead of an agent of the spcified category?

**Comment by thekordy** [comment]
Yes, it does that, however this has been addressed here #137 and fixed. I will release a new patch soon. But you can just pull the new code and the issue will be resolved.

**Comment by jetwes** [comment]
Sorry, didn't see it. Thanks!

**Comment by thekordy** [comment]
Thank you for giving us your feedback, that helps us a lot :+1:
