### ISSUE TITLE
Setting up Mail

### ISSUE THREAD

**Issue by ghost** [thekordy/ticketit#145]
I want to suggest a better info (wiki) on setting up mail to work with ticketit, the default laravel doc referred to isn't detailed enough and that seems confusing. I still haven't figured it out -_- its returning 

```
Trying to get property of non-object (View: 
/var/www/laravel/ticket/vendor/kordy/ticketit/src/Views/emails/assigned.blade.php)
```

**Comment by thekordy** [comment]
Which email provider and method do you use?

**Comment by melihovgv** [comment]
I have the same issue. I use smtp. Such error occurs when I try to add new ticket.

**Comment by melihovgv** [comment]
89608954600@bk.ru

**Comment by thekordy** [comment]
@melihovgv [Try this tutorial](http://laravelcoding.com/blog/laravel-5-beauty-sending-mail-and-using-queues)

**Comment by melihovv** [comment]
I have the same issue. I can send email from my one of my routes.
![image](https://cloud.githubusercontent.com/assets/8608721/12704193/4f5554a0-c866-11e5-8080-da42a73385b8.png)
And it arrives
![image](https://cloud.githubusercontent.com/assets/8608721/12704199/7d1c7882-c866-11e5-9331-6584cfbb9e9c.png)
But when I want to add new ticket it returns next
![image](https://cloud.githubusercontent.com/assets/8608721/12704208/acdfa38c-c866-11e5-8628-61ab60158c7e.png)

**Comment by andylord56** [comment]
check that you have values for each status priority category and someone is assigned to that category otherwise errors like the above happen

**Comment by melihovv** [comment]
I add status, priorities, categories, agents and it works now. I think we may close issue. Thanks @andylord56.
