### ISSUE TITLE
admin_route or main_route in sub path break blade

### ISSUE THREAD

**Issue by duckzland** [thekordy/ticketit#147]
Test case : 
1. Define admin_route / main_route in a sub path like admin/tickets or display/tickets

Result : 
Some blade that uses link_to_route() will break, because link_to_route will search for admin.tickets.moreurl while $settings->grab('admin_route') will return admin/tickets.moreurl

Not sure where is the best place to fix this, maybe adding another parameter in grab to convert?

like $settings->grab('admin_route', 'slashtodot') which result in admin.tickets?

Thanks for the complete solution for support ticket :)

**Comment by thekordy** [comment]
Yes, routes configuration should be handled that way. I will look into it. and thank you for your feedback :+1:
