### ISSUE TITLE
Method [autoSelectAgent] does not exist.

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#152]
![image](https://cloud.githubusercontent.com/assets/10881327/13047177/423b5a10-d3d5-11e5-9654-426644ee21d8.png)

**Comment by thekordy** [comment]
I hope this fixes the issue, you would need to do `git update` to get this update.

**Comment by sunnyjayjay** [comment]
Thanks for that. However, that causes a new issue and I cannot now get to /tickets.

ErrorException in Setting.php line 56:
Trying to get property of non-object

**Comment by sunnyjayjay** [comment]
Ignore my previous issue. With your version 0.2.4 that has gone away. However the original error of autoSelectAgent does not exist is still occurring.
