### ISSUE TITLE
Nothing work after changing tickets and tickets-admin routes in admin configuration

### ISSUE THREAD

**Issue by m0h4** [thekordy/ticketit#153]
Hello,
Thank you for this very practical and powerful ticketing tool.

I just installed it yesterday and I was playing around in changing some parameters.

Settings >> Configuration (I changed the following) : 
tickets -> requests
tickets-admin -> requests-admin
master->master

When I applied the changes, nothing wanted to work.

Any idea?

Thank you.

**Comment by thekordy** [comment]
I know this is so obvious, but to just make sure, did you try using the new URLs (http://yourdomain/requests)?

**Comment by m0h4** [comment]
Thank you for your reply. None of them worked. I tried the old ones too.
I changed values in the database directly and changed the value of the language from "en" to NULL.
After that I cleared the cache and now everything is ok.

Thank you.
