### ISSUE TITLE
Is there a way to directly install it.

### ISSUE THREAD

**Issue by Rahulsharma0810** [thekordy/ticketit#154]
I read https://github.com/thekordy/ticketit/wiki/How-to-install-Ticketit and followed documentation but i am not able to install it as i bit new in laravel stuff and having lots of trouble in installing ticketit

Can you provide copy of working dir or web installer so we can just clone it and composer update,, so it canbe ready in 10 sec ?

**Comment by thekordy** [comment]
I have not tried that before, let me try it locally and see if that could work.

**Comment by Rahulsharma0810** [comment]
@thekordy Thanx and waiting for the package .... if you can provide it soon as possible that would be fine, thank you and kudo for the project

**Comment by jonuran** [comment]
A mi tambien me serviria tener un package con esta aplicacion. Gracias

**Comment by balping** [comment]
I have started working on one 'pre-configured' app, I'll upload it probably tomorrow

**Comment by jonuran** [comment]
balping that would be fantastic!

**Comment by balping** [comment]
I created a repo which makes the installation a lot easier. I could install ticketit [under a minute](https://github.com/balping/ticketit-app#installation-in-56-seconds) (well, the database had been created before and composer packages were in cache, but still)

So check it out: https://github.com/balping/ticketit-app

I've also updated the readme of ticketit to reference this installer

**Comment by jonuran** [comment]
Great!!!
balping you're the best!! 
It is usable 100%
thank you very much.

**Comment by thekordy** [comment]
> So check it out: https://github.com/balping/ticketit-app

Looks perfect, very well done @balping :+1:

**Comment by asopiah** [comment]
Am using windows. The installation via the cmd is a not working for my case. Kindly suggest for me a way out
