### ISSUE TITLE
Failed attempts at installing

### ISSUE THREAD

**Issue by corbinisme** [thekordy/ticketit#157]
I've tried many times to install this in my laravel 5.1 application.  I followed the two simple tests, but I got a route exception going to [project]/tickets-install locally.  On my server, it gave the same problem, until one lucky refresh it showed the install interface.  There was an issue in the install due to permissions on the folders on the server, and it only gives me the  "Ticketit needs upgrade, admin should login and visit ticketit install route" error. I tried to uninstall/remove, and that failed, and tried to manually migrate and rollback the DB, which failed.  

I've been pulling my hair out for hours on this.  I need to integrate a ticket system into the CRM application I am building, but I cannot install or remove anything at this point.

**Comment by ahmedEloi** [comment]
Look for that line Ticketit needs upgrade, admin should login and visit ticketit install route and comment it

**Comment by thekordy** [comment]
Doing reinstall would not reset the Ticketit database tables, so it won't reinstall unless you roll back the migrations. If you get `class not found` error while trying to roll back Ticketit migrations, then you need to add the new pushed migrations to the composer auto load by one of these commands:

``` shell
composer dumpautoload -o

or 

php artisan optimize
```

**Comment by xseguib** [comment]
Maybe a bit late, but i had the same issue, when you create the user, make sure that it is admin, you can set it throught your db setting to 1 the field called ticketit_admin or something like that.(Users table btw)

**Comment by thekordy** [comment]
@Borgoroth Thank you for sharing
