### ISSUE TITLE
login redirect to the same page (login)

### ISSUE THREAD

**Issue by ahmedEloi** [thekordy/ticketit#158]
I cant see tickets after I logged in it turns me back to login page

**Comment by thekordy** [comment]
I can't repeat the issue, Would you please give more details and how is your Laravel setup?

**Comment by ahmedEloi** [comment]
When I logged in I cant see my tickets it redirects me back to login page even if i am logged in

**Comment by tmcdon89** [comment]
Version .2 or 1?
