### ISSUE TITLE
App is promising, keep up the good work

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#16]
No issues here the app works as promised and easy to get it up and running.

I was able to re-assign a ticket manually in the ticket-admin section to another agent. Loved it - it worked great.

Would it be difficult to code it so and admin could re-assign an instance of the customers ticket to more than one agent?

Im wondering if a customer submitted a help ticket, than the responsible agent can review the master ticket and (if required) create sub-tickets (actions) and assign them to different agents and each agent needs to complete their own in house sub-action before the main ticket can be closed.

Imagine for a minute the customer submitting a ticket is more like the customer creating a small Project, and the admin reviews the ticket and assigns new sub-Tasks from that ticket to multiple inhouse agents to help user faster - and only the admin or responsible agent can communicate back on the original ticket and customer does not see the sub-tickets assigned to other agents.

I followed this tutorial and built this Laravel 5 Project/Task which is good but I was hoping is was more like yours and acted like a customer ticket system that supports sub-tasks from the main ticket.
https://www.flynsarmy.com/2015/02/creating-a-basic-todo-application-in-laravel-5-part-1/

Your app is great.

**Comment by thekordy** [comment]
Hello Fishmad,

Thank you very much :) , and thank you for giving suggestions, your suggestions and feedback are very welcomed and appreciated here.

For the idea of assigning the ticket to multiple agents, Is it like a ring group, where it notifies all group agents and the first agent to answer would be assigned? Or it's open for all group members and no one would be particularly assigned at anytime? 
Could you please give us a scenario?

Sub-ticket .. Good point :)  
It's like new tickets where the agent of the master ticket is the owner of sub-tickets, Right?
What we might need: 
1. button for fast creation of sub-tickets
2. add link in records to link subs with their master
3. define rules
4. lock for master ticket to not being closed until subs are closed
what else?

**Comment by fishmad** [comment]
I love the concept of auto assigning tickets to an agent with the least amount of tickets I see where this would be very useful as a default setting but I also think we could be allowed to override a category and assign a default recipient or category owner - kind of like the scenario below.

__Scenario__: Bob is a customer and has purchased a software product from me (ABC Company)
Bobs software crashed, Bob copies the software error log and opens a new support ticket - say PC Support category.

The PC support category has 5 agents one of them who would be the category owner (Manager if you wish) the support ticked is automatically assigned to the manager.

Manager then receives email about new ticket, manager reviews ticket and determines the customers software crash could be related to one or more areas ie. User Error, Backend Developer Bug or Front End Design issue.

__The 5 agents attached to PC Support category have these skill sets.__
1. Manager
2. Software Designer
3. Software Coder #1 - CBA Skill
4. Software Coder #2 - ABC Skill
5. Software Client Trainer

The manager decides this ticket may require the expertise of a Software Designer, Software Coder #2 and Software Client Trainer so the manager assigns 3x sub-tickets with the below actions:

__Sub-Ticket 1a.__ Software Designer you need to review software frontend for design bugs (time to complete 1 days)
__Sub-Ticket 1b.__ Software Coder #2 you need review source code related to error log for bugs (time to complete 2 days)
__Sub-Ticket 1c.__ Software Client Trainer can you ring customer and step through usage instructions but only complete this step after Software Designer and Software Coder #2 have completed their tickets and confirmed the error is not with our software (time to complete 3 days).

__The manager may then reply to the ticket creator.__

>Dear Ben,
>
>We are sorry to hear of your troubles and are currently looking into this.
>My IT team are currently reviewing the error log for system compatibility issues and you can expect a phone call from one of the team with-in the next 3 days.
>
>Thank you
>Manager - ABC Company

In the background the Software Designer reviews the front end design and reports back on hes sub-ticket.

>Boss no issues on front end, closing ticket.

The Software Coder #2 hasn’t responded in two days, (away from work sick or something) manager notices the ticket in nearly overdue and remains un-responded and so he reassigns the ticket Software Coder #1 who completes the task and updates ticket.

>Dear boss I have made a small improvement to the code - customer to download update, closing ticket.

Day 3. Software Client Trainer rings Ben, Ben we have a fix for you, please download this update and I will walk you through the process.
>Dear Boss I have finished helping customer Ben and he is now happy. closing this ticket.

Manager is than automatically notified the last sub-ticket has been closed (alternatively the Manager can just reviews dashboard for open/outstanding tickets), he can now update client through master ticket and close it.

>Dear Ben.
>
>I’m am happy we have help you.
>
>Your issue appears to have been resolved we are now closing this ticket as completed.
>
>Thank you.


*BTW I don’t sell software or offer support like above is just a model concept.*

__I think it would also be good if the category owner could mass-assign a duplicate ticket to each team members.__

Write up a master ticket; assign a copy to Matt, Mel, John and Tom (an possibly 50 other workers)
>Message:
>You are required to participate in one of technology webinars being conducted daily over the next week to refresh your knowledge.
>
>Please close your (this) ticket when you have completed the task so I can mark you off as done.
>
>You’re Boss.

**Comment by FusionDesign** [comment]
Thank you for your detailed writeup. I'll look into implementing this pending a current big PR with Complete / Open Tickets. I'd directly push it but it's my first big commit since being given contributor, as well as my first project collab; so I'm nervous / no idea what I'm doing.

**Comment by thekordy** [comment]
@fishmad Let me sum it and correct or add if something is missing:

1. Assign category admin or team leader
2. Option to either auto assign (dynamically) or to default assign all category tickets to the category admin
3. Fast creation of sub-tickets from within the ticket, this option is for category admin
4. lock master ticket to not being closed until subs are closed
5. Notify the agent (Admin) of master ticket when sub tickets are closed
6. Notify sub-tickets agents with each other progresses

**Comment by thekordy** [comment]
@FusionDesign  Beleive me, You are doing great man :+1:

**Comment by fishmad** [comment]
@thekordy you nailed it in 6 bullets points (took me a book to explain), number 6 might be too hard to code.

If you two need any help with this project in general, happy to help where I can - ie. convert hard coded languages in view files into dynamic laravel multi language files etc.

The Trans method is great if you envisage making the app multilingual in the future but it's also great for those who just want override the default text/wording by modify only one view/lang/en/vendor file - then there is no need to modify the views.

```From:
<td>Description:</td> 
To:
<td>{!! trans('ticketit/tickets.create_new_ticket_description') !!}</td>

		// resources/views/vendor/ticketit/tickets/create.blade.php
		'page_new_ticket_form' => 'New Ticket Form',
		'create_new_ticket' => 'Create New Ticket',
		'create_new_ticket_subject' => 'Subject:',
		'create_new_ticket_brief_issue' => 'A brief of your issue ticket',
		'create_new_ticket_description' => 'Description:',
		'create_new_ticket_describe_issue' => 'Describe your issue here in details',
		'create_new_ticket_priority' => 'Priority:',
		'create_new_ticket_category' => 'Category:',
		'create_new_ticket_back' => 'Back',
		'create_new_ticket_submit' => 'Submit',

		// resources/views/vendor/ticketit/tickets/show.blade.php
```

**Comment by thekordy** [comment]
@fishmad Thank you and yes we need help :)

As you said, I also believe that localization is the most needed feature now, If you can help on this, that would be great :)

These two issues #21 and #22  I opened to collaborate about localization, or you might like to submit a pull request on v0.1.0 branch , your help would be very appreciated.

**Comment by fishmad** [comment]
Will do.

**Comment by thekordy** [comment]
I have good feelings about upcoming branches v0.1.0, 0.2.0, and 0.3.0 .. it's going so mature since now :) 
thanks to everyone gave his feedback, that helped us a lot.

and special Big Thanks to you two @FusionDesign and @fishmad

**Comment by FusionDesign** [comment]
Thanks @thekordy - I did not know you could reference people like that. Thank you so much for merging everything so fast. Incredible work all around
