### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by andylord56** [thekordy/ticketit#165]
Getting this error on a application without emails:

ErrorException in ee41fae0dfbea6acf24182ab907aa636cf03f90e.php line 22:
Trying to get property of non-object (View: /home/wwwwbpsalesco/salescrm/vendor/kordy/ticketit/src/Views/emails/assigned.blade.php)

I am guessing it is because the emails have not been setup is their anyway to disable them?

Edit:

I have added a mail trap and this does not solve this issue

Edit2: 

Found the problem of no statuses being assigned as none was added 

Future possible fix? 
Add a uncategorized status that cannot be deleted initially

**Comment by thekordy** [comment]
Go to Settings->Notifications and turn off the email notifications

status_notification, comment_notification, queue_emails, assigned_notification
