### ISSUE TITLE
All Open Tickets Section

### ISSUE THREAD

**Issue by andylord56** [thekordy/ticketit#166]
-- Currently can only see your own tickets a admin would need to see all tickets

-- Also a quick edit/close/open/comment buttons would be nice for the tickets

-- Ability to assign more then one agent to a ticket

-- Ability to add tags to each Ticket

-- Multiple categorizes to be assigned

-- Search by category

**Comment by balping** [comment]
Most of these are done, feel free to add the others to v2 discussion threads.
