### ISSUE TITLE
Updating ticket status: notification e-mail has correct header but incorrect content

### ISSUE THREAD

**Issue by kebian** [thekordy/ticketit#169]
When updating the ticket status, the notification e-mail has the correct header but the incorrect content.  For example, if I close a ticket then the e-mail header says **"Kebian updated My new ticket status to Complete"** but the e-mail content says **"Kebian changed the status of "My new ticket" from Pending to Pending"**

This is caused by the `default_reopen_status_id` and `default_close_status_id` settings being seeded as `false`.  Shouldn't they instead be the following?

```
default_reopen_status_id = 1 (for Pending)
default_close_status_id = 2 (for Solved)
```

The complication is of course that the statuses can be changed by an administrator so 1 might not always be "Pending" and 2 might not always be "Solved" so I thought I'd ask for your thoughts before submitting a pull request.

**Comment by thekordy** [comment]
I couldn't agree more
