### ISSUE TITLE
How to install  laravel ticketit on local wamp server?

### ISSUE THREAD

**Issue by cruxster** [thekordy/ticketit#171]
I have Tired to install it wamp server but cant install .
1. after  doing  Step 1. Run this code via your terminal (1-2 minutes)
   
   composer require kordy/ticketit:0.*

then cant find config folder plus master.baled.php  other steps please tell me detailed steps how to install ticketii on local server

**Comment by qublibjohnny** [comment]
I'm also stuck at this stage. I'd like to install it on a Windows XAMPP environment. New to Laravel and Composer. 

Any help is appreciated.

**Comment by thekordy** [comment]
This package will be useful only for people whom already have Laravel projects running, if you just want a helpdesk system, you might better think of a [stand alone tickets system](http://blog.capterra.com/the-7-best-free-help-desk-software-tools/).

**Comment by qublibjohnny** [comment]
Thanks for the suggestions :) Maybe I just need to read up on Laravel more as it's very new to me. This looks like such a great helpdesk though, pity I can't get it up and running on my environment so easily :( Due to my skill set though I suppose.

**Comment by thekordy** [comment]
@qublibjohnny If you are going to learn Laravel, I suggest you start from [Laracasts](https://laracasts.com/series/laravel-5-from-scratch) and [Learning Laravel](http://learninglaravel.net/books/laravel/installing-laravel) .. will help you a lot
