### ISSUE TITLE
110 database calls to open Dashboard view!

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#174]
Is it not possible to make this more db efficient?

**Comment by thekordy** [comment]
How?

**Comment by sunnyjayjay** [comment]
In my app, opening the dashboard,113 queries are triggered. Of these 19 are due to my app and the rest to Ticketit.

**Comment by thekordy** [comment]
addressed in v2

**Comment by sunnyjayjay** [comment]
v2?
