### ISSUE TITLE
Replace datatable

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#182]
Hi!

I'm think of replacing datatable with [bootgrid](http://www.jquery-bootgrid.com/Examples). I've used it in one of my projects and I'm quite satisfied with it. Compared to datatable it's much-much simliper, we could get rid of all crap that datatable means. What do you think @thekordy ? If you agree, I'll start doing it. I saw it once on an old todo-list that the removal of datatable was actually planned.

**Comment by thekordy** [comment]
Hi
Actually I am interested, let's do it :+1:

**Comment by fishmad** [comment]
Is it better?

**Comment by balping** [comment]
In my opinion, yes. There are fewer possibilities, but more than enough.

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/commit/cb4711b12cd1ac099d28174fbd3766b89b2707b3

Here's the first approach. Still needs testing

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/commit/47e46b8904239c6bcdd2c31bba77e8f8e0c1307d

I added text search functionality. It searches in subject, body and comments

**Comment by kasirye** [comment]
Hi balping, the bootgrid is not loading data. what could the problem be. have tried to troubleshoot but have failed. Please help

**Comment by balping** [comment]
Hi @kasirye please use the network tab of chrome dev tools and see if anything is wrong there

**Comment by kasirye** [comment]
@balping there is nothing wrong... i see no errors. I wonder where the problem is... tried a reinstallation but same issue.

I can see the count  of the active tickets in the upper nav-pill but not in the bootgrid. Do you think the problem is coming from the TicketsController@data function

**Comment by balping** [comment]
Maybe a stupid question, but are there any tickets in the database? I'll make a fresh install anyways and see what' wrong

**Comment by kasirye** [comment]
Yes @balping, i have some tickets in the database
![bootgrid](https://cloud.githubusercontent.com/assets/11265554/14937103/c0cfea38-0f05-11e6-8074-3f75a17551e4.png)

**Comment by balping** [comment]
It looks like bootgrid's js file isn't loaded check, there's a reference to it in the page's source html. If not, maybe your blade files are not set correctly

**Comment by kasirye** [comment]
Perfect @balping,  It was my blade master template. Thanks alot for your time. I appreciate
