### ISSUE TITLE
changing ticketit's source files

### ISSUE THREAD

**Issue by yizhihou2** [thekordy/ticketit#185]
Hi, I was trying to combine ticketit's logic into my project. There are some parts that I would like to unify for my project and ticketit, like nav.blade.php and errors.blade.php files. Some redundancy will be removed too. 

The question is if I changed the source code of ticketit in my local project, will I got a problem when ticketit has a new version and I run "composer update"? Will I lose all my changes? Thanks.

**Comment by balping** [comment]
Dont change the source code of the project. If you don't like one specific blade file, you can override it. For example create file resources/views/vendor/ticketit/shared/nav.blade.php to override this project's nav.blade.php file

https://laravel.com/docs/master/packages#views

**Comment by balping** [comment]
However if you think, you can improve the quality of the code, feel free to make pull requests for the 1.0 branch
