### ISSUE TITLE
Code view allows scripts to run - dangerous - can we turn off Code View

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#192]
In the Ticketit editor, if you choose code view and enter some javascript, when you leave code view the script runs. This is a problem as the script could be malicious. Our users would not need Code View, is there any way we can turn it off?

**Comment by balping** [comment]
Which version are you using?

**Comment by sunnyjayjay** [comment]
0.2.3

**Comment by balping** [comment]
If you set `editor_enabled` to `0` in your settings, does it help?

**Comment by sunnyjayjay** [comment]
Yes, it does. But I think we should still be able to use the code editor and not have the contents run as scripts, if possible.

**Comment by balping** [comment]
Could you provide an example XSS code? It's very likely that html is not filtered correctly then

**Comment by sunnyjayjay** [comment]
A good example is to type this into the code editor and then save it. It runs immediately.
    <script>
    alert('hello world');
    </script>

**Comment by sunnyjayjay** [comment]
Sorry, the code was removed by GitHub's editor! Try again:

`<script>alert('hello world')</script>`

**Comment by balping** [comment]
Oh, yes, now I remember it. It's a bug in summernote: https://github.com/summernote/summernote/issues/1627

They don't seem to fix it. But don't worry, we are filtering input at server side. Just save it and see what's in database, the script tag is removed. So you can run JS only in your own browser using this method. So nothing dangerous here.
