### ISSUE TITLE
Swift_TransportException

### ISSUE THREAD

**Issue by Soxfrot** [thekordy/ticketit#194]
When i reply a ticket, it says me that error:

Swift_TransportException in AbstractSmtpTransport.php line 383: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required"

I'm already authenticated, what should i do?

**Comment by thekordy** [comment]
This message is for the SMTP authentication, see, when you reply to the ticket, the system tries to send a notification email to the ticket owner and to the agent, but seems like it gets an authentication error when it tries to send SMTP email. 

Review back your SMTP email settings, or just disable email notification from admin panel settings if you are not using email system.

**Comment by Soxfrot** [comment]
Thank you, you helped me a lot :)
