### ISSUE TITLE
ErrorException in Agent.php line 131: Trying to get property of non-object

### ISSUE THREAD

**Issue by shilpaGowda** [thekordy/ticketit#196]
Hai, Thanks for the great package.

I'm facing an issue. When I login as an agent and try to access the ticket, I'm getting **Trying to get property of non-object** error in **Agent.php**. For admin everything is working fine, but agents can't view the ticket assigned to them.

![localhost 8000 tickets 1](https://cloud.githubusercontent.com/assets/12569566/15501822/6af42054-21cd-11e6-90ce-cd807688bddb.png)

**Comment by thekordy** [comment]
Have you changed the `main_route` setting?

**Comment by shilpaGowda** [comment]
No. I haven't changed any default routes. All the tickets are loading, if I try to access ticket with id 1, I'm getting this error even if the ticket is assigned to me.

**Comment by balping** [comment]
This line is causing the error: https://github.com/thekordy/ticketit/blob/0.2/src/Models/Agent.php#L131

It seems no agent is assigned to that ticket. Are auto-assign settings set up?

**Comment by waleedtfps** [comment]
i guess the problem is that its passing null value to isAssignedAgent function . i was not able to find the call for this function .so i just return true like 
`if (auth()->check() && Auth::user()->ticketit_agent) { return true; }`
not a good idea but works atleast .

**Comment by thekordy** [comment]
please update to [v0.2.7](https://github.com/thekordy/ticketit/tree/v0.2.7)
