### ISSUE TITLE
Dashboard paging not working well

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#197]
In Dashboard, select Users tab. If you have more than one page the pagination control appears. You select next page and it returns you to the Categories tab.

**Comment by balping** [comment]
But if you click again on the users tab, you'll be on the right page

**Comment by sunnyjayjay** [comment]
I agree - but are you happy with that behaviour?

**Comment by sunnyjayjay** [comment]
You should not really close this. It is not acceptable UI behaviour. We will receive support requests for it and be unable to resolve them. You do need to fix this.

**Comment by balping** [comment]
To be honest, I can't follow you. You made a bug report, I fixed the bug, now what's the problem?

**Comment by sunnyjayjay** [comment]
Apologies. I thought you had signed off saying "But if you click again on the users tab, you'll be on the right page" and that was that. I did not realise you had made a fix. Thanks very much. I am enjoying your product very much and my comments are in the spirit of trying to help you iron out any bugs.

**Comment by balping** [comment]
Ok, no problem. Thanks :-)

**Comment by thekordy** [comment]
Thanks @balping :+1:
