### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by eduardopaludo** [thekordy/ticketit#198]
Hello, 

I need help for install ticketit, follow all step by step but the error appear.

> Exception in InstallController.php line 66:
> Ticketit needs upgrade, admin should login and visit ticketit install route
> in InstallController.php line 66
> at InstallController->index()
> at call_user_func_array(array(object(InstallController), 'index'), array()) in Controller.php line 80
> at Controller->callAction('index', array()) in ControllerDispatcher.php line 146
> at ControllerDispatcher->call(object(InstallController), object(Route), 'index') in ControllerDispatcher.php line 94
> at ControllerDispatcher->Illuminate\Routing{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
> at Pipeline->Illuminate\Routing{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
> at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
> at ControllerDispatcher->callWithinStack(object(InstallController), object(Route), object(Request), 'index') in ControllerDispatcher.php line 54
> at ControllerDispatcher->dispatch(object(Route), object(Request), 'Kordy\Ticketit\Controllers\InstallController', 'index') in Route.php line 174
> at Route->runController(object(Request)) in Route.php line 140
> at Route->run(object(Request)) in Router.php line 724
> at Router->Illuminate\Routing{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in Authenticate.php line 28
> at Authenticate->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in VerifyCsrfToken.php line 64
> at VerifyCsrfToken->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in StartSession.php line 62
> at StartSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in EncryptCookies.php line 59
> at EncryptCookies->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
> at Pipeline->then(object(Closure)) in Router.php line 726
> at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
> at Router->dispatchToRoute(object(Request)) in Router.php line 675
> at Router->dispatch(object(Request)) in Kernel.php line 246
> at Kernel->Illuminate\Foundation\Http{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
> at Pipeline->Illuminate\Routing{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
> at Pipeline->then(object(Closure)) in Kernel.php line 132
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
> at Kernel->handle(object(Request)) in index.php line 54
> at require_once('C:\Users\eduardoh3069_00\Documents\help\public\index.php') in server.php line 21

Thanks!

**Comment by thekordy** [comment]
Login with admin account or login with the user that has id = 1 and go to ticketit-install

**Comment by eduardopaludo** [comment]
Ok, solved! Thanks

**Comment by 4nakata** [comment]
I log in with the user id = 1 and still have the same mistake of @eduardopaludo
