### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Wipsly** [thekordy/ticketit#2]
Hi,

when I run : composer require kordy/ticket dev-master

I get the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package kordy/ticket could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Update: There is a error in your documentation. It must be ticketit and not only ticket.

Can be closed

**Comment by thekordy** [comment]
Thank you for your feedback, I will fix that.
