### ISSUE TITLE
Upload file required for especified Status

### ISSUE THREAD

**Issue by eduardopaludo** [thekordy/ticketit#204]
How to for field upload file or some field be required in especified Status?

Example:

Status -> In order (Can't close if not attach document)

Thanks!

**Comment by thekordy** [comment]
you will need to make your own tickets controller, extend package TicketsController, override the store function, modify the tickets/create.blade.php to submit action to the new controller also you will need a new route to your new controller.

**Comment by eduardopaludo** [comment]
Ok, i'll try. Thanks.
