### ISSUE TITLE
New ticket is not displayed on fresh laravel installation

### ISSUE THREAD

**Issue by aenciso** [thekordy/ticketit#205]
Steps to reproduce:
1. Run the following commands:

```
git clone https://github.com/laravel/quickstart-basic quickstart
cd quickstart
composer install
php artisan migrate
```
1. Register a new user
2. Install ticketit

```
composer require kordy/ticketit:0.*

```
1. Update config/app.php in Service Providers section 
2. Go to http://your-project-url/tickets-install to finalize the installation
3. Assign only registered user as admin
4. Create statuses, categories and priorities
5. Go to http://your-project-url/tickets and create a new ticket
6. Ticket is created in DB but not displayed in page

![image](https://cloud.githubusercontent.com/assets/3810819/15842914/3a6a8878-2c55-11e6-9e0a-083b496b7300.png)

![image](https://cloud.githubusercontent.com/assets/3810819/15842932/60ba388e-2c55-11e6-8368-07c49ee4d4dd.png)

**Comment by balping** [comment]
Seems like you dont set up blade correctly,  js files required by tbe project are not included

https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template

**Comment by aenciso** [comment]
My mistake. I managed to missed @yield('footer').

Thanks

**Comment by ghost** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/38324285/77324664-1d495800-6d3d-11ea-86ee-6215c4c0ee90.png)

Hi, i have creating 5 tickets but it does not display the list, please help
