### ISSUE TITLE
Bug in edit ticket

### ISSUE THREAD

**Issue by eduardopaludo** [thekordy/ticketit#206]
I want that fields 'Subject' and 'Content' are disables in edit ticket, but when i remove 'required' and add 'disabled' to fields 'Subject' and 'Content' appears the error below.

![image](https://cloud.githubusercontent.com/assets/10199088/15899169/3f077964-2d71-11e6-9938-a60c69360a10.png)

![image](https://cloud.githubusercontent.com/assets/10199088/15899190/5123df5c-2d71-11e6-9581-91d95032d68c.png)

![image](https://cloud.githubusercontent.com/assets/10199088/15899199/58f97eda-2d71-11e6-8630-db52302d2706.png)

**If i remove 'disabled', works!**

Can someone help me?

Thanks!

**Comment by thekordy** [comment]
What about making them hidden?

**Comment by thekordy** [comment]
But let me mention that making them hidden or disabling them doesn't stop users from submitting them, you need to edit TicketsController upload function to the appropriate validation.

**Comment by eduardopaludo** [comment]
Yes, hidden Ok, but disabled not works?

**Comment by thekordy** [comment]
Won't work because of the validation rules as it makes subject and content fields required fields, and disabled fields won't be posted.
