### ISSUE TITLE
Not an issue: Change notification email setting: from

### ISSUE THREAD

**Issue by aenciso** [thekordy/ticketit#209]
If I am an admin and I assign a ticket to myself I received an email notification but the from address is my email.
GMail raises a warning saying that the email might not be sent by me, which is correct.

Is there any way of updating 

$m->from($notification_owner->email, $notification_owner->name);

to something else?

perhaps something like

env('MAIL_FROM')

Thanks

**Comment by maximusblade** [comment]
I have the exact same limitation.
I use postmark and it requires my "non-laravel admin" email
where or how do I configure this without messing with the package ?

**Comment by thekordy** [comment]
fixed here #207 .. until a new patch is released, you can use [0.2.x-dev](https://packagist.org/packages/kordy/ticketit#0.2.x-dev) version with the new patches.

**Comment by aenciso** [comment]
Thanks a lot!
