### ISSUE TITLE
Correct way of assigning tickets and notifications

### ISSUE THREAD

**Issue by aenciso** [thekordy/ticketit#211]
Hi,

At the moment I have to admins for the ticketing system. If a new ticket is created, one admin receives an email and if another ticket is created, an email is sent to the other admin.

Is there any way to send an email to both or all admins when a ticket is created?

I tried to add a comma separated values for all users I want to get notifications when a new ticket is created but still only sends to only one person.

Thank you.

**Comment by thekordy** [comment]
It sends email to the assigned agent not the admin, seems that each time one of them picked automatically as the assigned agent so this why it gets the notification.

If you want to alter this behaviour, disable ticketit notification setting, in your AppServiceProvider, you can hook into the ticket created event and send the notification the way you need. You can get an idea on how to hook into the new created ticket event [here](https://github.com/thekordy/ticketit/blob/0.2/src/TicketitServiceProvider.php#L120)
