### ISSUE TITLE
 Swift_TransportException in AbstractSmtpTransport.php line 383: Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user

### ISSUE THREAD

**Issue by yizhihou2** [thekordy/ticketit#212]
When a new tickect is created, I got the following error:

 Swift_TransportException in AbstractSmtpTransport.php line 383: Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user

I used smtp mail driver, and in config/mail.php, I have

'from' => ['address' => null, 'name' => null],

**Comment by thekordy** [comment]
Make sure to adapt the `config/mail.php` from to be same as the configured smtp address, and update to [ticketit v0.2.6](https://github.com/thekordy/ticketit/releases/tag/v0.2.6)

**Comment by yizhihou2** [comment]
Thanks. I just ran a `composer update` and it upgrade to 0.2.7.

When creating a new ticket, the error is changed to: 

Swift_TransportException in AbstractSmtpTransport.php line 162:
Cannot send message without a sender address

My smtp setting is right, because I can send emails in other scenarios, like when a user register to my system and getting a welcome email, etc. Thanks.

**Comment by thekordy** [comment]
Make sure 'from' => ['address' => null, 'name' => null] in `config/mail.php` is set as the same as the smtp settings and not null.

**Comment by yizhihou2** [comment]
I changed it to 'from' => ['address' => env('MAIL_USERNAME'), 'name' => env('MAIL_USERNAME')], and it worked! Thanks for your help!

**Comment by yizhihou2** [comment]
a little bit strange...I didn't find any email though. Neither in the user's email inbox, nor the sender's email send box...

**Comment by thekordy** [comment]
It doesn't send notification to the user who did the action, so if the user (ticket owner) commented on the ticket, only the agent will be notified, it the agent commented, only the user will be notified. 

The concept is if I am the one who have done the action, I don't need to be notified, the others participants whom should be notified.

**Comment by yizhihou2** [comment]
I see. Thanks for the clarification.
