### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by yizhihou2** [thekordy/ticketit#213]
I upgraded from 0.2.5 to 0.2.7. After I created a new ticket as a user and tried to open this ticket again, I got this error message:

ErrorException in Agent.php line 147:
Trying to get property of non-object

![1](https://cloud.githubusercontent.com/assets/12182051/16382004/a28b8f1c-3cb1-11e6-9785-8bde773c8130.png)

**Comment by thekordy** [comment]
Try a fresh install, remove ticketit migrations from database/migrations, comment  out ticketitServiceProvider, do `composer remove kordy/ticketit`, then do `composer require kordy/ticketit`, then uncomment TicketitServiceProvide in `config/app.php`

**Comment by yizhihou2** [comment]
Thanks, it works like a charm!
