### ISSUE TITLE
Problem with /Models/Agent.php , ticket id not pass to isTicketOwner and isAssignedAgent

### ISSUE THREAD

**Issue by igarbera** [thekordy/ticketit#218]
Hello! I have such problem on fresh installation of last version of ticketit : 
when user try to open his ticket, or moderator try to open his ticket:

 https://scr.pics/111111.png_2016-07-05_23-10-32.png

The problem is in methods: isAssignedAgent and isTicketOwner, Ticket::find($id)->user->id  and Ticket::find($id)->agent->id returns false, but when I check it in artisan tinker and set $id manually, it returns correct user id (works fine). How to fix it?

**Comment by thekordy** [comment]
Please update to v0.2.8

**Comment by igarbera** [comment]
Awesome! I see, you update ResAccessMiddleware , and now all works fine (laravel 5.2.). Thank you wery much for tiketit, it's really good helpdesk!

**Comment by thekordy** [comment]
Glade that fixed your issue, thank you for using Ticketit.
