### ISSUE TITLE
ticket list not showing 

### ISSUE THREAD

**Issue by dixit-neeraj** [thekordy/ticketit#223]
hello all 
i am using laravel 5.2 and this package 

currently i facing some weird issue .
i am not enable not see any listing .. 
i think there is some error Call to a member function diffForHumans() on string 

![screenshot from 2016-07-15 17 00 41](https://cloud.githubusercontent.com/assets/8327335/16872987/fcb7f908-4aad-11e6-9a44-226578ddd56f.png)
![screenshot from 2016-07-15 17 00 55](https://cloud.githubusercontent.com/assets/8327335/16872988/fcbcc744-4aad-11e6-8bea-ae40561b5dfa.png)

plz help

**Comment by jryd** [comment]
I am using it on 5.1 and whilst I can successfully create tickets they do not show in my list.

My Active count is 4 but I cannot see any in the table.

**Comment by jryd** [comment]
I am encountering the same issue.

**Comment by thekordy** [comment]
please update to kordy/ticketit:0.2.x-dev or clone 0.2 branch

**Comment by dixit-neeraj** [comment]
thanks mr. kordy ...
right now i am using laravel 5.2 and its default auth for login and register 
making command   " php artisan make:auth" ...
it works fine with your package ..... 

BUT NOW I have to use api for login custom auth ...any suggestion how it works with your package .

**Comment by small-tommy** [comment]
After delete status or category or priority, tickets with this status (category, priority) not available.
If set custom status in admin panel, but after delete this status, then tickets are no created - error.

**Comment by thekordy** [comment]
This is addressed in v2
