### ISSUE TITLE
Use username instead of name

### ISSUE THREAD

**Issue by jryd** [thekordy/ticketit#224]
In my application I don't use names, instead we just use usernames for our members.

When I tried to install I get an error that it couldn't select from the column name.

I have a accessor in my `User` model to `getNameAttribute()` which works fine for other parts of my application.

Are you able to introduce a config variable that allows us to set what column we want to use for name? Or that can leverage the accessor for `getNameAttribute()` in our User model.

**Comment by jryd** [comment]
I see this is actually referenced in a feature request; 181.

If I wanted to modify this now, which files would I need to change?

**Comment by thekordy** [comment]
You might need to find all occurrences of name and replace it with username, something like [this](https://github.com/thekordy/ticketit/search?utf8=%E2%9C%93&q=-%3Ename)

**Comment by jryd** [comment]
I changed the references of `name` to `username` in all the eloquent calls to `list` and this solved it as my `getNameAttribute()` accessor works for the rest of the app.
