### ISSUE TITLE
Ticket homepage not providing any guttering

### ISSUE THREAD

**Issue by jryd** [thekordy/ticketit#227]
I've noticed on every page but the 'active tickets' (/tickets) and 'completed tickets' (tickets/complete) there is appropriate guttering around the view.

When on these pages, despite being encompassed by a row div, they are not being held in a col and so they touch the sides of the page:

![no gutter](https://cloud.githubusercontent.com/assets/13251203/16942784/1ebb0f68-4dec-11e6-97e6-7770c5f2eaef.JPG)

When I add in a `<div class="col-md-12">` just inside the start of the row (and the appropriate close tag at the end) it fixes it.

![guttering](https://cloud.githubusercontent.com/assets/13251203/16942835/6af314ac-4dec-11e6-937c-2d8ab252f135.JPG)

![gutter source](https://cloud.githubusercontent.com/assets/13251203/16942836/6c81ac8e-4dec-11e6-8a1a-ddffab975758.JPG)

I've tried editing `src/Views/index.blade.php` and `src/Views/tickets/index.blade.php` in my own fork of this repo, but have not had any luck getting this to work.

What views need to be updated for the appropriate guttering to work on the  'active tickets' (/tickets) and 'completed tickets' (tickets/complete) views?

**Comment by thekordy** [comment]
wrap the @yield('content') in the master view in a view with class
`container` or any other class that puts margins or paddings.

## 

Best Regards,
Ahmed Kordy

**Comment by fishmad** [comment]
This is due to bootstrap 3 row class if you nest a container class inside
row it should provide the default gutter.

**Comment by jryd** [comment]
Thanks for your help guys, love this package by the way!

**Comment by thekordy** [comment]
Glad to hear that, and thank you for using Ticketit
