### ISSUE TITLE
use with custom login functioniality

### ISSUE THREAD

**Issue by dixit-neeraj** [thekordy/ticketit#228]
hello mr. @thekordy  
i am using my own function for login/authentication through session managing 

how can i use your package then . 

Thanks 

FYI :- i know it works well with default users and auth .

**Comment by thekordy** [comment]
Hi,
I think it requires auth::user(), App\User model, user `name` and `email` fields, some people could get it work with custom auth systems by hacking the package core or [providing alias model](https://github.com/thekordy/ticketit/issues/135) and [model attributes](https://github.com/thekordy/ticketit/issues/224), if you have time and you know how to hack code, you can try and I will answer any question if I can.
