### ISSUE TITLE
Datatable search produces 500 error

### ISSUE THREAD

**Issue by jryd** [thekordy/ticketit#229]
I have forked this repo and have edited it to use `username` rather than `name` for the most part.

I'm able to view tickets, create them, edit them etc, but when I try to manipulate the datatable I begin getting 500 errors on the page.

For example if I try to sort by agent I get this error:

> QueryException in Connection.php line 662:
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `ticketit` inner join `users` on `users`.`id` = `ticketit`.`user_id` inner join `ticketit_statuses` on `ticketit_statuses`.`id` = `ticketit`.`status_id` inner join `ticketit_priorities` on `ticketit_priorities`.`id` = `ticketit`.`priority_id` inner join `ticketit_categories` on `ticketit_categories`.`id` = `ticketit`.`category_id` where `completed_at` is null and (LOWER(`ticketit`.`id`) LIKE %%fc%% or LOWER(`subject`) LIKE %%fc%% or LOWER(`ticketit_statuses`.`name`) LIKE %%fc%% or LOWER(`ticketit`.`updated_at`) LIKE %%fc%% or LOWER(`users`.`name`) LIKE %%fc%% or LOWER(`ticketit_priorities`.`name`) LIKE %%fc%% or LOWER(`users`.`name`) LIKE %%fc%% or LOWER(`ticketit_categories`.`name`) LIKE %%fc%%)) count_row_table)

If I try to use search I get the following error:

> QueryException in Connection.php line 662:
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `ticketit` inner join `users` on `users`.`id` = `ticketit`.`user_id` inner join `ticketit_statuses` on `ticketit_statuses`.`id` = `ticketit`.`status_id` inner join `ticketit_priorities` on `ticketit_priorities`.`id` = `ticketit`.`priority_id` inner join `ticketit_categories` on `ticketit_categories`.`id` = `ticketit`.`category_id` where `completed_at` is null and (LOWER(`ticketit`.`id`) LIKE %%e%% or LOWER(`subject`) LIKE %%e%% or LOWER(`ticketit_statuses`.`name`) LIKE %%e%% or LOWER(`ticketit`.`updated_at`) LIKE %%e%% or LOWER(`users`.`name`) LIKE %%e%% or LOWER(`ticketit_priorities`.`name`) LIKE %%e%% or LOWER(`users`.`name`) LIKE %%e%% or LOWER(`ticketit_categories`.`name`) LIKE %%e%%)) count_row_table)

I've searched through the repo and believe the search functionality is coming from `TicketsController@data` but for the life of me I can't see where I need to change `name` to `username`.

This is my current `data()` function:

```
public function data(Datatables $datatables, $complete = false)
    {
        $user = $this->agent->find(auth()->user()->id);

        if ($user->isAdmin()) {
            if ($complete) {
                $collection = Ticket::complete();
            } else {
                $collection = Ticket::active();
            }
        } elseif ($user->isAgent()) {
            if ($complete) {
                $collection = Ticket::complete()->agentUserTickets($user->id);
            } else {
                $collection = Ticket::active()->agentUserTickets($user->id);
            }
        } else {
            if ($complete) {
                $collection = Ticket::userTickets($user->id)->complete();
            } else {
                $collection = Ticket::userTickets($user->id)->active();
            }
        }

        $collection
            ->join('users', 'users.id', '=', 'ticketit.user_id')
            ->join('ticketit_statuses', 'ticketit_statuses.id', '=', 'ticketit.status_id')
            ->join('ticketit_priorities', 'ticketit_priorities.id', '=', 'ticketit.priority_id')
            ->join('ticketit_categories', 'ticketit_categories.id', '=', 'ticketit.category_id')
            ->select([
                'ticketit.id',
                'ticketit.subject AS subject',
                'ticketit_statuses.name AS status',
                'ticketit_statuses.color AS color_status',
                'ticketit_priorities.color AS color_priority',
                'ticketit_categories.color AS color_category',
                'ticketit.id AS agent',
                'ticketit.updated_at AS updated_at',
                'ticketit_priorities.name AS priority',
                'users.username AS owner',
                'ticketit.agent_id',
                'ticketit_categories.name AS category',
            ]);

        $collection = $datatables->of($collection);

        $this->renderTicketTable($collection);

        $collection->editColumn('updated_at', '{!! \Carbon\Carbon::createFromFormat("Y-m-d H:i:s", $updated_at)->diffForHumans() !!}');

        return $collection->make(true);
    }
```

Where do I need to make this change for the datatable to work properly?

**Comment by jryd** [comment]
I believe I have narrowed this down to `src/Views/index.blade.php` in which the datatable itself was looking for `users.name`. I have updated this in my fork, however the change isn't being reflected in my views. I've tried a hard refresh and clearing the cache, am I on the right track here?

**Comment by thekordy** [comment]
`php artisan view:clear` ?

**Comment by jryd** [comment]
I literally just stumbled across this and was coming back to share it.
It looks like the views get cached in `resources/views/vendor` does the `php artisan view:clear` flush that folder or not?

**Comment by thekordy** [comment]
Yes, I think it does

**Comment by jryd** [comment]
Great. My shift to using `username` rather than `name` has now been completely successful. Thanks for your help along the way!
