### ISSUE TITLE
Summernote editor modal has no padding inside the edit modal

### ISSUE THREAD

**Issue by jryd** [thekordy/ticketit#230]
When you are editing a ticket, you have the option to edit the description of the ticket.

This uses the summernote editor and so you can add links, images, videos etc, and by clicking on this another modal window pops up inside the current on to add the content - however this second window has now padding and so inputs span the whole modal.

Is it possible to add some padding so that they look a little better inside the edit modal?

![screen shot 2016-07-22 at 10 00 37 am](https://cloud.githubusercontent.com/assets/13251203/17004588/bc6baf5e-4f29-11e6-9498-c0cfb823253e.png)

![screen shot 2016-07-22 at 10 00 53 am](https://cloud.githubusercontent.com/assets/13251203/17004589/bc6c2a88-4f29-11e6-9782-52947e38533b.png)

**Comment by jryd** [comment]
I changed the `.modal-body` padding to 30px which gave the appropriate spacing on the sides.

**Comment by kjdion84** [comment]
```
.note-editor .modal-body {
	padding: 15px 30px;
}
```
This will keep it consistent with regular bootstrap modals.
