### ISSUE TITLE
null pointer error in the Agent model

### ISSUE THREAD

**Issue by nCrazed** [thekordy/ticketit#232]
[This line](https://github.com/thekordy/ticketit/blob/0.2/src/Models/Agent.php#L147) doesn't account for the possibility of the ticket not existing causing something like this to be executed:

``` php
null->user->id
```

Since the `isTicketOwner` is called by routes implemented in this package, it is the responsibility of the package to guard against a potentially malformed request that match the routes.

A simple solution would be to replace the `find()` call with `findOrFail()`, this would make it so that a bad request will throw a `ModelNotFound` instead of the current `ErrorException` allowing it to be automatically handled by the application's normal 404 handler.

**Comment by nCrazed** [comment]
Additionally, it's possible that a ticket would not have a valid user associated with it because there's no foreign key constraint from `ticketit.user_id` to `users` table.

**Comment by balping** [comment]
Thanks for reporting this. Would you also create a pull request that fixes this?

**Comment by nCrazed** [comment]
Sure

**Comment by nCrazed** [comment]
Went on holiday and forgot all about this. 

@thekordy has this been resolved or would a PR still be useful?

**Comment by thekordy** [comment]
Not resolved yet, a PR would be very appreciated.
