### ISSUE TITLE
add some logic before users use ticketit

### ISSUE THREAD

**Issue by yizhihou2** [thekordy/ticketit#234]
Hi,

I'd like to add some logic before users actually use ticketit. For example, when a user clicks the link to go to ticketit, I would like to check the user' information and to make sure he/she has filled some extra information like company name, phone number, etc. If these information is missing, I'd like to redirect the user to profile page to complete these information.

Is it possbile for me to override TicketsController.php to add such logic? Or is there some better way to do it? 

Thanks!

**Comment by thekordy** [comment]
in any service provide (such as `app/providers/AppServiceProvider.php`) you can hook into the ticketit `creating` event and do the logic before the ticket is actually created. [See Laravel Documents](https://laravel.com/docs/5.1/eloquent#events) and you can see it is being used in [TicketitServiceProvider](https://github.com/thekordy/ticketit/blob/0.2/src/TicketitServiceProvider.php#L146) for notifications firing upon specific events like ticket update or create.
