### ISSUE TITLE
How add new localization?

### ISSUE THREAD

**Issue by small-tommy** [thekordy/ticketit#236]
Hi, thank you for ticketit!

I want add localization (ru). How I can add it, to not change "vendor" directory?

**Comment by balping** [comment]
Hi @small-tommy,

According the [laravel documentation](https://laravel.com/docs/master/localization#overriding-package-language-files), you can add your lang files under `resources/lang/vendor/ticketit/ru`

If you translate the whole app, we would appreciate a pull request for adding Russian translation.

**Comment by small-tommy** [comment]
@balping thank you. I do it)
