### ISSUE TITLE
Please Provide a default master view for test 

### ISSUE THREAD

**Issue by pierre-guillot** [thekordy/ticketit#239]
Hello
Ticketit is awesome, but very complicate to instal if you are new with Laravel.
Can you provide a master.blade.php example? Like the same uses for ticketit demo?

**Comment by balping** [comment]
I think this page is clear enough: https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template

All you have to do is to concat those code snippets

**Comment by balping** [comment]
Plus if you run `php artisan make:auth` it generates a nice master layout example, you can insert the above snippets into it quite easily.

I guess the demo was done by running this command too.
