### ISSUE TITLE
Use of modal-body or other modal divs by TicketIt

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#240]
Are you using modal-body in a fairly wide ranging way? I have a modal on the same page as my TicketIt and it is for something else. However TicketIt populates it with its own data (it repeats the Ticketit page inside my modal).

**Comment by thekordy** [comment]
Yes, we [use modal](https://github.com/thekordy/ticketit/search?utf8=%E2%9C%93&q=modal) for ticket edit form and delete confirmation at `tickets/show.blade.php`. 

Make sure you give an `id` to your modal and use it in `data-target` for the button that opens the model. Or you already did that?

**Comment by sunnyjayjay** [comment]
Yes, my modal has an id and it uses data-target as you say. However, the content of my modal body is overwritten by yours.

**Comment by thekordy** [comment]
This is the[ javascript that fills the delete confirmation](https://github.com/thekordy/ticketit/blob/e3573aec22c082860082c6faca9ad8e6287af3c6/src/Views/tickets/show.blade.php#L29) model with its data, try to delete it and see if the problem is gone.

**Comment by sunnyjayjay** [comment]
No, that is in the "Show" view - my problem is in the "Index" view.

**Comment by sunnyjayjay** [comment]
I get the entire Index view repeated in my modal window, instead of my own content. It is the modal-body that is being overwritten by yours. The id of my modal is "account" which as far as I can see is not the same as yours.

**Comment by balping** [comment]
Try to change your id then.
