### ISSUE TITLE
Status changed email - even when status is the same

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#242]
Emails are being sent out saying xx changed the status of "Support Ticket" from In progress to In progress.  What actually happened was that the support desk made a comment.

**Comment by sunnyjayjay** [comment]
Hi again. Can you respond please? Also I would really like to know how to customize these emails. Your templates are full of proprietary code. How can I make my own emails for this please?

**Comment by thekordy** [comment]
I already answered this in your previous issue #249 .. just make another service provider and copy `TicketitServiceProvider` logic to your new service provider, modify any logic you want, remove the `TicketitServiceProvider` from `config/app.php`.

For the email events, we are using hooks to the [eloquent model events](https://laravel.com/docs/master/eloquent#events), you can modify that to send the desired email at desired events with the desired information and template as you wish.
