### ISSUE TITLE
Questions for customization

### ISSUE THREAD

**Issue by WestFR** [thekordy/ticketit#244]
Hello, i'm French developer !

I have more questions for customize TicketIt.

Primary, how to translate or reach texts in English ? 
Because i need French language ! 

Secondary, how to differentiate one users and one users admin in TicketIt ?
I used Auth::user() but I need to differentitate this two users for redirect in home page.

![sans titre](https://cloud.githubusercontent.com/assets/21226632/17943805/3c7597cc-6a3d-11e6-9778-b1d110491826.jpg)

Finally, how to delete cleanly pages and access to path "password/reset,..." ?
And, how to make accessible the page " register " only in admin user ?

Thank you for the help ! 
And I apologize for my French !

**Comment by balping** [comment]
Cher @WestFR ,

Je réponds en français, parce que ça peut être plus facile pour toi (mais pas pour moi...)

Tes questions ont rapport à Laravel en général en premier lieu. Tu peux traduire Ticketit [de cette façon](https://laravel.com/docs/5.3/localization#overriding-package-language-files).  Fichiers anglais sont ici: https://github.com/thekordy/ticketit/tree/0.2/src/Translations/en 

Je ne comprends pas ton deuxième question, désolé. Tu pourrais  la reformulez en français.

C'est un guide pour désactiver _password resets_ et _registration_: http://robboyland.com/laravel-auth-how-to-disable-registration

Et pour _admin-only registration_ tu a besoin d'un _controller_ avec `Kordy\Ticketit\Middleware\IsAgentMiddleware` _middleware_. Dans ce _controller_ tu dois écrir propre code pour créer nouveaux utilisateurs. Comme ici: https://laravel.com/docs/5.2/quickstart#adding-tasks

**Comment by WestFR** [comment]
Thanks you @balping for you help ! 

So, i have translate this correctly in French !
But, for the fields "updated at" are in English. I have configure my field timezone in app.php "Europe/Paris".
It's a error or cache error ?

![sans titre](https://cloud.githubusercontent.com/assets/21226632/17952219/adf787d6-6a68-11e6-985a-ce2303a464ad.jpg)

Furthermore, I have "delete" "register " and " password / reset " page.

But how to make accessible these pages only in administrator of TicketIT ?

Finally, i have use IsAgentMiddleware with the same Controller for differentiate users and admin users.
I would like that the user arrives on a page with a different view but i doesn't work!

See my code...

![sans titre2](https://cloud.githubusercontent.com/assets/21226632/17952453/f7c43dc6-6a6a-11e6-8502-51cdde9e3c9a.jpg)

Thanks you very much !!

**Comment by balping** [comment]
Hi @WestFR,

Ticketit uses [this package](https://github.com/jenssegers/date) for displaying dates.

You'll have to [set the default locale](https://github.com/jenssegers/date#usage) to `fr`:

``` php
use Jenssegers\Date\Date;

Date::setLocale('fr');
```

A good place for this is the `app/Providers/AppServiceProvider.php` file's boot method.

---

In your routes file you have to wrap those  routes that you want to be accessible only to admins in this route group:

``` php
Route::group(['middleware' => \Kordy\Ticketit\Middleware\IsAgentMiddleware::class], function () {
    Route::get('whatever');
    ...
});
```

But your own `is-admin` middleware is also fine!

---

Now I think I understand what you want.

In your index method you could do a simple if-else statement:

``` php

if(Auth::user()->is_admin){
    return $this->indexAdmin();
}else{
    return view('home');
}
```

Hope this helps

**Comment by WestFR** [comment]
Hello @balping !

Thanks you for you help !
I managed to make what I wanted for the administrators and the users !

But, I have more questions for my customization !

1 -  We can override header.blade.php (view/shared/) ? Because if I updates TicketIt, I would lose the information not override.

2 - For displaying dates in French, I have more problems. I don't see what's doesn't work.
I try with this code "use Jenssegers\Date\Date;  Date::setLocale('fr');" in app/Providers/AppServiceProvider.php but it's doesn't work.

This is my code (app.php). If you have an explanation

![sans titre](https://cloud.githubusercontent.com/assets/21226632/18037638/8b33f9ea-6d89-11e6-920a-533b364846e1.jpg)

3 - I have created users panel (see picture). But I don't understand the functioning of the delete form.
How to use the form for the destroy method on the controller UserController ?

![sans titre](https://cloud.githubusercontent.com/assets/21226632/18037690/a0439d4e-6d8a-11e6-9848-00045ec70076.jpg)

Thanks you very much for you help !

To finish, it's possible to committed my version of TicketIt to make her accessible.
If yes, what limitations?

**Comment by balping** [comment]
1. You can override tviews without changing vendor code. Ex. `resources/views/vendor/ticketit/shared/nav.blade.php` will override `vendor/kordy/ticketit/src/Views/shared/nav.blade.php` If you do it this way, you don't have to worry about updates, your changes won't be lost. However you might want check if something changed  in the original file after an update. If so, it's possible that you have to modify your override file manually. See docs: https://laravel.com/docs/5.3/packages#views
2. Sorry, my previous comment was misleading. It should work by just setting locale in `config/app.php` See the source: https://github.com/jenssegers/date/blob/master/src/DateServiceProvider.php#L21
3. What you call in seeUser.blade.php is not your user controller, but ticketit's agentcontroller. To call your own controller set the form action to `action('UserController@destroy')`

**Comment by balping** [comment]
2. Sorry, my previous comment was misleading. It should work by just setting locale in `config/app.php` See the source: https://github.com/jenssegers/date/blob/master/src/DateServiceProvider.php#L21

**Comment by WestFR** [comment]
Hello and thanks you so much ! 

For the questions 1 and 3, it's work perfectly ! :)

For question 2, I have the same configuration and DateServiceProvider.php but it's doesn't work.
It's not critical !

My app.php
'timezone' => 'Europe/Paris',
'locale' => 'fr',
'fallback_locale' => 'en',

And, do you need my version of TicketIt ?

Thanks you for all !

**Comment by thekordy** [comment]
@WestFR you don't need this line:

``` php
// config/app.php
Jenssegers\Date\DateServiceProvider::class,
```

this is already done by [ticketit](https://github.com/thekordy/ticketit/blob/0.2/src/TicketitServiceProvider.php#L238)

Show us how do you implement date in your view, or make sure you show date like this:

``` blade
{!! Date::createFromFormat("Y-m-d H:i:s", $ticket->updated_at)->diffForHumans() !!}
```

Also you can try something like this in a test route or the tinker to make sure the date package is set correctly:

``` php
echo Date::parse('-1 day')->diffForHumans();
```
