### ISSUE TITLE
How do you feel about DataTables?

### ISSUE THREAD

**Issue by FusionDesign** [thekordy/ticketit#25]
I'm brilliant with Datatables (http://pos.demo.fusiondesign.me). Would you like me to bundle this which will provide Search/Sort and more?

**Comment by thekordy** [comment]
Yes, please ... I like it :)

**Comment by MACscr** [comment]
Just make sure its light and bootstrap friendly. Some solutions get way to heavy and bloated.

**Comment by thekordy** [comment]
> Just make sure its light and bootstrap friendly. Some solutions get way to heavy and bloated.

:+1:

**Comment by FusionDesign** [comment]
I totally agree. My DataTables are pretty epic when implemented properly.

**Comment by FusionDesign** [comment]
I finished this a bit early. Once I'm on something, it's hard to get me off lol
