### ISSUE TITLE
new field: "Completed by"

### ISSUE THREAD

**Issue by Jagy2014** [thekordy/ticketit#254]
User and Agent can close the ticket. Could you add "Completed by" to identify who closed it?

P.S: In database there is field "completed_at", it is visible only in database? If yes, please add to completed ticket details.

**Comment by thekordy** [comment]
Great idea, I will look into this for v2, but for v0.2 we only releasing bug fixes patches so we can focus on releasing v2. Can I encourage you to take a look at this [Laravel auditing package](https://github.com/owen-it/laravel-auditing)? I am using it in other projects and I find it very useful.
