### ISSUE TITLE
Email not working on Sparkpost

### ISSUE THREAD

**Issue by pistachioplease** [thekordy/ticketit#255]
![9a6ad22f65f4867e200d56aa7e06d73a](https://cloud.githubusercontent.com/assets/2632383/18589244/56a6b604-7c5c-11e6-9fdb-774581bb94d4.png)

I'm having trouble sending email using sparkpost. My test email route works fine and also other user emails, but the ticketit emails are not working.

**Comment by thekordy** [comment]
Have you configured the `from` setting in `config/mail.php`?

**Comment by pistachioplease** [comment]
Hi. I've configured the from setting 2 days ago. I solved it. Thanks for the reply.  Mail sending works fine now.
