### ISSUE TITLE
Duplicate user queries

### ISSUE THREAD

**Issue by zek** [thekordy/ticketit#256]
https://github.com/thekordy/ticketit/blob/0.2/src/TicketitServiceProvider.php#L38

This composer('*') line causes so many duplicate user query for each view.

select \* from `users` where `users`.`id` = '1' limit 1
select \* from `users` where `users`.`id` = '1' limit 1
select \* from `users` where `users`.`id` = '1' limit 1

**Comment by balping** [comment]
Could be replaced with view()->share() perhaps

**Comment by zek** [comment]
It's solved right now. No more queries :) I hope you commit it soon.

It does not create any bugs right?

**Comment by zek** [comment]
Yes it does as I'm afraid :(

Undefined variable: u (View: /Users/zack/Sites/site/resources/views/vendor/ticketit/shared/nav.blade.php) (View: /Users/zack/Sites/site/resources/views/vendor/ticketit/shared/nav.blade.php) (View: /Users/zack/Sites/site/resources/views/vendor/ticketit/shared/nav.blade.php)

**Comment by sunnyjayjay** [comment]
This query runs even when a view includes a partial. One of my views uses about 12 partials and this query runs for each one. This is not even a view that references TicketIt so why is it running?

**Comment by sunnyjayjay** [comment]
THIS IS A SUGGESTION FOR YOU. If in the TicketItServiceProvider you change the view composer creation to be limited to the TicketIt views you reduce the query count by 20 to 30 on other pages. At Line 38:

```
view()->composer('ticket*', function ($view) {
```

**Comment by thekordy** [comment]
@sunnyjayjay thanks, I try that

**Comment by rebootcode** [comment]
@thekordy  Reason for being rude at #361 was because of this issue #256 

It's been now more than 6 month and still running horrible number of queries was panic for web-app running this package.

Also, the reason to brag about wrong was because you have good number of stars and fork which becomes important for people to know the issue in the package.
