### ISSUE TITLE
On Install: array_diff_key(): Argument #2 is not an array

### ISSUE THREAD

**Issue by lrpasquetto** [thekordy/ticketit#257]
**Info:**

```
Laravel 5.3
PHP 7.0.10
```

**On finish composer required / update:**

```
ErrorException in InstallController.php line 247: 
array_diff_key(): Argument #2 is not an array
```

Can someone help me? Thanks!

**Comment by balping** [comment]
Does this solve your problem? https://github.com/thekordy/ticketit/pull/251

**Comment by lrpasquetto** [comment]
Very good! Thank you, it worked.
