### ISSUE TITLE
Nothing to publish for tag [].

### ISSUE THREAD

**Issue by lrpasquetto** [thekordy/ticketit#258]
Info:

```
Laravel 5.3
PHP 7.0.10
Composer: "kordy/ticketit": "0.2"
```

Error: When installed, to run **vendor:publish**, nothing happens.

```
MacBook-Pro-de-Lucas:Blitgestor lucasrpasquetto$ php artisan vendor:publish --provider="kordy\ticketit\src\TicketitServiceProvider"
Nothing to publish for tag []
```

I do not run, do not have the installation routes, does not publish the views, controllers.

**Comment by thekordy** [comment]
the provider is `Kordy\Ticketit\TicketitServiceProvider` not `kordy\ticketit\src\TicketitServiceProvider`
