### ISSUE TITLE
Ticket language

### ISSUE THREAD

**Issue by gps010** [thekordy/ticketit#259]
How to add language ?!

**Comment by balping** [comment]
https://laravel.com/docs/5.3/localization#overriding-package-language-files

**Comment by gps010** [comment]
Thx ^^

**Comment by gps010** [comment]
En fait y'en à pas kelkun ki parl français jvoulé demandé qqch

**Comment by gps010** [comment]
J'ai généré automatiquement le contrôleur d'authentification ainsi que ses view donc par la suite je me trouve avec un fichier app.blade.php qui contient tte mes vue et ça m'a fait une confusion avec master.blade.php exactement lorsque j'ajoute le nav bar ... Alors peux tu m'envoyer votre dossier "app" ?!

**Comment by balping** [comment]
You can find a working example app directory here: https://github.com/balping/ticketit-app
