### ISSUE TITLE
No routes? [boilerplate compatibility]

### ISSUE THREAD

**Issue by MACscr** [thekordy/ticketit#26]
Im trying to integrate your great ticket system into an existing app I am working on and I do not see any route information. Am I missing something?

**Comment by MACscr** [comment]
Ah, I guess its in the config/ticketit.php file. Hmm. Your package seems to have a completely different file layout than what im using with the https://github.com/rappasoft/laravel-5-boilerplate solution. They are both made for laravel 5.1 and it seems to meet all your minimum requirements. Any suggestions on how to get your system to work with it?

**Comment by MACscr** [comment]
Let me expand a bit more. Right now with zero config changes, when I go to /tickets, im getting:

``FatalErrorException in Agent.php line 9:
Class 'App\User' not found``

which I am pretty sure is a result of this different file structure.

**Comment by MACscr** [comment]
More info and I apologize if this is to much, but my config/auth.php has the following model set:

``'model' => 'App\Models\Access\User\User',``

**Comment by fishmad** [comment]
You need to follow the laravel instructions for enabling the auth system its installed by default but not enabled. You need to open your app\http\routes.php file and add the auth routes to initiate the functionality.
```
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');
```
[Activate Laravel 5.1 Authentication!]http://laravel.com/docs/5.1/authentication#authentication-quickstart

**Comment by MACscr** [comment]
I do not have a User.php in the app folder and I already have a working auth system as I mentioned. My app folder pretty much looks like so: https://github.com/rappasoft/laravel-5-boilerplate/tree/master/app

**Comment by FusionDesign** [comment]
MACscr - Does replacing App\User with App\Models\User\User fix the issue? If so I can probably fix that.

**Comment by FusionDesign** [comment]
IIRC - App\User is hard-coded right now and we can use app()->make(config('ticketit.model')); to fix.

**Comment by FusionDesign** [comment]
ticketit.model is not implemented to my knowledge in config, but it should be an easy update. I'll submit something after my current PR is pulled. I'm not smart enough for branches.

**Comment by MACscr** [comment]
Yes, changing that path in the Agent.php seems to solve that particular error. I will open a new ticket for the next error that came up after I troubleshoot it a bit. Thanks for the help!

**Comment by FusionDesign** [comment]
You're welcome. I knew that may come up.

**Comment by MACscr** [comment]
Had to update src/Models/Comment.php and src/Models/Ticket.php with the correct user path too.

**Comment by thekordy** [comment]
Please be aware that all changes you do are backed up, as any new version update will replace them.

While Ticketit integrates by default with Laravel default Auth and User system, but we may add in future somehow a compatibility to boilerplate. I guess It won't be that hard

**Comment by FusionDesign** [comment]
I tried turning Agent into a trait but it is far too much work. I didn't realize how much touched the Agent class. I gave up after I couldn't even get an error log to be produced.
 
This will have to be for way later, Kordy was right.

**Comment by FusionDesign** [comment]
I'd rather have a Wiki article on this subject, since you only have to change App\User in a few spots it would be easy to document.
