### ISSUE TITLE
how i can customize routes ?!!

### ISSUE THREAD

**Issue by gps010** [thekordy/ticketit#261]

**Comment by thekordy** [comment]
Make a custom service provider that includes the custom routes as described here https://github.com/thekordy/ticketit/issues/249#issuecomment-244314305

**Comment by thekordy** [comment]
![ticketit routes setting](https://cloud.githubusercontent.com/assets/11343048/19702808/e4597830-9b09-11e6-9290-5ca95d6f8d1f.png)
