### ISSUE TITLE
Auth::user()->tickets_role and Auth::user()->is_admin not working !!

### ISSUE THREAD

**Issue by gps010** [thekordy/ticketit#262]

**Comment by balping** [comment]
Could you provide more details please?

**Comment by gps010** [comment]
en fait je voulais vérifier est ce que l'utilisateur courant est il un administrateur ou bien non afin que je puisse modifier l'affichage de menu du nav bar selon leurs privilège

**Comment by gps010** [comment]
@if(Auth::user()->is_admin)

```
                <li><a href="{{ url('/tickets-admin') }}">Dashboard</a></li>
            @endif
```

**Comment by balping** [comment]
The `isAdmin` function works only on `Kordy\Ticketit\Models\Agent`.
