### ISSUE TITLE
[Question] Integration within existing site

### ISSUE THREAD

**Issue by jeremynikolic** [thekordy/ticketit#263]
I've got a management website recently launched and it's already getting hard to keep tracks of issues/user question and so on.

As your package looks like all I need, I am wondering if setting it up alongside my site would be easily done, any suggestions or warnings ?

Thanks

**Comment by thekordy** [comment]
Yes, it should integrate well if you already have pre-requirements set. Just try it first on a test environment.

**Comment by jeremynikolic** [comment]
I'll give it a try and let you know if all went well

**Comment by BartHuis** [comment]
as you can see in: https://github.com/thekordy/ticketit/issues/264 @astroop can't get it working in 5.3... what's your experience?

**Comment by jeremynikolic** [comment]
I didnt have time to try it yet but will keep you informed

**Comment by thekordy** [comment]
I can confirm it is working with last Laravel 5.3.19
