### ISSUE TITLE
question: 5.3 support?

### ISSUE THREAD

**Issue by BartHuis** [thekordy/ticketit#264]
hi, is this package supporting 5.3? its not in the requirements list of the readme?

**Comment by astroop** [comment]
I tried in a new project...and no this package is not supporting 5.3 :(

**Comment by balping** [comment]
It does. Use the newest 0.3.1 version.

**Comment by BartHuis** [comment]
@Astroop can you confirm this?

**Comment by thekordy** [comment]
I can confirm it is working with last Laravel 5.3.19
