### ISSUE TITLE
form request validation error in Laravel 5.3

### ISSUE THREAD

**Issue by astroop** [thekordy/ticketit#265]
Ok so the package is compatible with laravel 5.3 but i cant' understand why it doesn't works, when i try to reach the route /tickets-install it says the page i am looking for doesn't exist. Probably its because i missed something but anyone to explain how to setup Ticketit for 5.3 ??

Sorry for my bad level in english and thank you in advance

**Comment by balping** [comment]
Have you registered the ticketit service provider in your config/app.php fil?

**Comment by astroop** [comment]
Yup ! Installation with composer + 'php artisan make:auth' for the users

**Comment by Sennik** [comment]
Same problem here with Laravel 5.2. Kordy\Ticketit\TicketitServiceProvider::class, is in de App providers section.

**Comment by thekordy** [comment]
Could you please take a look at #74  #73

**Comment by astroop** [comment]
Ok so, in a new project with the laravel make:auth i created a user (/register),
After, I installed kordy/ticketit with composer.
I created my master view, and connected my account before accessing tickets-install.
Finally it works (you really need to be connected before accessing the route)  ! 
now i cannot post a ticket without this error :p 

"FatalErrorException in PrepareTicketStoreRequest.php line 7:
Class 'App\Http\Requests\Request' not found"

**Comment by thekordy** [comment]
mmm .. seems that in Laravel 5.3 they have changed to `Illuminate\Foundation\Http\FormRequest` instead of `App\Http\Requests\Request`, I do not know if this is the only change in form request validation, so I will wait until I get to home tonight to work on it.
