### ISSUE TITLE
Ticketit in Laravel 5.1, the pluck method threw error

### ISSUE THREAD

**Issue by zekylaf** [thekordy/ticketit#266]
Hi, I have installed Ticketit in an existing site. The site works with https, but all Ticketit routes only works with http.

Is there anyway to config Ticketit to work with https?

Thanks!

**Comment by thekordy** [comment]
It should work without any need for special configuration for Ticketit.

**Comment by zekylaf** [comment]
Ok, I'll try to solve it. One more thing before close the issue. When I was trying to install Ticketit in Laravel 5.1, the pluck method threw error, so, I change all "pluck" to "lists" and problem solved.

Thanks for answer!

**Comment by thekordy** [comment]
Thank you for your feedback, I will look into that.

**Comment by zekylaf** [comment]
Hi again, I was looking for a translation to spanish but I couldn't found it, so, I translated all the files excepting setting.php within the translations' folder. I don't know how to update this on github, so I'll paste all here:

admin.php: http://pastebin.com/JamdaW9K

install.php: http://pastebin.com/LqMarXWe

lang.php: http://pastebin.com/MLzdqkTV

email > assigned.php: http://pastebin.com/k7VYmw6L

email > comment.php: http://pastebin.com/XqXNeNMR

email > globals.php: http://pastebin.com/rXuzKaK1

email > status.php: http://pastebin.com/M1Ph43Qt

email > transfer.php: http://pastebin.com/uUnxgUaR

**Comment by thekordy** [comment]
I'd love to add them, but if I were you, I'd try first to add them as a pull request, here's how: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

Your contributions in any way are greatly appreciated, thank you.

**Comment by zekylaf** [comment]
Ok, I ran out of excuses. I'm going to do it ;)

**Comment by thekordy** [comment]
Yes, do it :+1:  :)
