### ISSUE TITLE
Ability to Disable Priorities and Categories, etc

### ISSUE THREAD

**Issue by MACscr** [thekordy/ticketit#27]
I know I can just create a single priority and category and then just hide them with css, but why not give the option in the config to disable such features if they aren't needed? Its a feature request of course and I really appreciate what you have done so far. Thanks!

**Comment by FusionDesign** [comment]
That's pretty easy to do but I'm not sure how many assets I'd have to touch, as I'm fairly new to the project. I'll see about this one too.

After I finish Stripe integration with my site, I'll look up some Github quick start vids somewhere. I know Git, I just am not familiar with Milestones, Tags, Labels, Assignee, Statuses, etc. Once I feel comfortable, I'll pump out the features.
