### ISSUE TITLE
Trying to get property of non-object 

### ISSUE THREAD

**Issue by twoheadedmona** [thekordy/ticketit#274]
Hello, I am using your plugin without an email setup, and I followed your insight on [this similar issue](https://github.com/thekordy/ticketit/issues/113), however I still encounter the following error: 

`Trying to get property of non-object (View: PhpstormProjects/project/resources/views/vendor/ticketit/emails/assigned.blade.php)
`

I like this plugin, I think it's very useful, but I'm stuck on this problem for 2 days now. Is there no way to make it work without the email setup? Please help :)

**Comment by thekordy** [comment]
Hi, try to make sure you all notifications are disabled in the settings > configuration panel, and make sure to create at least a status, priority, category, and assign agent to the category .. all that before you start creating tickets.

Also you might need to try a fresh installation with new database if the problem still there after you have done the above. a fresh installation, disable notifications, create a status and priority and category with agent.

**Comment by twoheadedmona** [comment]
Thank you for your fast reply, turns out, I had cache that was causing problems. Now after I have created all these tickets, none of them show up in the list. Can you please tell me if I am missing some setting? Or if there's something else I should do?

**Comment by thekordy** [comment]
make sure you include JQuery in your master view and you have `@yield{'footer')` after it https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template

**Comment by twoheadedmona** [comment]
Thank you so much. That solved my issue :)

**Comment by thekordy** [comment]
You are welcome :)
