### ISSUE TITLE
Error ReflectionException

### ISSUE THREAD

**Issue by vanool** [thekordy/ticketit#275]
I get the following error when I go to my view in laravel. This happend after I installed ticketit version 2.1.x-dev

Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist' in D:\wamp64\www\ticketsysteem\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 734
( ! ) ReflectionException: Class log does not exist in D:\wamp64\www\ticketsysteem\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 734

**Comment by thekordy** [comment]
please use 0.2
