### ISSUE TITLE
Does not find admin session

### ISSUE THREAD

**Issue by bahman2216** [thekordy/ticketit#276]
I have installed and integrated successfully with my current laravel user tables.
But first time everything is ok. When I logout and login again as admin, It does not route to /tickets successfully and show me login page again. it returns me 
`$this->agant->isAdmin() --> null`

But I logged in as admin user that defined column ticketit_admin = 1 in my user table.

**Comment by thekordy** [comment]
which versions?

**Comment by bahman2216** [comment]
I installed from composer. It is v0.3.0

**Comment by bahman2216** [comment]
I think it is related to these lines:

`
public static function authMiddleware()
    {
        if (static::min('5.2') && app(Router::class)->resolveMiddlewareClassName('web') != 'web') {
            return ['web', 'auth'];
        }

        return ['auth'];
    }
`

I have extra middleware with name: auth:admin.web

Does it possible to add it in my route?

**Comment by balping** [comment]
If it's still an issue, reopen. That part has changed with 5.4 again.
