### ISSUE TITLE
User table user_name problem

### ISSUE THREAD

**Issue by vastolord** [thekordy/ticketit#277]
Hi i have changed all the name like this[https://github.com/thekordy/ticketit/search?p=2&q=-%3Ename&utf8=%E2%9C%93](url) . but now i am getting this eror.db is working fine it updates but problem is shown in the pic datatable is not working :) ... TIA
![name](https://cloud.githubusercontent.com/assets/13767732/20531532/4555cc80-b101-11e6-84cf-966cd23449ba.PNG)

**Comment by thekordy** [comment]
what about accessors https://laravel.com/docs/5.2/eloquent-mutators#accessors-and-mutators

**Comment by vastolord** [comment]
i have managed changing the data table too tnx for the help though tnx man
:)

**Comment by vastolord** [comment]
Bro i Have installed your ticket it on shared hosting.it worked fine but
suddenly it shows a error and whole site is
down.nclude(C:\wamp\www\basket\vendor/kordy/ticketit/src/routes.php):
failed to open stream: No such file or directory
it takes somehow the localhost route into live server.Any solution ?

**Comment by vastolord** [comment]
P.S i didnt change anything it suddenly shows.even without changing any
files on the server at all ;)
