### ISSUE TITLE
AdminLTE integration

### ISSUE THREAD

**Issue by MACscr** [thekordy/ticketit#28]
This is a question and a feature request (maybe), but as you have seen in one of my other issues that I created, but I am using a great laravel/bootstrap boilerplate (https://github.com/rappasoft/laravel-5-boilerplate/) that uses the AdminLTE theme for its backend area. Since you only have a single master_template setting in the config/ticketit.php, is this even possible with the tickets package?

**Comment by MACscr** [comment]
Well I got it partly working by manually editing the admin template files $master setting to a static value of:

``@extends('backend.layouts.master')``

and then changing the admin_route in config/ticketit.php:

``'admin_route' => 'admin/tickets',``

and now it will show the ticket admin index, but when I go to a link, i get:

``ErrorException in UrlGenerator.php line 278:
Route [admin/tickets.status.create] not defined. (View: /var/www/html/laravel-5-boilerplate/resources/views/vendor/ticketit/admin/status/index.blade.php)``

and

``InvalidArgumentException in UrlGenerator.php line 278:
Route [admin/tickets.status.create] not defined.``

Guess I have to figure a way around that. hmm.

**Comment by FusionDesign** [comment]
Set admin_route to "admin" and main_route to "tickets" right?

**Comment by MACscr** [comment]
Nope, I don't think they compound like that. Unfortunately then I only get 404's for any of the ticket admin area.

**Comment by FusionDesign** [comment]
Easy enough. Change admin_route to dashboard. Now make a blank view for dashboard and you can list users tickets, stats, etc there.

**Comment by FusionDesign** [comment]
I'm taking a stab in the dark and guessing that the Boilerplate reserves /admin/*/* and so does Ticketit based on your config.

**Comment by MACscr** [comment]
but admin/tickets worked fine (I think). Just not any of the sub pages.

**Comment by FusionDesign** [comment]
Trust me. Just set it to Dashboard or something except admin. Then navigate to /dashboard/priority in url. I'd try a suggestion before saying "but" lol :D

**Comment by MACscr** [comment]
ok, so dashboard is my index for my user area already and I am really wanting to integrate the admin area of the ticket system into the actual admin area of the app.

**Comment by MACscr** [comment]
Sorry, will try something else. missed that point

**Comment by FusionDesign** [comment]
You wanted to make it work, I got it to work :)

Until we get some code updates, I'd suggest redirect()->route('admin.index'); for now.

**Comment by FusionDesign** [comment]
You know the reason you publish views is so you can tweak them :) -- You never actually have to link to the admin route anywhere, ever if you adjust the view html

**Comment by MACscr** [comment]
Actually just keeping it at the default of ticket-admin worked. Adjusting the master path in the templates as I mentioned earlier kept the admin view. Thanks!

**Comment by FusionDesign** [comment]
Good to know!

**Comment by MACscr** [comment]
Yep. My admin url might not be as pretty as I would have liked, but this works well enough. Woo hoo!
