### ISSUE TITLE
error when trying to serve: php artisan serve

### ISSUE THREAD

**Issue by LeoImmanuelj** [thekordy/ticketit#280]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to a member function prepare() on null

**Comment by LeoImmanuelj** [comment]
when i add 
        Kordy\Ticketit\TicketitServiceProvider::class
in app/config

the above error occurs

**Comment by LeoImmanuelj** [comment]
and i'm using mongodb

**Comment by ghost** [comment]
Maybe this will help you? https://github.com/thekordy/ticketit/issues/281

**Comment by balping** [comment]
https://github.com/yajra/laravel-datatables#php-artisan-serve-bug
