### ISSUE TITLE
Make routes dynamic for any environment

### ISSUE THREAD

**Issue by ghost** [thekordy/ticketit#281]
We were having an issue with this running multiple dev servers on the same db server -- when it tries to pull "routes" setting from db, it crashed all dev servers.

**Solution:**
in _/vendor/ticketit/src/TicketitServiceProvier.php_

change line 191 **from:**
`            include Setting::grab('routes');`
**to:**
`            include(__DIR__.'/routes.php');`

**Comment by ujackson** [comment]
Had the same issue: changing  include Setting::grab('routes'); to include(__DIR__.'/routes.php'); fixed it.

**Comment by balping** [comment]
Thanks to both of you for making this note

**Comment by ghost** [comment]
By the way, I still have this issue. This fix still needs to be applied EVERY TIME for me. :(
