### ISSUE TITLE
ErrorException in TicketitServiceProvider.php line 191: include(vendor/kordy/ticketit/src/routes.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by vastolord** [thekordy/ticketit#282]
Getting this error on and on.Any Solution ?

ErrorException in TicketitServiceProvider.php line 191:
include(vendor/kordy/ticketit/src/routes.php): failed to open stream: No such file or directory

**Comment by sekhoanem** [comment]
Hi. Did you get a solution to this? Getting the same error

**Comment by mhanoglu** [comment]
@sekhoanem 

On installation current path stored in databse. When change laravel directory, system show this error.
**Solution:**
Go to phpMyAdmin
ticketit settings table name is: **ticketit_settings** and slug is **routes** edit **value** column for right path.

And settings caching for 60 minutes, if you don't wanna wait, you may delete **storage/framework/cache/data/** manually.

![image](https://cloud.githubusercontent.com/assets/8195419/26240282/1e89b760-3c89-11e7-9b38-9700eaf944bf.png)

**Comment by sekhoanem** [comment]
@marzochi 

Thanks
