### ISSUE TITLE
Help with installing Tickeit

### ISSUE THREAD

**Issue by NikhilDoWhile** [thekordy/ticketit#283]
Hey,

I am trying to install Ticketit on my laptop and run. 

I have installed laravel and run the command in Step 1.

I can't understand what to do after that. Can you please explain in simple steps how to run Ticketit after Step one. What files to edit and what to run.

I just want to run the website on my computer like how you ran it on your demo site.

**Comment by francoisjacquet** [comment]
:+1:

For those who are not familiarized with Laravel, some tutorial / installation steps from scratch would be great!

Some hints can be found at https://github.com/thekordy/ticketit/issues/74 and https://github.com/thekordy/ticketit/issues/73

**Comment by balping** [comment]
If still in doubt, reopen it. I think the instructions are clear enough.
