### ISSUE TITLE
Trying to get property for non-object

### ISSUE THREAD

**Issue by ghost** [thekordy/ticketit#287]
I have done a fresh install, added the package service provider, created categories, and priorities, but when I go to create a new ticket I get:

ErrorException in 8015760469edf18a1bf1e0f9243aaca7cf0fd81a.php line 22:
Trying to get property of non-object (View: C:\xampp\htdocs\btc\vendor\kordy\ticketit\src\Views\emails\assigned.blade.php)

I've checked the database and it's being inserted, any ideas?

**Comment by ghost** [comment]
Just to clarify, I have my email settings set up and still receiving that error. Only when I disable notifications it goes away, although it should send an email.

**Comment by sunnyjayjay** [comment]
I have a similar error

**Comment by balping** [comment]
I could not replicate this. Could you check the cached view file, which line is causing this? Could be any of these four:

```php
'name'      =>  $notification_owner->name,
'subject'   =>  $ticket->subject,
'status'    =>  $ticket->status->name,
'category'  =>  $ticket->category->name
```

**Comment by Dyceman** [comment]
I commented out line 68 (starts with $this->sendNotification($template.....)) of NotificationsController.php and I don't get that error anymore.

**Comment by mjducharme** [comment]
I get this error if there is no such status for the status id configured for newly created tickets - ex. if it is configured to make new tickets with status id 1 and there is no such status. Adding a status with ID 1 resolved the error.
