### ISSUE TITLE
ErrorException in Setting.php line 57: Trying to get property of non-object

### ISSUE THREAD

**Issue by leejiaye** [thekordy/ticketit#288]
Can you help me to check why I am getting this error?
include Setting::grab('routes');           //this trigger the grab method in Models/Setting and occur the error
Thank you

**Comment by sunnyjayjay** [comment]
I have the same error

**Comment by balping** [comment]
Try to clear the cache

artisan cache:clear

**Comment by balping** [comment]
Other idea: check your database, you should have a row in the settings table, with slug `routes`. If you don't have that add it. The value should be `/installation/path/vendor/kordy/ticketit/src/routes.php`

As you didn't use the installer, this might be missing. After adding that row, don't forget to clear the cache!
