### ISSUE TITLE
Specify classes or id's for elements

### ISSUE THREAD

**Issue by MACscr** [thekordy/ticketit#29]
Id like to hide many aspects of the ticket system since I have no use for their particular values and I would like to customize the look of many other areas. Unfortunately this means that in most cases, I have to customize the blade template files versus just doing it with css because a majority of the elements do not have custom classes or id's associated with them. Priorities, categories, person responsible for ticket, owner, last updated, etc. All of these are just in generic divs with no custom css assignment such as class="ticket-owner" or something like that. This isn't really a huge deal, but it would be nice to be able to customize style of the ticket system without having to modify files that might be updated later. Doing it in css only can make upgrades so much easier to do.

Just another feature request. Last one that I can think of. Sorry! =)

**Comment by thekordy** [comment]
You are very right :+1:

**Comment by fishmad** [comment]
Hardcoded CSS is building fast we need to agree on some naming conventions for TicketIT id and class tags and follow the pattern throughout, also need a custom stylesheet implemented.

**Comment by fusiondesign** [comment]
I don't know if most email clients support stylesheets. Every Open Source template I've ever seen has inline styles with comments like "" and stuff.

This was an open source template as well that I converted into a theme.

**Comment by fusiondesign** [comment]
Which is why database setting variable in a ticketit_email_templates database may be wise

**Comment by fusiondesign** [comment]
Then we can have multiple "themes" that use the same template

**Comment by fusiondesign** [comment]
That said, I totally agree on id's and classes throughout the normal app.

**Comment by fishmad** [comment]
Agree, emails should have embedded styles - linked stylesheets in emails break to often and probably end up in clients spam folders.

Are we going to just wing-it with class names or follow the existing TitcketIT folder structure?

should we wrap each View file within its own custom div and ID or do integrate into existing the bootstrap something like below:

vendor\kordy\ticketit\src\Views\tickets\index.blade.php

```
Before: <div class="panel panel-default"> // Line 1 in view file
After: <div id="ticketit" class="panel panel-default ticketit-index" >
```

vendor\kordy\ticketit\src\Views\tickets\create.blade.php

```
Before: <div class="well bs-component"> // Line 1 in view file
After: <div id="ticketit" class="well bs-component ticketit-create">
```

vendor\kordy\ticketit\src\Views\tickets\show.blade.php (\partials\ticketit_body.blade.php)

```
Before: <div class="panel panel-default"> // Line 1 in view file
After: <div id="ticketit" class="panel panel-default ticketit-show ticket-{{ $ticket->id }}" >
```

OR assign ID once in Master, then use classes only in views

vendor\kordy\ticketit\src\Views\index.blade.php

```
@section('content')
Before: <div class="row">
After: <div class="row" id="ticketit">
```

vendor\kordy\ticketit\src\Views\tickets\index.blade.php

```
Before: <div class="panel panel-default"> // Line 1 in view file
After: <div class="panel panel-default ticketit-index" >
```

vendor\kordy\ticketit\src\Views\tickets\create.blade.php

```
Before: <div class="well bs-component"> // Line 1 in view file
After: <div class="well bs-component ticketit-create">
```

vendor\kordy\ticketit\src\Views\tickets\show.blade.php (\partials\ticketit_body.blade.php)

```
Before: <div class="panel panel-default"> // Line 1 in view file
After: <div class="panel panel-default ticketit-show ticket-{{ $ticket->id }}" >
```

**Comment by thekordy** [comment]
> assign ID once in Master, then use classes only in views

I am with this option :+1:
