### ISSUE TITLE
Making this work in Laravel 5.3

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#292]
I have Ticketit working great in a Laravel 5.2 app. However I cannot get it to work in a 5.3 app. Php artisan always gives an error and it seems the error is a non-object in Settings.php at line 57 or 58. Is there something different I have to do for 5.3?

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/issues/288

**Comment by sunnyjayjay** [comment]
I had already cleared the cache and composer dumped autoload, all to no avail.
