### ISSUE TITLE
Unable to finish intallation Laravel 5.4

### ISSUE THREAD

**Issue by Kyosfonica** [thekordy/ticketit#295]
The installation route doesn't exists and all I get is 404 errors form http://app/tickets-install
Also the config file doens't exist so you cannot publish it. Check the code it isn't there.

Anyone was able to install ticketit on laravel 5.4?

**Comment by thekordy** [comment]
make sure you are logged in, the config is web-based not in a file, and please review this #73

**Comment by Kyosfonica** [comment]
Solved.
Please, clarify the documentation and include that Laravel Authentication must be working with at least 1 user before continuing with step 3.
