### ISSUE TITLE
Configuration Setting paginate_items

### ISSUE THREAD

**Issue by pepoteloko** [thekordy/ticketit#296]
Hi,

I want to set de default number of items in the tables, and I changed the "paginate_items" value to 50, but always showing 10 tickets in the lists.

I'm doing it correctly?

**Comment by martinacostadev** [comment]
Hi,

You are doing right.

In `Controllers/TicketsController.php` the paginate setting is taking only be comments, right here:

`$comments = $ticket->comments()->paginate(Setting::grab('paginate_items'));`

But in the index of **Active Items** and **Completed Items** that setting is not used:

```
    public function index()
    {
        $complete = false;
        return view('ticketit::index', compact('complete'));
    }

    public function indexComplete()
    {
        $complete = true;
        return view('ticketit::index', compact('complete'));
    }
```

I think the correction would be:

```
    public function index()
    {
        $complete = false;
        return view('ticketit::index', compact('complete')->paginate(Setting::grab('paginate_items'));
    }

    public function indexComplete()
    {
        $complete = true;
        return view('ticketit::index', compact('complete')->paginate(Setting::grab('paginate_items'));
    }
```

Can you try this?

Regards,

Martín - Argentina.

**Comment by martinacostadev** [comment]
And is important use the filter in the top of the list "Show ... entries".

**Comment by thekordy** [comment]
@pepoteloko as @tinthenet said, it's left for user choice at datatables 

![ticketi demo helpdesk main page](https://cloud.githubusercontent.com/assets/11343048/22800392/e4ad22f8-ef11-11e6-9e3d-9a168a70e76d.png)

**Comment by pepoteloko** [comment]
Thanks to all!!
@tinthenet your solution does not work.
But I've modified the main view to set 50 item as default in datables.

```
<script>
    $('.table').DataTable({
         processing: false,
         serverSide: true,
         responsive: true,
         **pageLength: {{ $setting->grab('paginate_items') }},**
         lengthMenu: {{ json_encode($setting->grab('length_menu')) }},
```

**Comment by thekordy** [comment]
@pepoteloko Very good idea, It would be nice if you could put this into a PR?
