### ISSUE TITLE
Status should be listed on My Tickets list

### ISSUE THREAD

**Issue by MACscr** [thekordy/ticketit#30]
I lied about not having any other suggestions, but I hoping these thoughts benefit everyone.  =)

Don't you think that the Status of the tickets would be an important item to list in the My Tickets area? I think it's probably one of the most important pieces of info besides subject and last replied. Thoughts?

**Comment by MACscr** [comment]
Forgot to add that while you have a last updated time, you should really have some sort of indicator that shows if the ticket is waiting on the users response or an agent. Probably should be another feature request, but they are kind related? =P

**Comment by MACscr** [comment]
Ah, I see the status is shown as the subject color. Not sure if thats the best way to do it. Think its better to have a boostrap styled "button" looking item with the status instead. Easier to figure out what something is with actual text versus some color (especially when there is no legend).

**Comment by thekordy** [comment]
I was thinking of way to make it simple by lowering the number of columns, but I think we should find another solution, may be as you suggested or to put a color guidance above the table, or to replace category column with status .. Between you and me, I don't like much columns, it confuses me, the lower number of columns the better user experience.

**Comment by fishmad** [comment]
>Ah, I see the status is shown as the subject color. Not sure if thats the best way to do it. Think its better to have a boostrap styled "button" looking item with the status instead. Easier to figure out what something is with actual text versus some color (especially when there is no legend).

I thought that too, the colored text needs something meatier so it stands out more.

**Comment by FusionDesign** [comment]
When we switch to Datatables, we can do callsbacks for user-custommization in config on row colors, text colors, and more. Datatables are also extensible!

**Comment by thekordy** [comment]
Agent screen
![laravel helpdesk main page - agent](https://cloud.githubusercontent.com/assets/11343048/10256713/4a79d3c4-6953-11e5-88be-72b1ae41616c.png)

User screen
![laravel helpdesk main page - user](https://cloud.githubusercontent.com/assets/11343048/10256714/4a9c023c-6953-11e5-8a1e-553b94ceb201.png)

**Comment by thekordy** [comment]
Please note that it is not implemented in the current stable v0.0.7 , you will find it (as most of new current features) in the v0.1.0 branch 

https://github.com/thekordy/ticketit/wiki/v0.1.0-features
