### ISSUE TITLE
Footer overwritten by blade template

### ISSUE THREAD

**Issue by sgilberg** [thekordy/ticketit#300]
I'm working with the latest stable release (0.3.4), and I'm finding that the footer of my site's global template is being overwritten by the @section('footer') in the index.blade.php template of this package in the ticket views. A simple fix would be to include @parent at the bottom of the footer section, so that any footer in the master template doesn't get lost.

**Comment by thekordy** [comment]
Actually, that's a very good suggestion, It would be very nice if you could put this into a PR.
