### ISSUE TITLE
Stuck in tickets-install loop

### ISSUE THREAD

**Issue by OwenMelbz** [thekordy/ticketit#303]
Hi guys,

I've just deployed my application to our server, and the /tickets-install is stuck in a loop, i've tried manually installing it on the server, but that ended up erroring saying "visit tickets-install to install" despite already being on the page.

Suggestions would be helpful please

**Comment by sgilberg** [comment]
Hi Owen,
I had a little trouble with the install as well. I think the main thing it does is to copy the ticketit migrations into your app (if that's not already done), run them, and then seed the ticketit_settings table. This is just a guess, but if you are in a loop, it might mean that you have run the migrations but don't yet have the settings populated, and you can probably run the SettingsTableSeeder on the command line. I've also run into issues with needing to manually clear the cache when the settings table has been updated.

**Comment by balping** [comment]
If still a problem, reopen.
