### ISSUE TITLE
Setting up TicketIt on another system references previous path

### ISSUE THREAD

**Issue by jidesakin** [thekordy/ticketit#306]
I installed ticketit on my computer as a standalone app. I pushed it to a repo for my colleague to pull and set it up on his computer. But the referenced configuration still points to my computer.

**Comment by balping** [comment]
Does this help? https://github.com/balping/ticketit-app#notes

**Comment by irvine48** [comment]
I copy it from somewhere and could't find it again,
modify `TicketitServiceProvider.php`
this line
`include Setting::grab('routes');` => `include(__DIR__.'/routes.php');`

**Comment by tobz-nz** [comment]
We've got this problem as well - out deploy process creates a new release & swaps a symlink to the new release - so the path changes on each deploy. 
@irvine48's fix works.

Why would you store path info in the DB anyway?
