### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by farshid1367** [thekordy/ticketit#310]
The fonts cannot load after setting up the project in localhost, it would be appreciated if you could kindly help me to solve this issue. Thank you so much.
![font-issue](https://cloud.githubusercontent.com/assets/11360685/23656554/6e33260c-034f-11e7-9eb5-049d09a49d21.png)

**Comment by balping** [comment]
open up the dev console and see if you got any network errors

**Comment by balping** [comment]
If still an issue, reopen.
