### ISSUE TITLE
Am find hard in installing this project

### ISSUE THREAD

**Issue by asopiah** [thekordy/ticketit#312]
Hello guys,

Am new to larvel and I am also new in using the cmd in installing stuffs. I tried to follow the installation procedure provided https://github.com/balping/ticketit-app but still get it right. Any web installation script?
![captureegr](https://cloud.githubusercontent.com/assets/12970752/23751037/bee044c6-04e0-11e7-8ab7-840a16d2e129.PNG)

**Comment by Quintenps** [comment]
You'll need composer to install Laravel, more can be found here: https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by balping** [comment]
@asopiah I haven't tested my installation script on windows, could you you please report back if you've succeeded?

**Comment by asopiah** [comment]
@Quintenps I have installed composer but still not working. 
@balping I haven't succeeded. A web installation script will better for windows guys like me.

**Comment by balping** [comment]
Any new error messages?

**Comment by asopiah** [comment]
Hi @balping Same original error.

**Comment by balping** [comment]
Then you didnt succeed to install composer

**Comment by balping** [comment]
I suppose you have succeeded. If not, feel free to reopen
