### ISSUE TITLE
Installing Ticket it

### ISSUE THREAD

**Issue by thaiju** [thekordy/ticketit#314]
Hi Im a laravel newbie,

So i followed the quickinstallation steps and came till the point it starts setting up the database details for u. When it comes to the password bit it just stays like that for awhile if i press enter it returns an error saying
"Checking database connection...
Could not connect to database."

How do I seet up the database

**Comment by balping** [comment]
You should install mysql (follow any online tutorial  on it), but if you just want to try ticketit, select the sqlite option.

If you have mysql set up, when it asks for a password, enter the mysql password for the given database
