### ISSUE TITLE
I'm Facing this issue

### ISSUE THREAD

**Issue by ArunSharma009** [thekordy/ticketit#316]
![screen shot 2017-03-21 at 2 09 37 am](https://cloud.githubusercontent.com/assets/18621379/24120728/9b892606-0ddb-11e7-975f-54c0345f9992.png)

**Comment by balping** [comment]
Is it immediately after you run the script, or had there been questions before this error message?

+ Was this the first attempt you run the script?

**Comment by ArunSharma009** [comment]
Yes !
There were no questions. I followed the exact steps that you've described and everything worked fine. I changed my directory to ticketit and then ran the command " php artisan ticketit:install" and i got this error.

**Comment by balping** [comment]
Hmm. What's in `.env`? (Be careful not to post sensitive info)

**Comment by ArunSharma009** [comment]
I'm sorry but i couldn't figure that out

**Comment by balping** [comment]
`cat .env`

**Comment by ArunSharma009** [comment]
Thank you very much.
![screen shot 2017-03-21 at 4 53 07 am](https://cloud.githubusercontent.com/assets/18621379/24126162/830571fe-0df2-11e7-80e3-6f1c9de58cc9.png)

**Comment by ArunSharma009** [comment]
there were some keys as well

**Comment by balping** [comment]
Try

```bash
rm .env
cp .env.example .env
php artisan key:generate
php artisan ticketit:install
```

**Comment by ArunSharma009** [comment]
I've again received the same error after **php artisan key:generate**

**Comment by balping** [comment]
In `config/app.php` is `Kordy\Ticketit\TicketitServiceProvider::class` commented out? ([Like here](https://github.com/balping/ticketit-app/blob/5991621dff6d0d3cc656c8f26697c8a3856854d8/config/app.php#L170))

**Comment by ArunSharma009** [comment]
It worked!
Thanks a ton. 
But now i'm getting this 
![screen shot 2017-03-21 at 5 15 37 am](https://cloud.githubusercontent.com/assets/18621379/24126729/8b5049bc-0df5-11e7-8ac5-251b39a3b7c7.png)

**Comment by balping** [comment]
Yeah, you should set up a mysql database first, with  username and password and enter those here. Or if you dont want  to mess with that,  choose sqlite, which will create a single file

**Comment by ArunSharma009** [comment]
Thank you so much. I'm going with sqlite now. 
I appreciate your effort :)
