### ISSUE TITLE
Add PDF export for tickets list

### ISSUE THREAD

**Issue by pierre-guillot** [thekordy/ticketit#318]
We plan tu use ticketit for people that do lot of manual work (plumber, electrician, etc.) and they want a PDF export of tickets list.

It's possible tu use the "print" function of web browser, but the export is not very pretty (see here : https://framadrop.org/r/OVGbhYffdR#1FhCMCnT9eMRDaBC2Ob6NjAUU93QkUdlv2aduG/Ebbs=)

Why not have a "export to PDF" button to have a cool PDF export like in GLPI? (see here : https://framadrop.org/r/GcjM6XFM12#Zxd3F1aBHvvKlX0uhKxL/Iv4UeS77hiaGHJK1boHkmk=)

**Comment by balping** [comment]
Feel free to implement it yourself in your own app. You got full access to the database + you can override vendor views, it's absolutely possible.

However this is too specific to be added to the core, but @thekordy might add this to 2.0 roadmap, but even if he does so, 2.0 release is very far from now.
