### ISSUE TITLE
Ticket Index Paging

### ISSUE THREAD

**Issue by MACscr** [thekordy/ticketit#32]
Agents are going to have a lot of tickets to take care of and unfortunately right now, I am not seeing any paging support for the My Tickets section. Am I missing something?

**Comment by thekordy** [comment]
The pagination should support 10 items per page and is configurable in
config/ticketit.php

**Comment by thekordy** [comment]
This is a screen from the online demo
![kordy ticketit index example](https://cloud.githubusercontent.com/assets/11343048/10205453/96b10b42-67c1-11e5-855b-2c4d880ab416.png)
