### ISSUE TITLE
how to add additional admins

### ISSUE THREAD

**Issue by thaiju** [thekordy/ticketit#320]
I've succesfully tweaked and got it running to my liking. The only issue I currently have is how to add fresh Admin credentials after I manually installed it? Additionally I would also like to know if im to put it up on a server, direct copy pasting; would it function as such if the paths and everything i developed remains the same

**Comment by thekordy** [comment]
Register a new user, go to ticketit settings -> administrator -> create new ... and choose the user account from the list (just realized the language of this action is tricky and not accurate)

Yes, you can copy and paste if you keep env the same, and don't forget the db.

**Comment by balping** [comment]
Dont forget to update the route path in the database according to this: https://github.com/thekordy/ticketit/issues/288

**Comment by thaiju** [comment]
thank you!

**Comment by thaiju** [comment]
Sorry for all the questions, Newbie here
