### ISSUE TITLE
Notification to users by email on comments or status change

### ISSUE THREAD

**Issue by MattiaMarchiorato** [thekordy/ticketit#323]
Hi,
i can't notificate by email to user that opened a ticket when i comment ticket or change the ticket status, can you help me?

Best
MM

**Comment by MattiaMarchiorato** [comment]
I solved adding in NotificationsController
elseif (LaravelVersion::min('5.4')) {
            $mail = new \Kordy\Ticketit\Mail\TicketitNotification($template, $data, $notification_owner, $subject);

            if (Setting::grab('queue_emails') == 'yes') {
                Mail::to($to)->queue($mail);
            } else {
                //add for client notification ->cc($ticket->user->email)
                Mail::to($to)->cc($ticket->user->email)->send($mail);
            }
        }

**Comment by balping** [comment]
Could you make a PR of this?
