### ISSUE TITLE
Routes - Artisan error

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#329]
Please can you solve this ongoing problem. Any call to php artisan gives this error

    [ErrorException]
      include(../vendor/kordy/ticketit/src/routes.php): failed to open stream: No such file or directory

In ticketit_settings for routes I have:

    /home/forge/office.artlookonline.com/vendor/kordy/ticketit/src/routes.php

What is going on here?

**Comment by balping** [comment]
Trivial, but does the file exist?

Also, it's strange that in the error message it uses a relative path instead of the absolute one stored in the database. That might come from another source. Could you trace back the call in the log file?

**Comment by sunnyjayjay** [comment]
Yes the file exists.

The log shows this as the error:

    [2017-03-29 12:57:38] local.ERROR: ErrorException: include(../vendor/kordy/ticketit/src/routes.php): failed to open stream: No such file or directory in /home/forge/office.artlookonline.com/vendor/kordy/ticketit/src/TicketitServiceProvider.php:191

So that line is just 

    include Setting::grab('routes');

**Comment by balping** [comment]
What about clearing the cache?

**Comment by sunnyjayjay** [comment]
It cannot be in the cache as I have only just installed it!

**Comment by sunnyjayjay** [comment]
I am going to have to uninstall Ticketit and look for another solution as nobody is helping with this ridiculous and repetitively annoying error

**Comment by mhanoglu** [comment]
On installation current path stored in databse. When change laravel directory, system show this error.
**Solution:**
Go to phpMyAdmin
ticketit settings table name is: **ticketit_settings** and slug is **routes** edit **value** column for right path.

And settings caching for 60 minutes, if you don't wanna wait, you may delete **storage/framework/cache/data/** manually.

![image](https://cloud.githubusercontent.com/assets/8195419/26240282/1e89b760-3c89-11e7-9b38-9700eaf944bf.png)

**Comment by winfieldblum** [comment]
This was causing me issues deploying on Heroku, changing the value to "vendor/kordy/ticketit/src/routes.php" fixed it for me

**Comment by oborerichard** [comment]
I followed @marzochi 's suggestion and it worked.
Manually deleting cache was the magic step I had not done before seeing this thread
