### ISSUE TITLE
Manage Agents "Removed Agent" is still being auto assigned new tickets

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#33]
I removed an agent from one of my categories as I had too many, but when I submitted a new ticket later on it still assigned the new ticket to that removed agent.

I notice the relationship reference remains in pivot table `ticketit_categories_users` 
This may still have a purpose - if I was to manually delete the mysql row (I cant anyway) it would cause problems with any 'existing comments' that agent previously made on old tickets.

Suggest adding a flag in Pivot table to indicate if agent is still 'active' in that 'category'.
so when auto assign of tickets a query would check to see only 'active agents'.

**Comment by thekordy** [comment]
I hope this patch fixes the issue

**Comment by fishmad** [comment]
I'm having issues viewing any ticket

in TicketsController.php

both:
Master - line 92
v0.1.0 - line 125

        $agent_lists = ['auto' => 'Auto Select'] + Models\Agent::agentsLists($ticket->category_id);

1/1
FatalErrorException in TicketsController.php line 125:
Unsupported operand types

BTW I have all the localization done and noticed that you added the 'Translations' setup how can I push these?

**Comment by thekordy** [comment]
>BTW I have all the localization done and noticed that you added the 'Translations' setup how can I push these?

Really? That would save much time, Thank you :+1: 
To push contributions:
1. Fork the repository
2. Commit the changes to the Fork
3. Submit a Pull Request
 
https://help.github.com/articles/using-pull-requests/

**Comment by thekordy** [comment]
Of course you need to fork the v0.1.0 repository where the translation setup.

**Comment by fishmad** [comment]
1/1
ErrorException in TicketsController.php line 125:
array_merge(): Argument #2 is not an array

**Comment by thekordy** [comment]
The error probably because there is a tickets empty category with no agents
assigned. I fixed it so it shows empty agents list instead of the error.

**Comment by fishmad** [comment]
I can confirm this bug is now fixed.

Removed agents are not being assigned tickets anymore.
Error 1 fixed: Unsupported operand types
Error 2 fixed: array_merge(): Argument #2 is not an array

Looking good.

**Comment by FusionDesign** [comment]
This has been updated in v0.1.0 to `['auto' => 'Auto Select'] + $this->agent->agentsLists($ticket->category_id)->all()`

->all() was introduced for ->lists() in 5.1 iirc.

**Comment by FusionDesign** [comment]
This is resolved. Go ahead and submit a Pull Request per Kordy's instructions for Localization
