### ISSUE TITLE
Add an automatic setup script

### ISSUE THREAD

**Issue by asopiah** [thekordy/ticketit#330]
This project installation on Linux and mac work fines and simple but have tried severally to install the project on windows without success. 
Suggestion:
It would be nice to have a simple setup.php script (as RoundCube is doing).

The aim would be to simplify the installation of project for the common case of built-in auth, sqlite, mod_php+apache with the spool protected by an .htaccess file, mostly targetting webhosting platforms where shell access is not provided and windows OS users.
Following RC inspiration, the setup could as well remove itself after the procedure is completed, generating a single web page showing the installation details, along with a randomly generated password for the admin user.
Regards,
Thanks and looking forward for a better ticketit installation on windows OS

-----

- [x] Windows support
- [ ] Browser install

**Comment by balping** [comment]
OK, I'll see how I can get this working in Hell.

The browser-based setup is a good idea and a valid use case, though no shell access is very limiting, I'll see what I can do.

**Comment by balping** [comment]
I checked some Windows php-apache howtos and I'd rather avoid Hell, sorry.

I've written a notice in the main readme though in case someone wants to take the effort: https://github.com/balping/ticketit-app#windows-devs-needed

**Comment by dbeulen** [comment]
I've just tested the current installation with composer and artisan on windows, no problems with that installation here. 

As this stackoverflow post (http://stackoverflow.com/questions/15969948/use-composer-without-ssh-access-to-server) is explaining, it is not possible to use composer without shell access. 

A possible solution is to make a package with all dependencies preinstalled. Only then a browser installation would be possible, but you will throw away all the nice things composer provides. In my opinion not a real option.

My advice for @asopiah would be to install ticketit on a local machine with composer, then copy the application to a production server.

**Comment by balping** [comment]
@dbeulen 

Thank you very much for your investigation!

I found another [so article](http://stackoverflow.com/questions/17219436/run-composer-with-a-php-script-in-browser) about executing composer commands without shell access. I haven't tried it, it might or might not work. If it does, it would be a much convenient solution compared to pre-packaging.

But I agree, local install + upload should be fine in most cases.

**Comment by asopiah** [comment]
@dbeulen 
Your advice of installing the project on a local machine and then copying it to a production server works fine.

Thanks for the suggestion.

**Comment by balping** [comment]
I decided no to make a shared-hosting browser install script because it would be too much of a mess.

Every shared hosting provider provides different privileges + I would need to supply regular builds with the latest versions that I wouldn't like to do.

Plus I expect issues coming in due to various misconfigs in various environments - I don't want to deal with that neither.

If you need a laravel app on shared hosting just upload the files. It shouldn't be too hard. But rather rent a VPS, it's not much more expensive and has many benefits.
