### ISSUE TITLE
ticketit not installing on laravel 5.4

### ISSUE THREAD

**Issue by brazitech** [thekordy/ticketit#334]
ticketit not installing on laravel 5.4. 5.4 uses  "yajra/laravel-datatables-oracle": "7.0", by default.
need to change  "yajra/laravel-datatables-oracle": "~6.0", to  "yajra/laravel-datatables-oracle": "^6.0",
can anyone explain ho to do this?
thanks
Gator

**Comment by brazitech** [comment]
now getting the following error
if i   use composer require kordy/ticketit:0.* it tries to install v0.1.1

if i use composer require kordy/ticketit:0.2.* i get the following

https://pastebin.com/raw/FHWJ1ZmE

Installation failed, reverting ./composer.json to its original content.

**Comment by thekordy** [comment]
use 0.2.x-dev instead of 0.*

**Comment by brazitech** [comment]
after testing ^6 only works in lynx. not working for windows. in windows ^7 is the only thing that works. composer in windows is not recognizing the ^6 to include 7. i think the command for v6 or greater is different in windows. i do not know what that is in composer.

**Comment by mmguide2003** [comment]
`Class 'Kordy\Ticketit\TicketitServiceProvider' not found`

I don't think composer is downloading the package.
I cannot find the vendor folder and there is no reference to kordy in the composer lock file.
