### ISSUE TITLE
ticketit still not installing on laravel 5.4

### ISSUE THREAD

**Issue by brazitech** [thekordy/ticketit#335]
now getting the following error
if i use composer require kordy/ticketit:0.* it tries to install v0.1.1

if i use composer require kordy/ticketit:0.2.* i get the following

https://pastebin.com/raw/XMu4Ttcr

if i use  composer require kordy/ticketit
i get

https://pastebin.com/raw/nydgbzVX

what version do i install to get ^6.0 instead of ~6.0

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/issues/334#issuecomment-294346939

**Comment by sunnyjayjay** [comment]
Please can you clarify what to do to solve this? I am still getting

    Call to undefined method Illuminate\Foundation\Application::share()
