### ISSUE TITLE
ErrorException in ClassLoader.php line 414:

### ISSUE THREAD

**Issue by sekhoanem** [thekordy/ticketit#340]
![error hosting](https://cloud.githubusercontent.com/assets/21284746/25376602/1807a542-29a5-11e7-941b-c59442835e30.jpg)

Hi, I have uploaded my application on a shared hosting and I immediately came up against the error in the attached screenshot: ErrorException in ClassLoader.php line 414: include(/usr/www/users/womenmpmqg/members.womeninafrica.co.za/system/vendor/composer/../kordy/ticketit/src/TicketitServiceProvider.php): failed to open stream: No such file or directory

Do you perhaps know the cause of it and how to fix it?

Thanks

**Comment by thekordy** [comment]
the routes file path does not seem correct to me.

**Comment by balping** [comment]
This has been asked many times, change the row `route` in the settings table in the database.
