### ISSUE TITLE
not integrating into existing laravel 5.4 project

### ISSUE THREAD

**Issue by brazitech** [thekordy/ticketit#341]
all the ticketit repo tags are using datatables ^6.0. Laravel 5.4 uses ^7.0. you use this in the quick install. when you follow the integrating into an existing app it only allows for ^6.0, this breaks the existing app.
this needs to be fixed or change the read me to state that ticketit only works in laravel 5.4 when using the quick install. it will save people a lot of wasted time trying to get this to work.

Laravel Version Compatibility
Laravel 	Package
4.2.x 	3.x
5.0.x 	6.x
5.1.x 	6.x
5.2.x 	6.x
5.3.x 	6.x
5.4.x 	7.x
as per https://github.com/yajra/laravel-datatables

**Comment by brazitech** [comment]
if you look at  brazidev/ticketit it finally worked. changed to ^7.0.

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/commit/7725637774554807ab6da4f576aadfbeb861fe9e

Thanks.
