### ISSUE TITLE
TicketsController@index not defined

### ISSUE THREAD

**Issue by rabb-bit** [thekordy/ticketit#342]
So I was following the instructions on extending the functionality of the TicketsController, and I moved the routes.php to app\Http\ and edited the routes configuration ... and when I saved the routes. the error is this

```
ErrorException in UrlGenerator.php line 337:
Action Kordy\Ticketit\Controllers\TicketsController@index not defined. (View: C:\laragon\www\tickettit\vendor\kordy\ticketit\src\Views\shared\nav.blade.php) (View: C:\laragon\www\tickettit\vendor\kordy\ticketit\src\Views\shared\nav.blade.php) (View: C:\laragon\www\tickettit\vendor\kordy\ticketit\src\Views\shared\nav.blade.php)
```

now, I figured out that the caused of the issue is the @index in the nav.blade.php

I removed this portion in the nav.blade.

```
<li role="presentation" {{--class="{!! $tools->fullUrlIs(action('\Kordy\Ticketit\Controllers\TicketsController@index')) ? "active" : "" !!}"--}}>
                <a href="{{ action('\Kordy\Ticketit\Controllers\TicketsController@index') }}">{{ trans('ticketit::lang.nav-active-tickets') }}
                    <span class="badge">
                         <?php
                            if ($u->isAdmin()) {
                                echo Kordy\Ticketit\Models\Ticket::active()->count();
                            } elseif ($u->isAgent()) {
                                echo Kordy\Ticketit\Models\Ticket::active()->agentUserTickets($u->id)->count();
                            } else {
                                echo Kordy\Ticketit\Models\Ticket::userTickets($u->id)->active()->count();
                            }
                        ?>
                    </span>
                </a>
            </li>
```

and everything worked, the only problem is that menu is missing.

so I tried to confiure the '\Kordy\Ticketit\Controllers\TicketsController@index to be
`'./app/Http/Controllers/MyTicketsController@index() `

but id didn't work. 

also I tried
`fullUrlIs(action('MyTicketsController@index')) ? "active" : "" !!}"--}}>`
and it didn't work

and also, I checked the Kordy\Ticketit\Controllers\TicketController@index method and it's there.

is the '\Kordy\Ticketit\Controllers\TicketsController  supposed to be hard coded?

**Comment by thekordy** [comment]
no it should not

**Comment by boodovskiy** [comment]
> ErrorException in UrlGenerator.php line 337:
Action Kordy\Ticketit\Controllers\TicketsController@index not defined.

Did You figure out with it? I have the same problem after extending the functionality of the TicketsController and CategoriesController.

**Comment by balping** [comment]
What about overriding this blade file in resources/views/vendor dir?

**Comment by boodovskiy** [comment]
Yes, thank you - it works. I override blade file, where I changed path in action such way:
`$tools->fullUrlIs( action('\App\Http\Controllers\MyTicketitController@index'))`

**Comment by bmpf** [comment]
Hello, Im new to laravel, I was installing this functionality and i got this error :/

"Action Kordy\Ticketit\Controllers\TicketsController@index not defined."

**Comment by paljinderSingh13** [comment]
this is not working

InvalidArgumentException
Action Kordy\Ticketit\Controllers\TicketsController@index not defined.

**Comment by danilocarva9** [comment]
does anybody make this work
? i'm getting redirect to /home

InvalidArgumentException
Action Kordy\Ticketit\Controllers\TicketsController@index not defined.

**Comment by ShifanThawfeek** [comment]
Hi friends, I am getting the same error "Action Kordy\Ticketit\Controllers\TicketsController@index not defined." 

Please let me know how to fix this. Thanks!
