### ISSUE TITLE
Include other users in a ticket

### ISSUE THREAD

**Issue by jryd** [thekordy/ticketit#343]
This is a feature request, or a question as to how I could incorporate this myself; including other users in a ticket.

A user opens a ticket requesting access to something.
The agent needs to check with their supervisor, and so needs to add them to the ticket to comment about it.
The supervisor is then included in the ticket and can access it the same as a user.

Could this be added as a possible future feature?

If you have an idea of how this could be added now at a high level, then let me know and I can try implement it.

**Comment by thekordy** [comment]
Agents and admins can have access to all tickets, check the `agent_restrict` option in configuration -> permissions.
