### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long

### ISSUE THREAD

**Issue by pirmax** [thekordy/ticketit#344]
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `ticketit_settings` add unique `ticketit_settings_lang_unique`(`lang`))

**Comment by thekordy** [comment]
may be that solves it https://laravel-news.com/laravel-5-4-key-too-long-error/
