### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by prasadvittaldev** [thekordy/ticketit#347]
datatables warning: table id=datatables_table_0 - ajax error.datatables warning: table id=datatables_table_0 - ajax error. ticketit

**Comment by prasadvittaldev** [comment]
no solution found online

**Comment by ghost** [comment]
Same error.

DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I have categories, priorities and statuses.

@thekordy

**Comment by balping** [comment]
Try composer update, if you're using L5.4, laravel-datatables 7+ should be installed.

The latest release of ticketit probably fixes this, please try

**Comment by irvine48** [comment]
Tried with composer update, still facing the same issue.

**Comment by balping** [comment]
Could you please tell your laravel,  laravel-datatables and ticketit versions? They can be found in  `composer.lock`

**Comment by irvine48** [comment]
i am not sure am i get the right things for you.
`"name": "laravel/framework",
            "version": "v5.4.23",`
`"name": "yajra/laravel-datatables-oracle",
            "version": "v7.5.0",`
`"name": "kordy/ticketit",
            "version": "v0.3.6",`

this project i installed it via this command `composer create-project --prefer-dist balping/ticketit-app ticketit`

edit1*
`app.js:29 GET http://127.0.0.1:8002/tickets/data?draw=1&columns%5B0%5D%5Bdata%5D=id&colum…art=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1495620009828 401 (Unauthorized)` 
===> fix with setting session from file to database

edit2*
`app.js:29 GET http://127.0.0.1:8002/tickets/data?draw=1&columns%5B0%5D%5Bdata%5D=id&colum…art=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1495621507044 404 (Not Found)`

**Comment by balping** [comment]
Yes, this is what I asked, thank you.

 I made a fresh install using the same command and these are the exact same versions I have.
It's working for me, sorry I could't reproduce your bug, so I can't really investigate further. I've got no idea why it's not working for you.

**Comment by prasadvittaldev** [comment]
Can you suggest us a operating system in which you installed .

**Comment by balping** [comment]
I'm using ubuntu 16.04 

But it would be very strange, if this error was os specific

**Comment by irvine48** [comment]
https://github.com/yajra/laravel-datatables/issues/497

Yajra mentioned `artisan serve` might buggy.... i tested on my xampp, it finally work without any issue.

**Comment by balping** [comment]
Please post rows `main_route`, `main_route_path` and `routes` from table `ticketit_settings` in the database. I.e. the result of 

```sql
SELECT * FROM ticketit_settings WHERE slug LIKE '%route%';
```

**Comment by balping** [comment]
Also, what happens if you replace 

```php
"$main_route_path/data/{id?}"
```

to

```php
"$main_route_path/data"
```

in line 9 in `vendor/kordy/ticketit/src/routes.php`?

**Comment by balping** [comment]
@irvine48 Ah good, I've just seen your edit.

I usually use `php -S localhost:8000 -t public` for development, I've never encountered an issue like this. I think it's a good alternative of `artisan serve`, it doesn't require any extra setup.

@salihevrendemir , @prasadvittaldev can you confirm that using a webserver other than `artisan serve` solves the issue?

**Comment by prasadvittaldev** [comment]
how to do that .. copy to var/www/html/

**Comment by balping** [comment]
@prasadvittaldev 

Here's the official documentation: https://laravel.com/docs/5.4#web-server-configuration

I personally use `php -S localhost:8000 -t public` for development, as I mentioned above.

**Comment by prasadvittaldev** [comment]
tried that too .. still the same error only in admin page .. agent page
working perfectly

**Comment by prasadvittaldev** [comment]
%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=owner&columns%5B6%5D%5Bname%5D=
users.name
&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=category&columns%5B7%5D%5Bname%5D=
ticketit_categories.name
&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1495645254739


this is what its coming in cli

**Comment by irvine48** [comment]
@balping  tested with `php -S localhost:8000 -t public`, produce same error happen on admin page.

**Comment by balping** [comment]
The problem still seems to be with the webserver if you say that it works with apache.

Please try this, just a silly idea but might work

> Also, what happens if you replace 
> 
> ```php
> "$main_route_path/data/{id?}"
> ```
> 
> to
> 
> ```php
> "$main_route_path/data"
> ```
> 
> in line 9 in `vendor/kordy/ticketit/src/routes.php`?

**Comment by irvine48** [comment]
"$main_route_path/data" or "$main_route_path/data"
both negative.

**Comment by irvine48** [comment]
@balping hey, i wonder if change the ajax get request to post request might be a possible solution for this, can you lead me to the part should make change ?

I found the route, but not sure where to get the ajax part.

**Comment by balping** [comment]
vendor/kordy/ticketit/src/routes.php

**Comment by irvine48** [comment]
@balping It work, i made these change on the ajax call, with my knowledge still can't modify your code well. Here attached with the changes. As references.

> index.blade.php

```
ajax:
{
   type: 'POST',
   url: '/tickets/data',
   dataType: 'json',
   data: {
      '_token': '{{ csrf_token() }}',
   },
},
//ajax: '{!! route($setting->grab('main_route').'.data', $complete) !!}',
```

> routes.php
```
    //COMMENT OUT THIS
    //Route::post("$main_route_path/data/{id?}", 'Kordy\Ticketit\Controllers\TicketsController@data')
    //        ->name("$main_route.data");
```
> web.php
```
   //ADD THIS TO LARAVEL ROUTES.PHP
   Route::post("/tickets/data/{id?}", '\Kordy\Ticketit\Controllers\TicketsController@data');
```
