### ISSUE TITLE
Master blade did not show ticket list

### ISSUE THREAD

**Issue by bahman2216** [thekordy/ticketit#352]
I just installed on laravel 5.4
In master blade just display header of datatable without my tickets!
`@extends('layout')
<head>
    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <title>Ticket- @yield('page')</title>
</head>
@yield('content')

@yield('footer')`

**Comment by balping** [comment]
In your master layout file, you probably don't want to extend anything. + in the default install the master template is `layouts.app`, you might want to use that file instead.

Have a look at this for a working example:

https://github.com/balping/ticketit-app/blob/master/resources/views/layouts/app.blade.php

**Comment by irvine48** [comment]
@balping,

Facing the same issue just now, please update the installation guide, include a download link for template example `ticketit.blade.php` , point user drag this template into `views/layouts/...`

On `../ticket_install` page, add-on another selection for template instead modifying the master blade.

Should be less confusing.

**Comment by balping** [comment]
@irvine48 

I've updated the corresponding wiki page.

No, I won't add a pre-made template to the installation. Only those should choose the manual installation who already got something customised and it's not a good idea to make guesses on what directory structure and filename conventions they have/want. For those who want a default template,  the quick installer is the way to go.
