### ISSUE TITLE
Repeated checks.

### ISSUE THREAD

**Issue by kikoseijo** [thekordy/ticketit#353]
Seems that this package its doing a call on every view it loads, 
Haven't you try to use debugbar?

Well, when user its logged in, then you do a find of the Agent this where all happends
view()->composer('*', function ($view) {
                if (auth()->check()) {
                    **$u = Agent::find(auth()->user()->id);**
                    $view->with('u', $u);
                }
                $setting = new Setting();
                $view->with('setting', $setting);
            });

And this with your package and without:

as you can see, does a new user call on every view load, 

![screen shot 2017-05-26 at 04 38 35](https://cloud.githubusercontent.com/assets/1528668/26478560/511abf1e-41cd-11e7-95d2-cb3efb25bf3b.png)
![screen shot 2017-05-26 at 04 38 10](https://cloud.githubusercontent.com/assets/1528668/26478561/51436252-41cd-11e7-8f0c-418f37b71c15.png)

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/releases/tag/v0.3.7
