### ISSUE TITLE
Is it possible to show tickets when reply from auto received email directly, not webapp?

### ISSUE THREAD

**Issue by Seroja1010** [thekordy/ticketit#357]

**Comment by balping** [comment]
Could you specify this? It's not clear what you're asking

**Comment by kikoseijo** [comment]
He wants to reply to a ticket direct from email.
For that, you need generate some sort of ticketID in the subject or headers, then have a script able to enter your email account and search for email reply.
This library does not do that.

**Comment by balping** [comment]
It's been put to hold on this version, see these topics:

https://github.com/thekordy/ticketit/issues/302
https://github.com/thekordy/ticketit/issues/117
