### ISSUE TITLE
How to Change the view with my own design

### ISSUE THREAD

**Issue by skooperss** [thekordy/ticketit#358]
I want to change the front end for users?

**Comment by balping** [comment]
You can override views without changing vendor code. Eg. `resources/views/vendor/ticketit/shared/nav.blade.php` will override `vendor/kordy/ticketit/src/Views/shared/nav.blade.php` If you do it this way, you don't have to worry about updates, your changes won't be lost. However you might want check if something changed in the original file after an update. If so, it's possible that you have to modify your override file manually. See docs: https://laravel.com/docs/5.3/packages#views
