### ISSUE TITLE
have error in isAgent() 

### ISSUE THREAD

**Issue by webineh** [thekordy/ticketit#360]
hi all

after run route /tickets return error

ErrorException
Call to a member function isAgent() on null (View: D:\xampp\htdocs\gitlab\roshana2\vendor\kordy\ticketit\src\Views\tickets\partials\datatable.blade.php) (View: D:\xampp\htdocs\gitlab\roshana2\vendor\kordy\ticketit\src\Views\tickets\partials\datatable.blade.php) (View: D:\xampp\htdocs\gitlab\roshana2\vendor\kordy\ticketit\src\Views\tickets\partials\datatable.blade.php)

**Comment by rebootcode** [comment]
error provides you enough information to get you started working on it. It means there is no agent. It should have added first user by default. but if there is not any. Add one and assign him agent role.
