### ISSUE TITLE
Congratulation! For being one of the worst package for laravel - 11 duplicate query / 16

### ISSUE THREAD

**Issue by rebootcode** [thekordy/ticketit#361]
Any comment on below :-1:  

![Image of Worst module built for laravel ](http://0me.in/files/onxqaz75276.png)

**Comment by thekordy** [comment]
Very rude!! The time you took to insult us, you could have used it to find another package or better to contribute something useful. 

Actually insulting others might be easier to you than taking from your time and efforts to make something useful.

**Comment by balping** [comment]
Your critics  on repeated queries is valid, however you could have said it in a way which is not insulting.

This has been reported before see issue no 256

If you'd like to be more constructive, suggest a solution, or send a PR.
