### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by ayolana** [thekordy/ticketit#367]
Thanks for the fantastic package

Can you please include in your documentation to change the CACHE_DRIVER to array. If doesn't get updated easily.

i cloned to my localhost and everything was working. I then wanted to push live with my database. The first time i loaded the site the routes (in the ticketit_settings tables) it picked was my local server. 

Refreshed and debug so many times it didn't work. Was until i navigated to your Settings Model and saw cache then I changed the driver to array then it work.

**Comment by balping** [comment]
It's not related to the cache driver, but to flushing the cache.
