### ISSUE TITLE
what ticket status exactly do ? 

### ISSUE THREAD

**Issue by jbehrouzi** [thekordy/ticketit#369]
hi there and thank's to you for this package

i have a question about status , how could admins change status ? or what status do ?

**Comment by balping** [comment]
Statuses are to indicate the current status of progress of an issue. Eg. new -> read -> working on it -> closed

By default (if installed through the quick installer), ticketit has 3 statuses: new, closed, reopened. You can add new ones / edit them at Settings -> statuses.

The above three have special meanings, they are set automatically when opening / closing /re-opening a ticket. These action can be configured at settings -> configuration -> tickets by setting `default_status_id`,  `default_close_status_id`  and  `default_reopen_status_id`



You can change the status of an existing ticket manually by clicking the edit button on the ticket's page.
