### ISSUE TITLE
Edit ticket - Unable to re-assign or update ticket in branch v0.1.0

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#37]
Unable to select Agents for re-assign - None available in drop-down

![capture2](https://cloud.githubusercontent.com/assets/12012101/10266019/94e56bfc-6a94-11e5-8367-deb353fef9fe.PNG)

__Also if try to change subject line and save changes - error is thrown below:__

Whoops, looks like something went wrong.

1/1
ErrorException in TicketitServiceProvider.php line 52:
Trying to get property of non-object
in TicketitServiceProvider.php line 52

**Comment by FusionDesign** [comment]
Fixed in v0.1.0 by me and in master by thekordy.
