### ISSUE TITLE
Installing in subdomain and not able to update ticketit_settings.default

### ISSUE THREAD

**Issue by stevecreekmore** [thekordy/ticketit#372]
I got all the way up to /tickets_install and getting an error with route paths.  Followed your instructions to update (MySql) ticketit_settings with the correct path.
I updated the field 'value' with the correct path but not able to update the field 'default', is this a MySql thing I'm unaware of?

![screen shot 2017-07-17 at 9 55 51 am](https://user-images.githubusercontent.com/5994720/28277129-2dc996ac-6ad6-11e7-9f77-69a9db233ce2.png)

**Comment by balping** [comment]
`default` itself is a keyword in sql, try the following

```sql
select `default` from ticketit_settings;
```

PS. I  don't think you need to set the default value, value should be enough.
