### ISSUE TITLE
The requested URL /fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff2 was not found on this server.

### ISSUE THREAD

**Issue by luizpatrocinio** [thekordy/ticketit#375]
The icons do not appear in /tickets-admin

####

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff2 was not
 found on this server.</p>

######

**Comment by thekordy** [comment]
I don't think this relates to ticketit package. But you can solve this by downloading the required file and copy it to that path in the error.
