### ISSUE TITLE
Can you tell me how can i extend controller

### ISSUE THREAD

**Issue by wasiqaftab** [thekordy/ticketit#381]
HI

i follow the documentation but i get issues it says controller not found 
`
class DashboardController extends Kordy\Ticketit\Controllers\TicketsController
{
  `
also i need to override datatable function or i need to query data according to my needs so i need a function so how should i do that

**Comment by balping** [comment]
You're missing a backslash: 

`class DashboardController extends \Kordy\Ticketit\Controllers\TicketsController`

**Comment by wasiqaftab** [comment]
thx but if i need to override a function in controller should i use same
name amd xan i change view in it. also are u using cache in it

**Comment by balping** [comment]
Yes, overriding means using the same function name. You don't have to change the view names in the controllers, you can override the views this way: https://github.com/thekordy/ticketit/issues/358

**Comment by balping** [comment]
And yes, some parts are cached, config mainly.

**Comment by wasiqaftab** [comment]
Thanks for your prompt reply last question (hope fully :) ) should i need to update route file if yes than how i can do that i read in documentation should i need to update it in database or how that works little confusing

**Comment by wasiqaftab** [comment]
if you see here
http://prntscr.com/gakkil
i copy route file from package and update db as well please check screen grab
http://prntscr.com/gakl3d

but if i remove route in my route file just to test it still works

**Comment by balping** [comment]
You have to specify the route file in the database: `slug='routes'` in table `ticketit_settings`. It was not the best choice, it confuses a lot of people.

**Comment by balping** [comment]
By default it points to ticketit's own route file. If you don't want to customise to routes, you don't have to anything with that.

**Comment by wasiqaftab** [comment]
Thanks got it

**Comment by wasiqaftab** [comment]
Can you please give me one example  Like if this the default route and i write my own controller how can i add my own controller should i just replace kordy/ticketit to controller name which i need to change 
`
Route::resource($main_route_path, 'Kordy\Ticketit\Controllers\TicketsController', [
            'names' => [
                'index'   => $main_route.'.index',
                'store'   => $main_route.'.store',
                'create'  => $main_route.'.create',
                'update'  => $main_route.'.update',
                'show'    => $main_route.'.show',
                'destroy' => $main_route.'.destroy',
                'edit'    => $main_route.'.edit',
            ],
            'parameters' => [
                $field_name => 'ticket',
            ],
        ]);
`

**Comment by wasiqaftab** [comment]
Sorry it gives me this error if i follow documentation do i need to copy all functions in my controller

http://prntscr.com/galwcw

**Comment by wasiqaftab** [comment]
I got this error
`Declaration of App\Http\Controllers\DashboardController::data(App\Http\Controllers\Datatables $datatables, $complete = false) should be compatible with Kordy\Ticketit\Controllers\TicketsController::data(Yajra\Datatables\Datatables $datatables, $complete = false)`

**Comment by thekordy** [comment]
unfortunately, you won't be able to extend the controller unless you extend the service provider itself, so you can bind a custom routes file where you might be able to change the controller.
