### ISSUE TITLE
Instalación ticketit

### ISSUE THREAD

**Issue by VHSR9479** [thekordy/ticketit#393]
buenas soy nuevo utilizando este framework y al intentar instalar el sistema TIcketit  presento un problema con:
![image](https://user-images.githubusercontent.com/21245168/29980032-73023480-8f0d-11e7-8af8-85f8ef9b71d6.png)

el sistema después de autentificarse  me muestra este mensaje de error:
![image](https://user-images.githubusercontent.com/21245168/29980082-c3b6e178-8f0d-11e7-8f27-fdd0aeecd55b.png)

Ya he configurado las migraciones desde  la carpeta ticketit\vendor\kordy\ticketit\src\Migrations,
las dependencias, la configuración de autentificacion  y la vista maestra, los he seguido con el paso a paso https://github.com/thekordy/ticketit.

pido su amable colaboración muchas gracias

**Comment by balping** [comment]
@mandrakecr please

**Comment by VHSR9479** [comment]
@balping  de pronto sabes como solucionarlo?

**Comment by balping** [comment]
Ok, I don't speak Spanish, but I'll try to give it a go with google translate

First, if you want the simplest way to install ticketit and you don't have any other functionality already, use the [quick installer](https://github.com/balping/ticketit-app). It's dead simple.

---

However if you want to stick to manual installation we must solve your issue. Have you registered the service provider in config/app.php ?

**Comment by VHSR9479** [comment]
la verdad he intentado utilizar el instalador rápido, y presento el mismo error al finalizar la instalación. 
![image](https://user-images.githubusercontent.com/21245168/30038032-615e4f9a-9186-11e7-9e7f-bd71ce80d6e3.png)

![image](https://user-images.githubusercontent.com/21245168/30038047-85f755ea-9186-11e7-8a03-e6a7da6a4dd5.png)
 
todo perfecto, hasta que ingreso los datos de usuario y sale este error.
![image](https://user-images.githubusercontent.com/21245168/30038088-cc187202-9186-11e7-8dbc-d1f104a5b227.png)

**Comment by VHSR9479** [comment]
y en la instalación manual tengo instalados correctamente estos proveedores.
![image](https://user-images.githubusercontent.com/21245168/30038152-40fb440a-9187-11e7-9108-9487cc4c49fe.png)

**Comment by balping** [comment]
Try to set the root folder to the public directory

https://laravel.com/docs/5.5#web-server-configuration

You could also use

`php -S localhost:8000 -t public/`

and then open http://localhost:8000 in your browser.

**Comment by mandrakecr** [comment]
@VHSR9479 

hola, disculpen pero no había visto esto hasta ahora pareciese no tienes publicados algunas de las bases, prueba con composer dump-autoload. 

Sino con gusto mandame un privado con tu skype o correo y con gusto te ayudo.

@balping  Will try to help him, sorry didn't catch this message until now

**Comment by VHSR9479** [comment]
No, la verdad es que el re direccionamiento a la ruta : vendor\kordy\ticketit\src\Controllers, no lo recnnoce.
![image](https://user-images.githubusercontent.com/21245168/30039164-f489c360-9192-11e7-9db8-c090e8fbd9e3.png)
ingreso los datos de usuario y continua saliendo el mismo error.
![image](https://user-images.githubusercontent.com/21245168/30039182-1bfccc8a-9193-11e7-93d7-83d0167b098b.png)

configure el public / .htaccess  y directamente en el terminal.
![image](https://user-images.githubusercontent.com/21245168/30039189-32f4e60c-9193-11e7-95cd-59c476c25a44.png)

**Comment by balping** [comment]
@mandrakecr Thank you :-)

@VHSR9479  what's the value of the row where `slug='routes'` in table `ticketit_settings` ? Check if it points to a valid file.

**Comment by VHSR9479** [comment]
la tabla ticketit_settings se encuentra  vacía.
yo ejecute la migracion desde la ruta : vendor\kordy\ticketit\src\Migrations

**Comment by balping** [comment]
It shouldn't be empty. This means that the install script `php artisan ticketit:install` didn't run succesfully.

You don't have to run the migrations again beacause the fact that ticketit_settings exists means that the migrations have been already run.

**Comment by mandrakecr** [comment]
Si las tablas estan vacias el migration no ha corrido, deberias probar a correrlas manualmente. ¿cuál versión de laravel estas usando?

**Comment by VHSR9479** [comment]
@balping  gracias, me hacia falta ` Schema::defaultStringLength(191;` ,  ahora si  la tabla ` ticketit_settings` me guarda registros.
![image](https://user-images.githubusercontent.com/21245168/30070702-ef5d9ef6-9229-11e7-8a5b-655caef53489.png)

Pero cuando inserta esta linea presenta un error.
![image](https://user-images.githubusercontent.com/21245168/30069956-a9e9a1f0-9227-11e7-8c95-950778601de4.png)

El ancho del campo  en la base de datos.
![image](https://user-images.githubusercontent.com/21245168/30070061-ede84438-9227-11e7-8aa7-dffd06866a6e.png)

**Comment by VHSR9479** [comment]
@mandrakecr la version de  laravel es 5.4.36

**Comment by balping** [comment]
Interesting. The type shouldn't be varchar but mediumtext. See this migration: https://github.com/thekordy/ticketit/blob/0.2/src/Migrations/2016_01_15_040207_enlarge_settings_columns.php

Mediumtext can have the size of 2<sup>24</sup> − 1 bytes which should be more than enough.

Probably the above migration has failed to run

**Comment by balping** [comment]
Since `Schema::defaultStringLength(191);` was a problem for you, maybe you should try to run migrations again.

**Comment by VHSR9479** [comment]
@balping  y @mandrakecr  muchas gracias ya funciona me hacia falta la dependencia `doctrine/dbal`.
este hilo ya se ha cerrado

**Comment by balping** [comment]
You're welcome. If you have other issues, feel free to open a new thread.
