### ISSUE TITLE
Configs don't really work

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#4]
1. `'main_route'`

I changed this to `'support'`, I got the following error message:

```
Route [tickets.create] not defined. (View: /var/www/vendor/kordy/ticketit/src/views/tickets/index.blade.php)
```

2. `'master_template'`

I changed `'master_template'` to `'app'`. Now when opening page `tickets/create`:

```
View [master] not found. (View: /var/www/vendor/kordy/ticketit/src/views/tickets/create.blade.php)
```

So it still needs a `master.blade.php`. My workaround is the following: I created a `master.blade.php` with content `@include('app')`. Of course it works, but since you offer these configs, please make them working.

**Comment by thekordy** [comment]
1. Fixed 4c084a3
2. Fixed 3a8d374

Very pleased with your feedback, thank you :)

**Comment by balping** [comment]
Thanks for the fixes and thanks for creating this package. I'll definitely use it

**Comment by thekordy** [comment]
That is a good news for me. Thanks for using it :)
