### ISSUE TITLE
Don't want middleware to create new ticket  

### ISSUE THREAD

**Issue by sandeep-mishra123** [thekordy/ticketit#400]
Hey
I much appreciate your work but i stuck some where.
I'm implementing it as for client so don't want to that ticket should be raised by only logged-in user. 

Help me ASAP

**Comment by thekordy** [comment]
I am sorry, but it doesn't support guests, only logged in users can create tickets.

**Comment by sandeep-mishra123** [comment]
can i off sendingEmails to agent ? any solution @thekordy ?

**Comment by winfieldblum** [comment]
@sandeep-mishra123 sounds like you're wanting to modify the codebase, you may wish to clone and make changes for your own version
