### ISSUE TITLE
Remove hardcoded 'App\User'

### ISSUE THREAD

**Issue by ngugijames** [thekordy/ticketit#401]
Howdy!

1. Brilliant package! Thanks for all you've done.

2. Could we remove the requirement that a User model exists under 'App\User'. Instead we could use ``config('auth.providers.users.model')`` to get the actual location of the User Model.

I can write a PR.

This requirement is currently making it hard for us to use this package.

Thoughts?

**Comment by balping** [comment]
This package used to have config files, but we moved to database config only, which wasn't necessary a good move. So in 2.0 we'll return to file based config. But until then to avoid confusion, I think it's better not to have config files.

What you could do as a workaround is defining a [class alias](http://php.net/manual/en/function.class-alias.php).

**Comment by ngugijames** [comment]
Good suggestion.

Additionally, there are several references to the App namespace. These fail when the namespace has been customised.

When are you planning to start working on the new version?

**Comment by balping** [comment]
Well, if you have a look on the [2.1 branch](https://github.com/thekordy/ticketit/tree/2.1) you can see, that the work has started, but the latest commit is about a year old. I hope kordy will continue working on it sometime.

**Comment by balping** [comment]
PS. This is how the model config in v2 will look like: https://github.com/thekordy/ticketit/blob/2.1/src/Config/models.php

**Comment by ngugijames** [comment]
Nice! I like how configurable the models are. Looking forward to it. 
Thanks for your feedback @balping .
