### ISSUE TITLE
Routes not configurated after install

### ISSUE THREAD

**Issue by GuiRangel08** [thekordy/ticketit#402]
Hi, i find this app in google and i liked ticketit it a lot, simple and objective.

I've instaled the system with sucessfuly but when i login the admin page just show: 

![logged](https://user-images.githubusercontent.com/28784054/31669039-acd5ee2e-b332-11e7-99ed-9e2d4710da8d.jpg)

If i access any page show this information, what i've done wrong in this process?

**Comment by winfieldblum** [comment]
Do you want to output your users table?

…

Regards,

Chris Winfield-Blum
Founder & CEO

[cflogo_02_150w]<http://www.changefox.com/>

How would you rate your experience with Change Fox?<http://www.changefox.com/provide-us-feedback>

**Comment by balping** [comment]
@GuilhermeBuzu Well, the screen you have above is the default dashboard that comes with laravel. You have to navigate to a ticketit-specific url, such as /tickets

**Comment by GuiRangel08** [comment]
@balping if i go to page /tickets or /tickets-admin show me this screen:

![ticket_and_ticket-admin](https://user-images.githubusercontent.com/28784054/31670553-a17dbd96-b336-11e7-9519-885e2af60193.jpg)

**Comment by GuiRangel08** [comment]
i installed again, now in the php 7 and work fine. Thx for the help.
