### ISSUE TITLE
Ticketit needs upgrade, admin should login and visit ticketit install route

### ISSUE THREAD

**Issue by learnhard** [thekordy/ticketit#409]
I have gone through all threads on this topic to no positive result. I would like to solve this or if I could revert and re-install the package?

**Comment by balping** [comment]
Sorry, it's not clear what you are asking. What error message do you get? What laravel and tiicketit versions are you on?

**Comment by learnhard** [comment]
I got; "Ticketit needs upgrade, admin should login and visit ticketit install route " error
using laravel 5.4 and the latest version of ticketit.

**Comment by thekordy** [comment]
@learnhard Have you tried to do as the message says?

**Comment by learnhard** [comment]
I dont know how... So I thought i could re-install it,  I tried to delete and the require line from the composer.json file and ran composer update, but got this error:
`Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Kordy\Ticketit\TicketitServiceProvider' not found
Script php artisan optimize handling the post-update-cmd event returned with error code 1`

**Comment by learnhard** [comment]
Then tried re-installing ticketit and got `Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
  [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from information_schema.tables where table_schema = blog and table_name = migrations)
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
  [PDOException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
Script php artisan optimize handling the post-update-cmd event returned with error code 1
Installation failed, reverting ./composer.json to its original content.` 
error

**Comment by learnhard** [comment]
I'm really confused here. Hope you can help sort things out for me. Thanks

**Comment by learnhard** [comment]
how do I do this ?
"@learnhard Have you tried to do as the message says?" @thekordy @balping @kebian @c0h1b4 @mandrakecr

**Comment by learnhard** [comment]
how do I do this ?
"@learnhard Have you tried to do as the message says?" @thekordy @balping @kebian @c0h1b4 @mandrakecr

**Comment by learnhard** [comment]
how do I do this ?
"@learnhard Have you tried to do as the message says?" @thekordy @balping @kebian @c0h1b4 @mandrakecr

**Comment by sarkkk** [comment]
When you remove your **ticketit** folder from vendor, don't forget to remove `Kordy\Ticketit\TicketitServiceProvider::class,` line from `config/app.php` as well. after that try re-installing **ticketit**. 

and Is your MySQL server is running or recheck your MySQL database credentials?
