### ISSUE TITLE
Testing v0.1.0

### ISSUE THREAD

**Issue by FusionDesign** [thekordy/ticketit#41]
What's left to do on this branch? Just battle testing or did you want me to work on some feature?

I'd like to start writing tests for coverage soon, as the project is starting to need it.

**Comment by thekordy** [comment]
I just thought to keep it for two days or less for testing, any new
features will best fit in the next releases.

**Comment by FusionDesign** [comment]
Good idea, I'll be testing tonight then thanks @thekordy

**Comment by fishmad** [comment]
How do you get the DataTables to be responsive for mobile devices like this https://www.datatables.net/blog/2014-07-16#Example

The table columns on the far right drop off to fit screen and the become a drop down with-in the current row, its very nifty, never seen anything like this before.

**Comment by FusionDesign** [comment]
Oh I can do that easy. Hang on .

**Comment by FusionDesign** [comment]
Added in v0.2.0
