### ISSUE TITLE
Method [validate] does not exist while adding category, priority and other options

### ISSUE THREAD

**Issue by sarkkk** [thekordy/ticketit#411]
Getting following error: 

(1/1) BadMethodCallExceptionMethod [validate] does not exist.
--
in Controller.php (line 82)
at Controller->__call('validate', array(object(Request), array('name' => 'required', 'color' => 'required')))in CategoriesController.php (line 46)

**Comment by balping** [comment]
Based on the other issue you opened after this, I assume you have solved this one.

**Comment by sarkkk** [comment]
yes, i have thank you .. the problem was on my part of a controller.
