### ISSUE TITLE
Changing Status and closing/reopening tickets with notes

### ISSUE THREAD

**Issue by sarkkk** [thekordy/ticketit#415]
What about providing `change status` option as a different button rather than giving it inside edit page?
And each time someone changes the status have to leave a note on his/her action (Also for closing and re-opening the ticket). 
Just a thought!

**Comment by balping** [comment]
This kind of history is going to be available in v2.

If you want custom buttons, you can just override vendor views.

**Comment by sarkkk** [comment]
Thank you, Will wait for the v2 even though I have managed to meet my requirement for now. I added new button as update status, where a user can manage status (including Reopen and close ticket) and record the history of changes with description.
![screenshot](https://user-images.githubusercontent.com/10656752/33161439-9e6446f2-d04b-11e7-92d2-3c3daa738304.png)
