### ISSUE TITLE
how can we use all the controller routes and views with current project.

### ISSUE THREAD

**Issue by amirgee007** [thekordy/ticketit#416]
hi i have installed the package and it works with default templating but i want to copy all the routes controllers views etc in my existing app bc i need to update some headings text inputs labels etc but if i done in vendor folder these changes not saved.
so that now want to copy all the existing files from vendor to my existing travel app.

how can i do this in a better way?
i tried but it seems all files need to update namespaces etc and trying from two days to find best solution how can i do this in proper file.
there is no vendor publish command etc so that all views etc move to my current views directory.

just problem is want to update routes name as well as some hading etc what is the best solution for getting this?

thanks you

**Comment by balping** [comment]
Hi!

Follow the [manual instructions](https://github.com/thekordy/ticketit#installation-manual). I think vendor publish should work then. If not, follow [this comment](https://github.com/thekordy/ticketit/issues/244#issuecomment-243228267) to customise views.

**Comment by amirgee007** [comment]
ok thanks mate
