### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by stephaneisnard** [thekordy/ticketit#417]
Hello,  
In vendor/kordy/ticketit/src/Translations/fr/lang.php  
For 'btn-create-new-ticket' and 'create-new-ticket'  
The translation must be 'Créer un nouveau ticket' ;-)  

Kind regards and thank you for this very helpful development !!

Stéphane

**Comment by stephaneisnard** [comment]
same thing for 'index-create-new-ticket' :-)

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/commit/7e03c0bcd096b0ddd39ff8580bf67e526476e3f4

Thanks
