### ISSUE TITLE
Error when submitting new ticket

### ISSUE THREAD

**Issue by azaman2204** [thekordy/ticketit#419]
Installed tickett. run successfully after created categories, priorities and users
got the following error when test by submit a ticket.
![screen shot 2017-12-23 at 11 48 38 am](https://user-images.githubusercontent.com/790857/34316747-be4855dc-e7d7-11e7-9748-2e57f3996537.png)

**Comment by balping** [comment]
Could you please attach the whole call stack that we can see what calls purifier?

**Comment by azaman2204** [comment]
[image: MailTag]Here is the full stack
ErrorException (E_WARNING)
mkdir(): No such file or directory

   -
   <https://app.mailtag.io/link-event?url=https%3A%2F%2Fgoogle.com%2Fsearch%3Fq%3DErrorException%2Bmkdir%28%29%3A%2BNo%2Bsuch%2Bfile%2Bor%2Bdirectory%26id%3D7a3e8818-e9b5-11e7-8f13-06ccf5eaaee6>

   -
   <https://app.mailtag.io/link-event?url=https%3A%2F%2Fduckduckgo.com%2F%3Fq%3DErrorException%2Bmkdir%28%29%3A%2BNo%2Bsuch%2Bfile%2Bor%2Bdirectory%26id%3D7a3e89f8-e9b5-11e7-b374-06ccf5eaaee6>

   -
   <https://app.mailtag.io/link-event?url=https%3A%2F%2Fstackoverflow.com%2Fsearch%3Fq%3DErrorException%2Bmkdir%28%29%3A%2BNo%2Bsuch%2Bfile%2Bor%2Bdirectory%26id%3D7a3e8b38-e9b5-11e7-8898-06ccf5eaaee6>

 COPY
Application frames (1)
<https://app.mailtag.io/link-event?url=http%3A%2F%2Flocalhost%3A8000%2Ftickets%23%26id%3D7a3e8c50-e9b5-11e7-8cc1-06ccf5eaaee6>
 All frames (71)
<https://app.mailtag.io/link-event?url=http%3A%2F%2Flocalhost%3A8000%2Ftickets%23%26id%3D7a3e8d54-e9b5-11e7-bf44-06ccf5eaaee6>
70
ErrorException

…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Filesystem
/
Filesystem.php
442
69

mkdir
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Filesystem
/
Filesystem.php
442
68
Illuminate
\
Filesystem
\
Filesystem

makeDirectory
…
/
vendor
/
mews
/
purifier
/
src
/
Purifier.php
201
67
Mews
\
Purifier
\
Purifier

checkCacheDirectory
…
/
vendor
/
mews
/
purifier
/
src
/
Purifier.php
67
66
Mews
\
Purifier
\
Purifier

setUp
…
/
vendor
/
mews
/
purifier
/
src
/
Purifier.php
53
65
Mews
\
Purifier
\
Purifier

__construct
…
/
vendor
/
mews
/
purifier
/
src
/
PurifierServiceProvider.php
52
64
Mews
\
Purifier
\
PurifierServiceProvider

Mews
\
Purifier
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Container
/
Container.php
749
63
Illuminate
\
Container
\
Container

build
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Container
/
Container.php
631
62
Illuminate
\
Container
\
Container

resolve
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Container
/
Container.php
586
61
Illuminate
\
Container
\
Container

make
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Application.php
732
60
Illuminate
\
Foundation
\
Application

make
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Container
/
Container.php
1195
59
Illuminate
\
Container
\
Container

offsetGet
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Support
/
Facades
/
Facade.php
159
58
Illuminate
\
Support
\
Facades
\
Facade

resolveFacadeInstance
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Support
/
Facades
/
Facade.php
128
57
Illuminate
\
Support
\
Facades
\
Facade

getFacadeRoot
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Support
/
Facades
/
Facade.php
215
56
Illuminate
\
Support
\
Facades
\
Facade

__callStatic
…
/
vendor
/
kordy
/
ticketit
/
src
/
Traits
/
Purifiable.php
19
55
Kordy
\
Ticketit
\
Models
\
Ticket

setPurifiedContent
…
/
vendor
/
kordy
/
ticketit
/
src
/
Controllers
/
TicketsController.php
220
54
Kordy
\
Ticketit
\
Controllers
\
TicketsController

store
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Controller.php
54
53

call_user_func_array
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Controller.php
54
52
Illuminate
\
Routing
\
Controller

callAction
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
ControllerDispatcher.php
45
51
Illuminate
\
Routing
\
ControllerDispatcher

dispatch
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Route.php
212
50
Illuminate
\
Routing
\
Route

runController
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Route.php
169
49
Illuminate
\
Routing
\
Route

run
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Router.php
658
48
Illuminate
\
Routing
\
Router

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
30
47
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Middleware
/
SubstituteBindings.php
41
46
Illuminate
\
Routing
\
Middleware
\
SubstituteBindings

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
45
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
44
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Auth
/
Middleware
/
Authenticate.php
43
43
Illuminate
\
Auth
\
Middleware
\
Authenticate

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
42
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
41
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Middleware
/
VerifyCsrfToken.php
67
40
Illuminate
\
Foundation
\
Http
\
Middleware
\
VerifyCsrfToken

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
39
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
38
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
View
/
Middleware
/
ShareErrorsFromSession.php
49
37
Illuminate
\
View
\
Middleware
\
ShareErrorsFromSession

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
36
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
35
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Session
/
Middleware
/
StartSession.php
63
34
Illuminate
\
Session
\
Middleware
\
StartSession

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
33
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
32
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Cookie
/
Middleware
/
AddQueuedCookiesToResponse.php
37
31
Illuminate
\
Cookie
\
Middleware
\
AddQueuedCookiesToResponse
handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
30
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
29
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Cookie
/
Middleware
/
EncryptCookies.php
59
28
Illuminate
\
Cookie
\
Middleware
\
EncryptCookies

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
27
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
26
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
102
25
Illuminate
\
Pipeline
\
Pipeline

then
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Router.php
660
24
Illuminate
\
Routing
\
Router

runRouteWithinStack
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Router.php
635
23
Illuminate
\
Routing
\
Router

runRoute
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Router.php
601
22
Illuminate
\
Routing
\
Router

dispatchToRoute
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Router.php
590
21
Illuminate
\
Routing
\
Router

dispatch
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Kernel.php
176
20
Illuminate
\
Foundation
\
Http
\
Kernel

Illuminate
\
Foundation
\
Http
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
30
19
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
barryvdh
/
laravel-debugbar
/
src
/
Middleware
/
InjectDebugbar.php
65
18
Barryvdh
\
Debugbar
\
Middleware
\
InjectDebugbar

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
17
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
16
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Middleware
/
TransformsRequest.php
30
15
Illuminate
\
Foundation
\
Http
\
Middleware
\
TransformsRequest
handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
14
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
13
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Middleware
/
TransformsRequest.php
30
12
Illuminate
\
Foundation
\
Http
\
Middleware
\
TransformsRequest
handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
11
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
10
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Middleware
/
ValidatePostSize.php
27
9
Illuminate
\
Foundation
\
Http
\
Middleware
\
ValidatePostSize
handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
8
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
7
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Middleware
/
CheckForMaintenanceMode.php
46
6
Illuminate
\
Foundation
\
Http
\
Middleware
\
CheckForMaintenanceMode

handle
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
149
5
Illuminate
\
Pipeline
\
Pipeline

Illuminate
\
Pipeline
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Routing
/
Pipeline.php
53
4
Illuminate
\
Routing
\
Pipeline

Illuminate
\
Routing
\
{closure}
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Pipeline
/
Pipeline.php
102
3
Illuminate
\
Pipeline
\
Pipeline

then
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Kernel.php
151
2
Illuminate
\
Foundation
\
Http
\
Kernel

sendRequestThroughRouter
…
/
vendor
/
laravel
/
framework
/
src
/
Illuminate
/
Foundation
/
Http
/
Kernel.php
116
1
Illuminate
\
Foundation
\
Http
\
Kernel

handle
…
/
public
/
index.php
52
0

require_once


[image: MailTag]  Sent with MailTag <undefined>

**Comment by thekordy** [comment]
Too old ticket
