### ISSUE TITLE
v0.2.0 - Create or Edit Ticket - The agent id field is required.

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#42]
The agent id field is required.

Hidden field not present or validation issue.

**Comment by FusionDesign** [comment]
is_array() was returning false because scopeAgentsLists() returns an object, not an array.

Updated method to include ->all() which converts the into an array.

**Comment by FusionDesign** [comment]
That commit should have been tagged #41

**Comment by FusionDesign** [comment]
And that should have been tagged #43. I should just got to bed. Obviously losing my mind.
