### ISSUE TITLE
During Installation: Cannot make non static method App\Models\Auth\User::isAdmin() static in class Kordy\Ticketit\Models\Agent

### ISSUE THREAD

**Issue by dinorhythms** [thekordy/ticketit#420]
Cannot make non static method App\Models\Auth\User::isAdmin() static in class Kordy\Ticketit\Models\Agent

**Comment by balping** [comment]
What PHP version are you using?

**Comment by JuanAdamuz** [comment]
Cannot make non static method App\User::isAdmin() static in class Kordy\Ticketit\Models\Agent, Got the same. Im using:
Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9

**Comment by balping** [comment]
Could you post a call stack?

**Comment by JuanAdamuz** [comment]
```php
<?php
 
namespace Kordy\Ticketit\Models;
 
use App\User;
use Auth;
 
class Agent extends User
{
    protected $table = 'users';
 
    /**
     * list of all agents and returning collection.
     *
     * @param $query
     * @param bool $paginate
     *
     * @return bool
     *
     * @internal param int $cat_id
     */
    public function scopeAgents($query, $paginate = false)
    {
        if ($paginate) {
            return $query->where('ticketit_agent', '1')->paginate($paginate, ['*'], 'agents_page');
        } else {
            return $query->where('ticketit_agent', '1');
        }
    }
 
    /**
     * list of all admins and returning collection.
     *
     * @param $query
     * @param bool $paginate
     *
     * @return bool
     *
     * @internal param int $cat_id
     */

```
Arguments
"Cannot make non static method App\User::isAdmin() static in class Kordy\Ticketit\Models\Agent"

**Comment by JuanAdamuz** [comment]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Cannot make non static method App\User::isAdmin() static in class Kordy\Ticketit\Models\Agent

**Comment by JuanAdamuz** [comment]
Any News¿?

**Comment by balping** [comment]
Sorry, I'm quite busy with other things, a PR would appreciated.

**Comment by JuanAdamuz** [comment]
I had a isAdmin method in  my User model sorry
