### ISSUE TITLE
Installer doesn't proceed if primary key of users table has different column name than id

### ISSUE THREAD

**Issue by ankitpise** [thekordy/ticketit#422]
Attempted on Laravel 5.3
Ticketid Version v0.3.10

My users table primary column is `user_id` which is also declared in `Users` model with `protected $primaryKey = 'user_id';` but installer still attempts on column `id`

**Comment by balping** [comment]
Hi,

Could you please point to the file and line number causing this?

**Comment by medmin** [comment]
Yes. I changed the "name" column of Users table to "username", and the install url (/tickets-install) throws an error.

```bash
Illuminate\Database\QueryException thrown with message "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: select `name`, `id` from `users`)"

```

**Comment by balping** [comment]
Could you include the whole call stack please?

**Comment by medmin** [comment]
i changed the username back to name

it works

so, you use name as the default.

Balázs Dura-Kovács <notifications@github.com> 于 2018年6月22日周五 15:10写道：

**Comment by hernan19182** [comment]
al cambiar el campo name de la tabla users ticketit no me reconoce el nuevo campo sigue buscando el campo name.... como puedo solucionar ese problema este es el error...

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: select `name`, `id` from `users` inner join `ticketit_categories_users` on `users`.`id` = `ticketit_categories_users`.`user_id` where `ticketit_categories_users`.`category_id` = 1 and `ticketit_agent` = 1)
