### ISSUE TITLE
Class 'App\Http\Controllers\Controller' not found

### ISSUE THREAD

**Issue by dyanakiev** [thekordy/ticketit#423]
Hello i followed the instructions but i get this error:

```
PHP Fatal error:  Class 'App\Http\Controllers\Controller' not found in /Users/xx/Sites/xx/web/vendor/kordy/ticketit/src/Controllers/InstallController.php on line 16

In InstallController.php line 16:

  Class 'App\Http\Controllers\Controller' not found

```

Running Laravel 5.4.27
 There is App\Http\Controllers\Controller..

**Comment by balping** [comment]
`composer dump-autoload`?

**Comment by dyanakiev** [comment]
Nvm found the issue, i have to change App\.. to my app name..
  Im wondering is there alternative to fix this?

**Comment by balping** [comment]
You could try aliasing: https://github.com/thekordy/ticketit/issues/401#issuecomment-336630867
