### ISSUE TITLE
showing errors after submitting  new  ticket 

### ISSUE THREAD

**Issue by sunnystark** [thekordy/ticketit#424]
Swift_TransportException (530)
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

![desktop screenshot 1](https://user-images.githubusercontent.com/14926212/34663873-178929e2-f47f-11e7-891e-d45095610ceb.png)

**Comment by balping** [comment]
Set up mailing correctly.  It's usually done by editing your .env file. If you want to disable mails, you might want to set mail driver to `log` or `array`.

**Comment by sunnystark** [comment]
thanku dear .. 

there is my .env file 


APP_NAME=Ticketit
APP_ENV=local
APP_KEY=base64:P+Gq+PeQ8YL22HGD01KTHxuC2x1/q0WOsu2FmpmK/88=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=ticket
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=



if i want to disable mails what i do exactly 


actually i'm not a programmer

**Comment by balping** [comment]
Set `MAIL_DRIVER=log`. This means all the emails will be go to a logfile, instead of being sent.

UPDATE 2018-10-14

`MAIL_DRIVER=array` should work too now.

**Comment by sunnystark** [comment]
thanks balping u such a good person :)
