### ISSUE TITLE
Error message: Class 'Yajra\DataTables\DataTablesServiceProvider' not found 

### ISSUE THREAD

**Issue by yuj1ro** [thekordy/ticketit#428]
When I try to install it with https://github.com/balping/ticketit-app I receive this error message

**Comment by balping** [comment]
I couldn't replicate this.

Does running `composer update` help?

**Comment by yuj1ro** [comment]
No it didn't 

![image](https://user-images.githubusercontent.com/5978562/35400162-fe1fa4e6-01ed-11e8-9298-d35f84f7d32e.png)

**Comment by balping** [comment]
Does that file exist in the vendor dir?

**Comment by yuj1ro** [comment]
yes 

![image](https://user-images.githubusercontent.com/5978562/35400612-2834aab4-01ef-11e8-9a42-849c3b77ca29.png)

**Comment by balping** [comment]
Could you dump your composer.lock file?

**Comment by yuj1ro** [comment]
yes 


[composer.txt](https://github.com/thekordy/ticketit/files/1664853/composer.txt)

**Comment by balping** [comment]
For some reason you have Laravel Datatables v6.24.1 installed, however v8 is required for L5.4 Try forcing v8 to be installed. I guess some of the requirements for v8 is not met. https://github.com/yajra/laravel-datatables

**Comment by yuj1ro** [comment]
Find the solutions thanks
