### ISSUE TITLE
Emails do not send.

### ISSUE THREAD

**Issue by FusionDesign** [thekordy/ticketit#43]
unserialize(): Error at offset 0 of 162 bytes

Error whenever sending emails. All templates contain inline PHP unserialize() commands. I have no idea the purpose of these.

**Comment by FusionDesign** [comment]
I'm not closing this just yet. @thekordy why unserialize?

**Comment by thekordy** [comment]
Please refer to #8

**Comment by FusionDesign** [comment]
Ah makes sense. I wonder why status_notification is the only unserialize that doesn't work? It only doesn't work when changing status using the Complete Ticket button on v0.2.0

**Comment by FusionDesign** [comment]
Regardless, I re-implemented it into v0.2.0 until we can fix that one item.
