### ISSUE TITLE
Settings lang unique

### ISSUE THREAD

**Issue by lparolari** [thekordy/ticketit#435]
Hi,
i was watching your db schema and i noticed that the settings table has the lang column, which is used to translate some settings, so if i want to translate it in italian i have to put in the lang column "it".

Now, my question is: **why the lang column has `unique` option**? Why i don't have to specify for each row if it needs to be translated or not?

Thanks!

**Comment by balping** [comment]
Probably it would be a bug if it was used. But that column isn't used anywhere in the codebase, so just ignore. I don't know what the original intention was.

**Comment by lparolari** [comment]
Okay, thank you!
