### ISSUE TITLE
Install Issue - FatalThrowableError: Call to a member function connection() on null

### ISSUE THREAD

**Issue by pcartagena74** [thekordy/ticketit#437]
I'm running Laravel 5.4 with an existing application with users, etc.

1. I ran composer require kordy/ticketit:0.* which completed without issue.
2. I added Kordy\Ticketit\TicketitServiceProvider::class, to config/app.php
3. I was able to get to project-url/tickets-install and I can verify that the migrations were run and there are 8 ticketit* tables that were created.

However, the routes: project-url/tickets and /tickets-admin result in the Exception above.

Please let me know what other information you would need in order to troubleshoot this.  I look forward to actually using this ticketing system!

`
(1/1) FatalThrowableErrorCall to a member function connection() on null
--
in Model.php (line 1058)
at Model::resolveConnection(null)in Model.php (line 1024)
at Model->getConnection()in Model.php (line 859)
at Model->newBaseQueryBuilder()in Model.php (line 818)
at Model->newQueryWithoutScopes()in Model.php (line 802)
at Model->newQuery()in Model.php (line 346)
at Model::all()in Setting.php (line 53)
at Setting::Kordy\Ticketit\Models\{closure}()in Repository.php (line 291)
at Repository->remember('ticketit::settings', 60, object(Closure))in CacheManager.php (line 305)
at CacheManager->__call('remember', array('ticketit::settings', 60, object(Closure)))in Facade.php (line 221)
at Facade::__callStatic('remember', array('ticketit::settings', 60, object(Closure)))in Setting.php (line 54)
at Setting::Kordy\Ticketit\Models\{closure}()in Repository.php (line 291)
at Repository->remember('ticketit::settings.main_route', 60, object(Closure))in CacheManager.php (line 305)
at CacheManager->__call('remember', array('ticketit::settings.main_route', 60, object(Closure)))in Facade.php (line 221)
at Facade::__callStatic('remember', array('ticketit::settings.main_route', 60, object(Closure)))in Setting.php (line 69)
at Setting::grab('main_route')in TicketitServiceProvider.php (line 195)
at TicketitServiceProvider->boot()
at call_user_func_array(array(object(TicketitServiceProvider), 'boot'), array())in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php (line 87)
at BoundMethod::callBoundMethod(object(Application), array(object(TicketitServiceProvider), 'boot'), object(Closure))in BoundMethod.php (line 31)
at BoundMethod::call(object(Application), array(object(TicketitServiceProvider), 'boot'), array(), null)in Container.php (line 539)
at Container->call(array(object(TicketitServiceProvider), 'boot'))in Application.php (line 788)
at Application->bootProvider(object(TicketitServiceProvider))in Application.php (line 771)
at Application->Illuminate\Foundation\{closure}(object(TicketitServiceProvider), 12)
at array_walk(array(object(EventServiceProvider), object(LogServiceProvider), object(RoutingServiceProvider), object(ServiceProvider),object(TrustedProxyServiceProvider), object(FlysystemServiceProvider), object(MailTrackerServiceProvider), object(AgentServiceProvider),object(HtmlServiceProvider), object(DataTablesServiceProvider), object(DateServiceProvider), object(PurifierServiceProvider), object(TicketitServiceProvider),object(AirbrakeServiceProvider), object(AuthServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider),object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FormRequestServiceProvider), object(FoundationServiceProvider),object(NotificationServiceProvider), object(PaginationServiceProvider), object(SessionServiceProvider), object(ViewServiceProvider),object(ExcelServiceProvider), object(PhantomJsServiceProvider), object(MediableServiceProvider), object(ActivitylogServiceProvider),object(LinkCheckerServiceProvider), object(RefererServiceProvider), object(EntrustServiceProvider), object(CashierServiceProvider),object(AppServiceProvider), object(AuthServiceProvider), object(EventServiceProvider), object(RouteServiceProvider), object(MailServiceProvider),object(QueueServiceProvider), object(TranslationServiceProvider), object(CacheServiceProvider)), object(Closure))in Application.php (line 772)
at Application->boot()in BootProviders.php (line 17)
at BootProviders->bootstrap(object(Application))in Application.php (line 208)
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php (line 162)
at Kernel->bootstrap()in Kernel.php (line 146)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

`

**Comment by balping** [comment]
Is caching set up properly?

https://laravel.com/docs/5.4/cache

**Comment by pcartagena74** [comment]
I have the default cache setup.

**Comment by balping** [comment]
What if you clear the cache? This seams to be cache-related.

**Comment by pcartagena74** [comment]
Ok.  So I commented out the line:          Kordy\Ticketit\TicketitServiceProvider::class, so that I could run:
`php artisan cache:clear`

It cleared successfully.  I uncommented the line above and still get the error.

**Comment by pcartagena74** [comment]
I upgraded to Laravel 5.5 and changed nothing else.  TicketIt routes now resolve correctly.
