### ISSUE TITLE
Unable to delete Status in admin

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#44]
Click delete - I get the JS confirmation - do you really want to delete ? hit yes then nothing happens.

No obvious errors,

**Comment by fishmad** [comment]
Update it will delete but only the last Status in the list - one at the bottom.

I was eventually able to delete all Statuses by deleting from the bottom up.

**Comment by FusionDesign** [comment]
Duplicated. On it.

**Comment by fishmad** [comment]
Same bug applies to Categories and Priorities.

**Comment by FusionDesign** [comment]
On it.

**Comment by FusionDesign** [comment]
Fixed!
