### ISSUE TITLE
Add Locations to Tickets

### ISSUE THREAD

**Issue by ghost** [thekordy/ticketit#442]
Hello,
My company has different branches in different places and I would like to identify from which branch the ticket is being requested. Could this improvement be implemented? Another question: is it possible to integrate with the active directory? #

**Comment by balping** [comment]
Feel free to fork and implement anything your company needs. I don't understand the second question. What do you mean by active directory?

**Comment by thekordy** [comment]
I guess you mean integrating the authentication/login with active directory users, if so, you just need to integrate Laravel with LDAP, there are multiple packages for that, but I haven't tried any of them.
see https://laracasts.com/discuss/channels/laravel/how-to-join-laravel-54-to-windows-active-directory-server?page=1
and
https://laracasts.com/discuss/channels/laravel/authenticating-with-active-directory

about the first part of your question, to add more information to the ticket, such as the branch name or something, you will need add a new field to the ticket database (migration to alter ticketit table) and the  view files (Blade template at resources/view/vendor/ticketit).

**Comment by Eaglemcz** [comment]
Hy fellows, i have made some improvements on our app, by the way, very good aplication, powerful and answers to most of my needs in the IT demands and tickets.

**Improvements:**

1. **pt_BR Language improvemments**
2. **Added places class to the project**

@balping and @thekordy, may i send the project folder for validation? I though most of us will like this update.

**Comment by balping** [comment]
@Eaglemcz Could you send a pull request instead? What do you mean by "places class"?

**Comment by Eaglemcz** [comment]
Pull request sent, i mean table, sry!

**Comment by Eaglemcz** [comment]
Hy @balping and @thekordy, my pull request must have only files that i have updated/created instead all project folder, right?

**Comment by balping** [comment]
The files you updated or created under `ticketit/src`

**Comment by Eaglemcz** [comment]
Done, files updated / uploaded
