### ISSUE TITLE
1071 Specified key was too long

### ISSUE THREAD

**Issue by oden08** [thekordy/ticketit#445]
Please forgive if handled elsewhere but I ran into an issue and wanted to drop it here in case anyone else had the same issue.

Running newest release of xampp for Windows which has mariadb 10.1.30.  Turns out in Mariadb version < 10.2 or Mysql version < 5.7 the prefix limitation in innodb is 767 bytes.  This causes a failure when running "php artisan ticketit:install" of " SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))" --and a few more errors.

To get the install working I did the following:

Added "use Illuminate\Support\Facades\Schema;" 

and

    public function boot()
    {
        //
		Schema::defaultStringLength(191);
    }

to my AppServiceProvider.php located in \app\Providers\

**Comment by balping** [comment]
Thank you. This is a general bug in Laravel 5.4+, it can be handled just as you did.

Reference: https://laravel-news.com/laravel-5-4-key-too-long-error/

The same bug was encountered in these issues: https://github.com/thekordy/ticketit/issues/344 https://github.com/thekordy/ticketit/issues/332
