### ISSUE TITLE
Tried almost everything but still get view not found error

### ISSUE THREAD

**Issue by ThistleApps** [thekordy/ticketit#449]
I have attempted to resolve this issue with suggestions from various posts but cannot resolve.  Keep getting error that "View [index] not found. (View: /home/forge/MyProject.com/vendor/kordy/ticketit/src/Views/index.blade.php)

The index file is definitely in the production directory.

I did note however that if I try to change the MySQL settings table template field value to something other than index the error message won't reflect that change.  So the error is always looking for index.  But if I change the MySQL field to say "home" it still states it cannot find "index".  Makes me think there is a problem somewhere else.

**Comment by balping** [comment]
Try clearing the cache. `php artisan cache:clear`

You should do this after changing some config in the database (and not via the admin interface) every time.

**Comment by ThistleApps** [comment]
Thanks balping.  That seems to have resolved.  I had tried that before but I suppose I used the wrong value when updating the database manually.
