### ISSUE TITLE
Hardcoded language in external javascript - localization

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#45]
DataTables has some hard coded language reference in the external bootstrap Javascript.

Not sure how to tackle these, so just want to park it for now.

![capture](https://cloud.githubusercontent.com/assets/12012101/10280274/b36f68f6-6bb7-11e5-96ec-5fbbaf2497d1.PNG)
http://cdn.datatables.net/plug-ins/505bef35b56/integration/bootstrap/3/dataTables.bootstrap.js
	"oLanguage": {
		"sLengthMenu": "_MENU_ records per page"
	}

**Comment by FusionDesign** [comment]
Oh that's easy. I'll push an update.

**Comment by FusionDesign** [comment]
That's the old API anyway, we are using the new one.

**Comment by FusionDesign** [comment]
Fixed in v0.2.0, reference #46
