### ISSUE TITLE
ticketit for admins only?

### ISSUE THREAD

**Issue by yocmen** [thekordy/ticketit#450]
Can i use this for a ticket system just for my role admins (entrust) and they can send the ticket directly to another admin instead of an agent? thanks in advance, i really like this package.

**Comment by balping** [comment]
You can create a custom middleware protecting all ticketit routes, if this is what you're asking.

**Comment by yocmen** [comment]
i mean the ticket system will be used for my admins(entrust) and they can open ticket for a specific or group of another admins(entrust) so the agent function will be disable on this example, will be directs tickets is some way, they will need select another admin or several admins when they create the ticket.

**Comment by thekordy** [comment]
I don't think this is possible in current version.
