### ISSUE TITLE
how to change user models 

### ISSUE THREAD

**Issue by loveunCG** [thekordy/ticketit#456]
namespace Kordy\Ticketit\Models;

use App\Models\UsersModel as User;
use Auth;

class Agent extends User
{
    protected $table = 'tbl_users';
.....
}
I have changed User model on agent model
but while installing ticket module, has error maybe not changed User model 
how about that thanks

**Comment by balping** [comment]
Since `Agebt` extends `User`, it is enough to update the table property o `User`, you don't have to touch `Agent`. But if you use a different table, you might want to be careful migrations.

**Comment by loveunCG** [comment]
thanks for your answer
now I am integrating this ticket package to existing project
so I gona change User model (that is Auth model )
 my auth model is app\Models\UsersModel
but there is no users table only tbl_users

**Comment by loveunCG** [comment]
and I cannt publish this config/Ticketit.php
