### ISSUE TITLE
🎉  🎆 500 stars celebration 🎆  🎉

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#463]
![500](https://user-images.githubusercontent.com/5840038/41320824-a6d21324-6ea1-11e8-8552-66b0ce408619.png)

---

To celebrate this achievement, today I released v0.4.0 that comes with bootstrap 4 support (bootstrap 3 is still the default).

A new version of the [quick installer](https://gitlab.com/balping/ticketit-app)  is also released, that is compatible with the latest Laravel 5.6.25 (the default Laravel installation now comes with Bootstrap 4).

**Comment by thekordy** [comment]
Great work @balping, Thanks. And big thanks to the awesome open-source community
