### ISSUE TITLE
API Routes

### ISSUE THREAD

**Issue by krishnakanthpps** [thekordy/ticketit#464]
Firstly great work. 

I would love to integrate this into my existing barebones Laravel App. How do I set this up in such a way that my app sends data to ticketit via API? 

I want my system to send data to create a ticket via API and that tickets be created and assigned to agents automatically. In other words, user agents would not be creating any tickets, but would just be working on solving the tickets.

What changes do I need to make where to implement the above functionality?

Thank you in advance.

**Comment by balping** [comment]
See the store method on [TicketsController](https://github.com/thekordy/ticketit/blob/0.2/src/Controllers/TicketsController.php) 

You can copy that code and use it elsewhere with changes you want.

**Comment by rahulazm** [comment]
> Firstly great work.
> 
> I would love to integrate this into my existing barebones Laravel App. How do I set this up in such a way that my app sends data to ticketit via API?
> 
> I want my system to send data to create a ticket via API and that tickets be created and assigned to agents automatically. In other words, user agents would not be creating any tickets, but would just be working on solving the tickets.
> 
> What changes do I need to make where to implement the above functionality?
> 
> Thank you in advance.

Hi ,

As I am also lookin for API , just wanted to check if you have created API and willing to share

Thanks,
Rahul

**Comment by krishnakanthpps** [comment]
Nope. I havent worked on this

**Comment by rahulazm** [comment]
May I know your suggestion on any other ticketing PHP based free opensource
application with API
