### ISSUE TITLE
Class not found in a ticket commented

### ISSUE THREAD

**Issue by BlackCheems** [thekordy/ticketit#468]
I got this error when i ran  comment ticket
Anyone knows where i need to change that name?

My correct app name is "cctapp"

![captura](https://user-images.githubusercontent.com/36548555/41739620-3e3540aa-755b-11e8-849f-beb60e8f0b0a.PNG)

**Comment by balping** [comment]
Use aliasing, as described in [this comment](https://github.com/thekordy/ticketit/issues/401#issuecomment-336630867).
