### ISSUE TITLE
Settings and User dropdowns do not work after installation

### ISSUE THREAD

**Issue by tmlight** [thekordy/ticketit#469]
Hi, I did a fresh install and completed without any errors. But when I go into mysite/tickets the settings and User dropdowns do not work 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/40670757/42048442-eb667b2a-7b20-11e8-9eec-6d12b10d7b31.png">

<img width="318" alt="image" src="https://user-images.githubusercontent.com/40670757/42048465-fdbac9e8-7b20-11e8-82c5-16552c1707f3.png">

Any help will be much appreciated. I selected -  another option in the master template layout during installation and gave the path to app.blade.php [which was modified to match the example in the installation instructions]

**Comment by balping** [comment]
jquery is probably not loaded correctly.

**Comment by tmlight** [comment]
That works! Thank u so much.
