### ISSUE TITLE
Unable to see active tickets

### ISSUE THREAD

**Issue by tmlight** [thekordy/ticketit#470]

**Comment by tmlight** [comment]
I have managed to install and run the ticketit app. I am able to create tickets but they do not show in the active tickets:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/40670757/42086733-a5b74fa0-7bb1-11e8-9541-714e43ca2c2c.png">

**Comment by balping** [comment]
Check the  devtools console to get an error message

**Comment by tmlight** [comment]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/40670757/42103468-d1edf116-7be6-11e8-8881-3467b4321d72.png">

**Comment by tmlight** [comment]
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/40670757/42106808-eb382cac-7bf2-11e8-81c4-79b2c29f09aa.png">

**Comment by tmlight** [comment]
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/40670757/42106882-2719d450-7bf3-11e8-8b33-3171e35cd627.png">

**Comment by tmlight** [comment]
Managed to resolve - bootstrap was not properly installed; installed using npm - ok now
