### ISSUE TITLE
What do I really need to install?

### ISSUE THREAD

**Issue by antvet** [thekordy/ticketit#472]
Goodmorning,

I would like to install tecketit on my server but I never used Lavarel before. So according to the readme, I need to do the basic install of lavarel but what does _Users table_ means? Do I need to do all the steps of the "Authentication" documentation? Same for Laravel email configuration, which steps do I need to do from the linked page of the official doc? Only the "Sending Mail" or "Rendering Mailables" too?

Thanks for your help.

EDIT: Do I need to install MySQL during the basic install, too?

**Comment by balping** [comment]
If you're unfamiliar with Laravel, use our quick install package: https://gitlab.com/balping/ticketit-app

It will perform every necessary task and ask questions when needed.

**Comment by antvet** [comment]
Thanks a lot. So I just need to [install composer](http://www.bravo-kernel.com/2014/08/how-to-install-composer-on-debian/) for this, right?
EDIT: and MySQL, of course

**Comment by balping** [comment]
Yes, you'll need composer. MySQL is not strictly necessary, but recommended. It could work with sqlite too.

**Comment by antvet** [comment]
Thank you for your answers.
