### ISSUE TITLE
Changing the Auth User attribute 'name' to 'email_address'

### ISSUE THREAD

**Issue by talahkz** [thekordy/ticketit#474]
Is it possible to make ticketit system use the attribute 'email_address' instead of 'name' throughout it's front interface instead of going through every blade file and changing "->name" to "->email_address"?

I only ask because i do not have the 'name' column in my User table, i split it into first_name and second_name and the uid is the email address, on the front end of TicketIt the name is empty everywhere.

I would also love to hear any alternative solutions anyone may have, thanks.

**Comment by balping** [comment]
Please see #406. I can't really add anything to what's said there.
