### ISSUE TITLE
Ticket was auto assigned to Admin who is not the Agent in Category

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#48]
I have two Agents Joined to a Category (neither of them are the Admin) DB User #3 and #4
I logged in as a standard User DB User #2 and created a new a ticket.
The ticket was auto allocated to the Admin instead of my Agents.

I then logged in as Admin (DB User #1) with intent to re-assign ticket but the ability to Edit ticket is not available to Admin (possibly because he's not assigned to Category), however the Admin can add Comments or Delete the Ticket just not Edit it.

This also means I can't edit the ticket at all because Admin owns it and no other Agent knows it exists.

Also in the DataTable under the Agent table Heading the name of the person who submitted the ticket shows up and not the Assigned Agent not sure if you intended this to be the ticket owner or agent.
![capture](https://cloud.githubusercontent.com/assets/12012101/10282350/0ca95d1a-6bc6-11e5-8635-7c77e9788696.PNG)

Perhaps it should have a column for both 'ticket owner' and 'assigned agent'

Also I deleted all the tickets as Admin but they are still in the Tickets Table in Database.

**Comment by FusionDesign** [comment]
I'll look into this tonight after work :)
