### ISSUE TITLE
Ticketit tickets list not optimized for mobile

### ISSUE THREAD

**Issue by GelLiNN** [thekordy/ticketit#482]
When I visit ticketit from my mobile device, the list is not horizontally scrolling and is instead overflowing.  Is this supposed to happen automatically?  If yes, what can I do to fix this, or otherwise optimize ticketit for smartphone use?

![ticketit](https://user-images.githubusercontent.com/11727088/43556117-f46ed210-95b2-11e8-84f3-1e8f6b37a9ca.png)

**Comment by balping** [comment]
Thanks for reporting. Fix released.
