### ISSUE TITLE
Can't install on Laravel 5.6

### ISSUE THREAD

**Issue by flexsingit** [thekordy/ticketit#483]
After installing via composer using the command : composer require 'kordy/ticketit:0.*'

We are having the below error 
![issue](https://user-images.githubusercontent.com/25687998/43699182-5a95425c-996b-11e8-91fe-1a523822dcb2.png)

Any help will be highly appreciated.

FYI , we are using laravel 5.6

**Comment by balping** [comment]
Somehow you installed an old version. This bug was fixed more than 2.5 years ago! https://github.com/thekordy/ticketit/commit/bd4c8f96635bdff81019dd161ce0ea6bb2dc9ebd

Try to require `0.4.*`

**Comment by flexsingit** [comment]
Thanks for providing the information on the same. 

I tried the same however still i am facing another issue as below : 


![issue_persist](https://user-images.githubusercontent.com/25687998/43715042-c02bd8e8-999c-11e8-8484-a27125a414ef.png)

**Comment by flexsingit** [comment]
Yes this worked!
