### ISSUE TITLE
Error pos installation

### ISSUE THREAD

**Issue by Eaglemcz** [thekordy/ticketit#484]
Hi there,

after installation i am getting this error message when trying to login:

The requested URL /chamados/public/login was not found on this server.

**Comment by balping** [comment]
Please read through this on how to setup http server correctly: https://laravel.com/docs/5.6/installation

The url  should't include `public`, as that should be the root.



>#### Public Directory
> 
> After installing Laravel, you should configure your web server's document / web root to be the `public` directory. The `index.php` in this directory serves as the front controller for all HTTP requests entering your application.


> #### Apache
> 
> Laravel includes a `public/.htaccess` file that is used to provide URLs without the `index.php` front controller in the path. Before serving Laravel with Apache, be sure to enable the `mod_rewrite` module so the `.htaccess` file will be honored by the server.
> 
> If the `.htaccess` file that ships with Laravel does not work with your Apache installation, try this alternative:
> 
>     Options +FollowSymLinks -Indexes
>     RewriteEngine On
> 
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^ index.php [L]

**Comment by Eaglemcz** [comment]
Tnx @balping for helping me  solving this issue, very helpful, but it only worked when edited the apache's .htaccess. editting the folowing lines:

Find the following code inside the editor:

> `<Directory /var/www/>` <br>
>  ` Options Indexes FollowSymLinks` <br>
>  ` AllowOverride None` <br>
>  `Require all granted` <br>
> `</Directory>` <br>

And change to:

> `<Directory /var/www/>` <br> 
>     `Options Indexes FollowSymLinks` <br>
>     `AllowOverride All` <br />
>     `Require all granted` <br>
> `</Directory>` <br>

After that restart the Apache server.

> `#systemctl restart httpd.service`

After some googling i found this on holly [stackoverflow](https://stackoverflow.com/questions/28242495/laravel-the-requested-url-was-not-found-on-this-server)
