### ISSUE TITLE
Run another ticketit as a 2nd set within my laravel app

### ISSUE THREAD

**Issue by GelLiNN** [thekordy/ticketit#485]
Hi I have been running ticketit for work-orders and I'm pleased with it.  I would like to run a separate copy of everything in the same UI, for Issues instead of Work-Orders.  The way I'm expecting it to go is to just have an Issues link in my nav bar that links to this second set of tickets.

Currently I have a 'Work-Orders' link in my nav bar which just takes you to <url>/tickets, how should I do this with the new 'Issues' link?
![buildingintellect](https://user-images.githubusercontent.com/11727088/43867890-fc08beec-9b1f-11e8-9a84-bb1d42c58e92.png)

**Comment by balping** [comment]
You could create create a category for that purpose. Then you could create new routes that point to a custom controller that extends `TicketsController` and filters to that specific category.

Relevant parts of code to help you get started:

https://github.com/thekordy/ticketit/blob/f774e435022e6a11acfb26a06ef9c872eef61c44/src/routes.php#L7-L10

https://github.com/thekordy/ticketit/blob/f774e435022e6a11acfb26a06ef9c872eef61c44/src/Views/bootstrap4/index.blade.php#L27

https://github.com/thekordy/ticketit/blob/f774e435022e6a11acfb26a06ef9c872eef61c44/src/Controllers/TicketsController.php#L31

https://github.com/thekordy/ticketit/blob/f774e435022e6a11acfb26a06ef9c872eef61c44/src/Controllers/TicketsController.php#L153-L158

**Comment by GelLiNN** [comment]
So I have the UI showing the issues nav link, and when I go to the issues page it looks exactly like the work-orders page.  How do I add this filter for certain category?  Will the filter go in my IssuesController?
![issues1](https://user-images.githubusercontent.com/11727088/43870130-e49d670c-9b2a-11e8-8a46-2ecead023ca1.png)
![issues2](https://user-images.githubusercontent.com/11727088/43870131-e4bb1144-9b2a-11e8-8dda-d2a94f1d6714.png)

**Comment by balping** [comment]
Yes. You should override the data method. You could add the filter around here:

https://github.com/thekordy/ticketit/blob/f774e435022e6a11acfb26a06ef9c872eef61c44/src/Controllers/TicketsController.php#L61

A simple `where` would do it.

**Comment by GelLiNN** [comment]
Thanks for the direction, Balping!  I have added the where after the select using the 'category' alias.  I also put a simple echo at the top of the data override to make sure my override is getting called.  But the application seems to still be using the original controller data method because I'm not seeing my echo and the filter doesn't work.
Any ideas?
![where](https://user-images.githubusercontent.com/11727088/43913664-8cc1c6e6-9bba-11e8-8d73-5bcd6b5ec58c.png)

**Comment by balping** [comment]
Is your own custom routes file set up properly (ie does that url point to your custom controller)? Also, you'll need to use the category id in the where filter.
