### ISSUE TITLE
Deploying TicketIT in sub domain

### ISSUE THREAD

**Issue by Gugulethu-Nyoni** [thekordy/ticketit#486]
Hi there.

What a powerful ticketing packaging this is.

I'm running into problems trying to deploy ticketit into a subdomain. On my localhost the app works fine. So I created a subdomain. helpdesk.example.com 

I also moved the contents of public into the the app root and updated index.php accordingly.

These are the errors I'm getting. 

```

[10-Aug-2018 06:35:10 UTC] PHP Parse error:  syntax error, unexpected '?' in /home/casecore/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233
[10-Aug-2018 06:35:18 UTC] PHP Parse error:  syntax error, unexpected '?' in /home/casecore/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233
```

On the front end when i go helpdesk.example.com/login I get this error:

```
This page isn’t working
helpdesk.casecore.net is currently unable to handle this request.
HTTP ERROR 500

```

Kindly help

**Comment by balping** [comment]
Is the PHP version up to date?

**Comment by Gugulethu-Nyoni** [comment]
Thanks Balping you are a star. I needed to upgrade my PHP version. Thanks again.  All good now except that when in tickets-admin/ and go to settings->agents (tickets-admin/agent) I get this error:

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select count(*) as aggregate from `users` inner join `ticketit_categories_users` on `users`.`id` = `ticketit_categories_users`.`user_id` where `ticketit_categories_users`.`category_id` = 4 and `id` = 97) (..../vendor/kordy/ticketit/src/Views/admin/agent/index.blade.php)

I'm quite lost here kindly help. 

Million thanks.

**Comment by balping** [comment]
I think you should update ticketit too. That file you referenced doesn't exists in the newest release.

**Comment by shuvoenr** [comment]
I face problem like this
```
QueryException in Connection.php line 770:
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_id' in where clause is ambiguous (SQL: select count(*) as aggregate from (select '1' as `row_count` from `ticketit` inner join `users` on `users`.`id` = `ticketit`.`user_id` inner join `ticketit_statuses` on `ticketit_statuses`.`id` = `ticketit`.`status_id` inner join `ticketit_priorities` on `ticketit_priorities`.`id` = `ticketit`.`priority_id` inner join `ticketit_categories` on `ticketit_categories`.`id` = `ticketit`.`category_id` where `user_id` = 3 and `completed_at` is null) count_row_table)
```

That was solved by changing code code like this : 
File : vendor/kordy/ticketit/src/Models/Ticket.php

**From**
   ```
 public function scopeUserTickets($query, $id) {
        return $query->where('user_id', $id);
    }
```
**To**
   ```
 public function scopeUserTickets($query, $id) {
        return $query->where('ticketit.user_id', $id);
    }
```

**Comment by thekordy** [comment]
@shuvoenr thanks for sharing the solution, but as a recommendation, don't edit the source code as it might be overwritten with the updates.
