### ISSUE TITLE
Email Not Working

### ISSUE THREAD

**Issue by KareemAdams** [thekordy/ticketit#488]
Hi there,

First, I'd like to say Ticketit is a job well done!

I'm trying to set it up at my office for ticketing logging, while all went well - the email sending part doesn't seem to be working.

I'm currently running on Laravel 5.6.33.

To add to that, I've set up .env in different ways with smtp, sendmail nothing seem to be working. Same settings I used on my Laravel 4.* is sending email but not on this.

**I get this error:** 

Swift_TransportException
Process could not be started ['C:\apps\laragon\bin\sendmail' is not recognized as an internal or external command, operable program or batch file. ]

Process could not be started ['C:\apps\laragon\bin\sendmail' is not recognized as an internal or external command,\r\n operable program or batch file.\r\n]

Please assist.

**Comment by balping** [comment]
Sorry, but this has very little to do with Ticketit directly. Please try to seek help on SO or some Laravel forum on how to setup sendmail with Laravel under windows.
