### ISSUE TITLE
v 0.2.0 Unable to change ticket status - Validation issue

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#49]
Try to Edit a ticket and change status from Open to Assigned (Modal window)  - Validation

The subject field is required.
The content field is required.

![capture](https://cloud.githubusercontent.com/assets/12012101/10296994/b2912430-6c19-11e5-8076-5fd0425a2ac2.JPG)

**Comment by thekordy** [comment]
In 'tickets/edit.blade.php'
```php
@if(Kordy\Ticketit\Models\Agent::isAdmin())
    <div class="form-group">
        {!! Form::text('subject', $ticket->subject, ['class' => 'form-control', 'required']) !!}
    </div>
    <div class="form-group">
        {!! Form::textarea('content', $ticket->content, [
            'class' => 'form-control', 'rows' => '5', 'required'
        ]) !!}
    </div>
@endif
```

Do we need to restrict editing subject and body to only admins? or to open it for agents as well? or to make it configurable?

**Comment by fishmad** [comment]
I would think by default it should be Locked to Admin only.

Add new config setting to admin categories - Allow Agent to modify Subject and Body?: True/False

**Comment by thekordy** [comment]
>Allow Agent to modify Subject and Body?: True/False
I agree, I have to get some sleep now, but I will do it by tomorrow.

**Comment by FusionDesign** [comment]
@thekordy we are doing far too much coding with no relationships defined in our migrations. When a Status is deleted, all tickets with that status should also be deleted. Likewise, if a user is deleted, all tickets for that user should also be removed.

I'm am going to make a PR around this issue. We can discuss thoughts there! :)

**Comment by thekordy** [comment]
@FusionDesign I don't see it right to delete all tickets if you delete a status, but I agree about putting some restrictions and mass moving option.. an example of the relationship restriction:
1. you are about deleting a status that is assigned to many tickets, please move them first to another status in order to be able to delete this status
2. you are about deleting an agent whom is assigned to many tickets, please assign them first to another agent in order to be able to delete this status

**Comment by fusiondesign** [comment]
Right, a relationship will give us that error to "catch"

**Comment by thekordy** [comment]
@fishmad @FusionDesign  Kindly be informed that v0.1.0 branch became "master" branch

**Comment by fusiondesign** [comment]
We can at least define ->onDelete('cascade') on the pivot table. All other foreign keys will allow us to throw an Exception like "Cannot delete Status. Please either rename or change the status of existing tickets. If you would like to set all existing tickets to Status ID "insert permanent_status_id from config" and continue deletion, please press Replace.

Right now.. if you delete a status, category, or priority for which an existing ticket belongs to, you'll get errors and not be able to load Ticket index.

**Comment by thekordy** [comment]
@FusionDesign .. Good point and I agree with you

**Comment by fishmad** [comment]
Seem to have a new bug in v0.2 - Change ticket Status

```
ErrorException in 0a3d27e7393bc2470f628f697bdc02fb line 1:

unserialize(): Error at offset 0 of 175 bytes (View: C:\OneDrive\vendor\kordy\ticketit\src\Views\emails\status_notification.blade.php)
```

And line one is:
`<?php $notification_owner = unserialize($notification_owner); ?>`

**Comment by fusiondesign** [comment]
I've had it forever, I just removed the unserialize methods from status_notification and it worked fine. I still have no idea what this error means.

**Comment by thekordy** [comment]
The error might be related to the data that is being serialized in first place, so we need to debug what is being serialized, would you please get dump of $notification_owner? 

``` php
$notification_owner = \Auth::user();
```

in Controllers/NotificationsController

``` php
 public function ticketStatusUpdated(Ticket $ticket, Ticket $original_ticket)
    {
        $notification_owner = \Auth::user();
        $template = "ticketit::emails.status_notification";
        $data = [
            'ticket' => serialize($ticket),
            'notification_owner' => serialize($notification_owner),
            'original_ticket' => serialize($original_ticket),
        ];
```

**Comment by thekordy** [comment]
The problem because there was no serialize in the first place :)

``` php
$data = [
            'ticket' => $ticket,
            'notification_owner' => $notification_owner,
            'original_ticket' => $original_ticket,
        ];
```

it should be now fixed
