### ISSUE TITLE
Separate admin table

### ISSUE THREAD

**Issue by SargisBeglaryan** [thekordy/ticketit#494]
I have 2 tables on my project. Users - for users and Admins - for admin panel. So can i use this package with two tables instead Users

**Comment by balping** [comment]
You need to use the users table. An extra column is going to be created indicating whether a user is a ticketit admin or not. You can use the admin table elsewhere in your application though.

**Comment by SargisBeglaryan** [comment]
Yeah I saw it. I mean about two new columns on Users table. But I don't have admins on Users table. There are on Admins table with different roles )) 
And I find another issue too. I get error on template($master). 
I am using Auth but my template is not Laravel Auth default template. My structure is another and $master can't found it.
