### ISSUE TITLE
Want to add as a Package or Module. So, at every new setup not to require in composer.json require section

### ISSUE THREAD

**Issue by saurabhstact** [thekordy/ticketit#496]

**Comment by balping** [comment]
Could you elaborate? I don't really understand you. This is a package already.

**Comment by saurabhstact** [comment]
> Could you elaborate? I don't really understand you. This is a package already.

Thank you for reply, Yes, you are right it is a package. I want to use it in my laravel application and also want to customize it as per my needs. How can I do it ? because I want to use it on my repository So, that whenever I want to setup it on new system it show all the changes and not download code from your repository. Can you please suggest.

**Comment by CallumCarmicheal** [comment]
Hello @saurabhstact I'm going to assume you have yet to figure out a solution to this or have already so i will be leaving this for future reference. 

I needed to do the exact same thing a little while ago, to do that i had created a new folder called "packages" where i would store all of my modified versions of vendor based packages and then modified the `composer.json` file to add ```"Kordy\\Ticketit\\": "packages/kordy/ticketit",``` into my psr-4 section of autoload.

Like this: 
```json
{
	...
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            "Kordy\\Ticketit\\": "packages/kordy/ticketit",
            "": "app/"
        }
    },
	...
}
```

This should now allow you to autoload from that directory without having to worry about composer updating the wrong package.
