### ISSUE TITLE
Ticket is not displayed 

### ISSUE THREAD

**Issue by MartyHemart** [thekordy/ticketit#499]
Hello, after installing Ticketit, everything works except the display of tickets, the error of my console is as follows: 

`ReferenceError: jQuery is not defined[En savoir plus]  datatables.min.js:17:124
	<anonyme> http://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js:17:124
	<anonyme> http://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js:17:2
ReferenceError: $ is not defined[En savoir plus]  tickets:181:6
	<anonyme> http://10.148.193.127/tickets:181:6`

I tried to modify the cdn but none of them work ...

Can you help me please
Sincerely.

**Comment by balping** [comment]
The error message is pretty clear: you should load jquery before datatables. Modify your layout file to load jquery before that.

**Comment by MartyHemart** [comment]
thank you and sorry, and I also forgot to define the status, 

EDITE : 

Another problem: After creating a ticket, the tickets are displayed correctly, but when the page is loaded the tickets disappear... no more errors on the console...

Sincerely.
