### ISSUE TITLE
Cannot switch between the bootstrap 3 & bootstrap 4

### ISSUE THREAD

**Issue by j-dohnalek** [thekordy/ticketit#501]
Laravel 5.7

When changing the settings in database to move to bootstrap 3 from bootstrap 4 the system does not move to bootstrap 3. 

Any help on this please?

**Comment by balping** [comment]
You probably still include bootstrap 4 css. Check your layout file

**Comment by j-dohnalek** [comment]
I have used this page https://gitlab.com/balping/ticketit-app/blob/master/resources/views/layouts/app.blade.php to setup the application. I am trying to merge it with application that uses bootstrap 3 and having to use the layout from the link above it completely breaks the page header style.  

![image](https://user-images.githubusercontent.com/6439903/47995655-ee055d00-e0ed-11e8-972e-9d3e982a167a.png)


Any advice?

**Comment by balping** [comment]
This line loads bootstrap 4 by default (that comes with laravel) https://gitlab.com/balping/ticketit-app/blob/master/resources/views/layouts/app.blade.php#L18

Try to load bootstrap 3 via cdn instead.

**Comment by j-dohnalek** [comment]
Thanks for help
