### ISSUE TITLE
Agents cannot see all tickets

### ISSUE THREAD

**Issue by j-dohnalek** [thekordy/ticketit#502]
if agent_restrict is set to 0 or 1 the agent can see only his own tickets 

Agent view
![image](https://user-images.githubusercontent.com/6439903/48206358-244d1180-e366-11e8-8e15-4e40affd13f7.png)

Administrator View
![image](https://user-images.githubusercontent.com/6439903/48206402-434ba380-e366-11e8-93ea-cc0061fd9467.png)

any help please?

**Comment by balping** [comment]
Is that ticket assigned to that agent? 

> Agent restrict: Restrict agents access to only their assigned tickets

**Comment by j-dohnalek** [comment]
The missing ticket is not assigned to the agent.

Maybe I have misunderstand something, please correct me if I am wrong

Feature list talks about

8. Tickets access restrictions (Only ticket owner, an agent, or an admin whom has access to the ticket)
9. Settings option to allow agents access to all tickets or to restrict agents access to only their assigned tickets 

I understood that "agent_restrict" enable/disable the agent to see all tickets (even not assigned to him)? The problem if I set it to 0 or 1 it does not change anything in the list of the agent. Thanks for help

**Comment by SeagleDub** [comment]
I have the same problem
