### ISSUE TITLE
Class 'Kordy\Ticketit\TicketitServiceProvider' not found

### ISSUE THREAD

**Issue by waqarali09** [thekordy/ticketit#504]
i  have pasted Kordy\Ticketit\TicketitServiceProvider::class,  ni my config/app.php but when i rust url to install its giving following error.

Class 'Kordy\Ticketit\TicketitServiceProvider' not found
![screenshot_2](https://user-images.githubusercontent.com/18718710/48630855-0ecb8d80-e9df-11e8-9366-bd0dda342781.png)

**Comment by balping** [comment]
Was the composer install successful? You could also try `composer dump-autoload`

**Comment by waqarali09** [comment]
yes i tried composer dump-autoloadbut not worked
![screenshot_3](https://user-images.githubusercontent.com/18718710/48669589-a4733400-eb29-11e8-979c-e15e39420215.png)

**Comment by balping** [comment]
What version of ticketit did you install? (You can find the version number in composer.lock)
