### ISSUE TITLE
composer install on server and it reset all the changes in vendor folder..no publish command?

### ISSUE THREAD

**Issue by amirgee007** [thekordy/ticketit#506]
hi i install the plugin and it creates all the changes in the vendor folder and it works like a charm.

after that i just commit the code on bitbucket it said no change because vendor folder is in the gitingore so i push the code and run composer install on the server it was the original code and i have no changes in my site.

so is there a way to vendor publish etc so I get all the controller/views/models in the original laravel directory as like when we run vendor publish for the laravel markdown emails it copy all the views into laravel default views folder and we can change according to our needs.

please GUID 
thanks

**Comment by thekordy** [comment]
only views can be overwritten with usual laravel vendor publish command. 
For using your own controllers, you can use a custom routes file to point to other controllers, [just change the path to the routes file from the admin settings](https://github.com/thekordy/ticketit/wiki/Custom-routes-and-customizing-Ticketit-functions)
