### ISSUE TITLE
Issue installing on an existing Laravel project

### ISSUE THREAD

**Issue by markgukov** [thekordy/ticketit#507]
Hi,

I'm having a problem installing ticketit on an existing project. After following all the steps, the /tickets-install page just keeps reloading for me. I can see that the migrations ran successfully. Any thoughts?

Thanks

**Comment by thekordy** [comment]
Anything from error logs?

**Comment by benrobey** [comment]
I am having the same issue. It's like the installation didn't complete properly. I can't see anything in the logs.

**Comment by benrobey** [comment]
I have done some debugging of this issue and I was able to get an error:

```

Ticketit needs upgrade, admin should login and visit ticketit install route
--
 
```

What I had to do is go into my database and update the `ticketit_admin` (against the user) field to true. Then everything worked!

**Comment by thekordy** [comment]
@brobey8 Thanks for letting us know.

**Comment by PilauGrice** [comment]
HI @thekordy  ive managed to get it to intergate and create tickets but the tickets that have been displayed dont show ?
