### ISSUE TITLE
installing route not found - and dont show new tickets

### ISSUE THREAD

**Issue by Rasoul-Karimi** [thekordy/ticketit#509]
hi 

i have an existed project on aravel 5.4 and now install your package and after install, I add a `Kordy\Ticketit\TicketitServiceProvider::class,` to app.php in config directory! after that i login in laravel auth system but when i cal `mySite/tickets-install` return 404 and not found error! this route not define! 

i check it and not any conflict in my web.php file!

2- don't show new ticket!  only show count of one for example but dont show  ticket title and content and other..

**Comment by afandiyusuf** [comment]
+1

**Comment by mgolshan** [comment]
I have the same problem.

**Comment by thekordy** [comment]
Please check if you missed the Auth and login part as mentioned here #295, #507, or #408

**Comment by mgolshan** [comment]
Well,
I am adding this package to an existing project. the auth was installed long time ago.

However, I started implementing my own ticketing system 🤔
