### ISSUE TITLE
Ticketit attempts to install after unrelated migrations

### ISSUE THREAD

**Issue by ThistleApps** [thekordy/ticketit#511]
I have already successfully installed and used Ticketit.  Then I recently updated some unrelated models and ran migrations related to those new, unrelated models and now my users are directed to tickets-install despite Ticketit having already worked.

**Comment by ThistleApps** [comment]
Digging in a bit more I think Kordy is looking for specific migration names.  Is that accurate?  If so, how and were is that identified in the code?

**Comment by thekordy** [comment]
Right. It looks into ticketit/src/Migrations dir and checks if all migration files are migrated.

https://github.com/thekordy/ticketit/blob/0.2/src/Controllers/InstallController.php#L211
