### ISSUE TITLE
i cant install ticketit

### ISSUE THREAD

**Issue by alejandrorau04** [thekordy/ticketit#513]
i cant install ticketiti i followed all steps but i cant do it

please help me !!

**Comment by balping** [comment]
Hello,

Have you tried the quick installer, or manual install? Do you get any error message?

**Comment by alejandrorau04** [comment]
try to install it in both ways
I tried to install it with a local server (localhost / ticketit) but it only opens the folders that it contains

**Comment by balping** [comment]
Propbably you have your webserver misconfigured. Check if the root points to the public folder, etc.

https://laravel.com/docs/5.7#web-server-configuration

**Comment by alejandrorau04** [comment]
I have other programs using laravel and it works perfectly, I do not know why I can not use it I followed all the steps and when I enter
localhost / ticketit only the folders and files appear but not the system :(

**Comment by Shalto** [comment]
I get Class 'Yajra\DataTables\DataTablesServiceProvider' not found using manual install.

I did composer require 'kordy/ticketit:0.*'
i added Kordy\Ticketit\TicketitServiceProvider::class,
to config/app.php

Fixed, by Installing the Yajra before tickitit

**Comment by bishalkc** [comment]
@Shalto Can you please specify laravel version and Yajra version? I am having same issue.

Thank you in advance.

**Comment by merdiano** [comment]
Installed 0.4.5 version on Laravel 5.7
tried to publish config ticketit.php with no success. 
tried to copy it but 'vendor/kordy/ticketit/src/Config/ticketit.php' does not exists
