### ISSUE TITLE
created at time is wrong

### ISSUE THREAD

**Issue by ShifanThawfeek** [thekordy/ticketit#514]

**Comment by ShifanThawfeek** [comment]
Hi, when i create a new ticket, in the ticketit table in the database, created_at and updated_at times are showing wrong time even after changing date.timezone="Asia/Colombo" in php.ini file.

Could you please help me? Thanks!

**Comment by pepoteloko** [comment]
Have you set your timezone in Laravel? file: config/app.php

**Comment by ShifanThawfeek** [comment]
Hi, Thank you so much, now only I set the timezone in app.php and it works perfectly.
