### ISSUE TITLE
Laravel 5.8 compatibility

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#518]
Laravel collective / html has been released, so ticketit could be updated. I won't have time for this before 24th March.

**Comment by dhavald99** [comment]
@balping : can you give estimate when you can update with laravel 5.8.

because i m using package in my site and want to update site for 5.8 release 

Thanks

**Comment by bishalkc** [comment]
eagerly waiting ;)

**Comment by sweatyc** [comment]
Still no update? I tried to add the package into Laravel 5.8.19, it breaks the site with:

> Class 'Yajra\DataTables\DataTablesServiceProvider' not found

Digging into it I can see [Laravel-Databasetables-Oracle](https://packagist.org/packages/yajra/laravel-datatables-oracle) required to be 9.0 for Laravel 5.8, while this package only require 6.0 | 8.0....

Not a Laravel expert, anyone has a workaround?

**Comment by balping** [comment]
Sorry for the delay. New version released, should be compatible with L5.8
