### ISSUE TITLE
Customize admin template

### ISSUE THREAD

**Issue by gidaban** [thekordy/ticketit#522]
Hello guys, 

You do really great job thank.

I want to customize admin template. I already add in config table new record about name of admin template and now i wondering what will happen if i will edit views from vendor dir and you will update package?

**Comment by balping** [comment]
Run `php artisan vendor:publish` and select `TicketitServiceProvider` from the menu. This should create a directory `resources/views/vendor/ticketit`. Under this folder, you can edit files that will persist on updates.

**Comment by gidaban** [comment]
thanks
