### ISSUE TITLE
Migration class name CreateSettingsTable conflicts with Laravel Voyager migration class name CreateSettingsTable

### ISSUE THREAD

**Issue by mjducharme** [thekordy/ticketit#525]
Your migration class name CreateSettingsTable conflicts with Laravel Voyager CreateSettingsTable class, making it awkward to use both in the same system.

I worked around it by manually renaming 2015_10_08_123457_create_settings_table.php to 2015_10_08_123457_create_ticketit_settings_table.php and changing the class name from CreateSettingsTable to CreateTicketitSettingsTable.

Is there any better option that won't involve me having to continually rename this file each time I update your code?

**Comment by balping** [comment]
Hi,

Maybe you could try to override that file from composer: https://medium.com/@shyammakwana/laravel-how-to-override-vendor-class-file-52c7d7b3b384

I wouldn't rename that class here in this repository, because a different migration name could cause troubles in existing installations on update.

**Comment by balping** [comment]
Hi,

Maybe you could try to override that file from composer: https://medium.com/@shyammakwana/laravel-how-to-override-vendor-class-file-52c7d7b3b384

I wouldn't rename that class here in this repository, because a different migration name could cause troubles in existing installations on update.

**Comment by mjducharme** [comment]
Tried it - didn't work. I did some research and PS4 Autoload isn't used for Doctrine migrations so that is probably why it doesn't work. Any other ideas?

**Comment by balping** [comment]
It's a terrible hack, but you could try adding this to `composer.json`:

```
"scripts": {
    "post-update-cmd": [
        "sed -i -e 's/CreateSettingsTable/CreateTicketitSettingsTable/g' vendor/kordy/ticketit/src/Migrations/2015_10_08_123457_create_settings_table.php && mv vendor/kordy/ticketit/src/Migrations/2015_10_08_123457_create_settings_table.php vendor/kordy/ticketit/src/Migrations/2015_10_08_123457_create_ticketit_settings_table.php"
    ]
}
```

This is the same as you were doing, but at least it's automated. Maybe add the same thing for `post-install-cmd` too. If you don't like bash, you can write a php class doing the same renaming business. More info: https://getcomposer.org/doc/articles/scripts.md

**Comment by mjducharme** [comment]
Would it make more sense for me to fork your repo, make those adjustments, and simply pull future updates from your repo to my fork? I doubt you are ever going to change that migration file, so I shouldn't ever end up with any conflicts. It seems silly to have to fork your repo for only that reason, but it might make more sense than doing sed commands.

**Comment by balping** [comment]
Yes, it could work and while it needs some manual maintenance, shouldn't require too much time.

**Comment by thekordy** [comment]
Closed for now new activities.
