### ISSUE TITLE
Tickets are not displayed

### ISSUE THREAD

**Issue by krismd** [thekordy/ticketit#526]
![image](https://user-images.githubusercontent.com/45736872/63962452-93cdf200-ca9b-11e9-8a0d-29faf36cc05f.png)

`@yield('footer')` is conected.
![image](https://user-images.githubusercontent.com/45736872/64010360-48125b80-cb22-11e9-8a2f-600ae075fede.png)

Fix: https://github.com/thekordy/ticketit/issues/526#issuecomment-527503563

**Comment by krismd** [comment]
@balping 🙏

**Comment by balping** [comment]
Hi, I won't have access to my laptop until Wednesday, but I'll have a look
then.

**Comment by krismd** [comment]
Temporary fix

          ajax: {
            url: '{!! route($setting->grab('main_route').'.data', $complete) !!}',
            type: "GET",
            async: false
          },

**Comment by AneeqIftikhar** [comment]
I am getting the same issue. I added the tickets and it is showing in db but it is not getting displayed on the form.

**Comment by AneeqIftikhar** [comment]
Temporary Fix didn't work as shown in the image below, i have highlighted changes. Still no data.
![Capture](https://user-images.githubusercontent.com/29915717/64184329-be95bd00-ce84-11e9-9e7d-6d08b807f28e.PNG)

**Comment by mjducharme** [comment]
Hello, I had this problem initially. It was an issue in my app.blade.php (my main layout file) which was based on the default I believe. The first tag after `<body>` was `<div id="app">`. When I removed the id="app" (so it just became `<div>`) all tickets then appeared. The id="app" appears to use the app.css that comes with Laravel and must somehow interfere with the ticket table display.

**Comment by krismd** [comment]
![image](https://user-images.githubusercontent.com/45736872/64236947-11fb2000-cf04-11e9-9a2b-451a125129af.png)

**Comment by krismd** [comment]
> Hello, I had this problem initially. It was an issue in my app.blade.php (my main layout file) which was based on the default I believe. The first tag after `<body>` was `<div id="app">`. When I removed the id="app" (so it just became `<div>`) all tickets then appeared. The id="app" appears to use the app.css that comes with Laravel and must somehow interfere with the ticket table display.

Thank you!

**Comment by AneeqIftikhar** [comment]
> Hello, I had this problem initially. It was an issue in my app.blade.php (my main layout file) which was based on the default I believe. The first tag after `<body>` was `<div id="app">`. When I removed the id="app" (so it just became `<div>`) all tickets then appeared. The id="app" appears to use the app.css that comes with Laravel and must somehow interfere with the ticket table display.

Thanks

**Comment by balping** [comment]
So is there anything I should change in the codebase, or was it only due to custom theme issues?

**Comment by mjducharme** [comment]
@balping I don't completely recall where I got the app.blade.php file in Layouts. I know I had to manually add the @yield('footer'). Perhaps it was generated when I ran php artisan make:auth? If so then the modern Laravel default adds id="app" out of the box.

**Comment by mjducharme** [comment]
@balping your example app.blade.php includes that id="app":

https://gitlab.com/balping/ticketit-app/blob/master/resources/views/layouts/app.blade.php

You give that as an example in the ticket-it instructions.
