### ISSUE TITLE
Laravel 6.0 compatibility

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#527]
LaravelCollective/html has already been released, so it should be possible to update now.

**Comment by balping** [comment]
Still waiting for https://github.com/mewebstudio/Purifier/issues/110

UPDATE: it's been released, can proceed now.

**Comment by mewebstudio** [comment]
Released https://github.com/mewebstudio/Purifier/releases/tag/3.0.0

**Comment by thekordy** [comment]
Thanks @balping 👏
