### ISSUE TITLE
InvalidArgumentException Action Kordy\Ticketit\Controllers\TicketsController@index not defined.

### ISSUE THREAD

**Issue by Asdrubal-Lavin** [thekordy/ticketit#529]
Illuminate\Routing\UrlGenerator::action
:422
C:\xampp\htdocs\ticketit-app-master\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php

what is the solution a this problem ? 
 i dont know what do :(

**Comment by xcg340122** [comment]
i also encounter this error

**Comment by xcg340122** [comment]
ok,already been solved
you need open chrome visit url: youurl.com/tickets-install
install you script
