### ISSUE TITLE
Relationship restrictions

### ISSUE THREAD

**Issue by thekordy** [thekordy/ticketit#53]
Putting some restrictions and mass moving option.. an example of the relationship restriction:
1. you are about deleting a status that is assigned to many tickets, please move them first to another status in order to be able to delete this status
2. you are about deleting an agent whom is assigned to many tickets, please assign them first to another agent in order to be able to delete this status

anything else?

**Comment by fishmad** [comment]
Option for bulk delete of tickets in list view ( this is handy during development ) a tick box next to table row and a 'select all' link ( auto tick all boxes ) this could double for bulk transfer to another category.

**Comment by thekordy** [comment]
> Option for bulk delete of tickets in list view ( this is handy during development ) a tick box next to table row and a 'select all' link ( auto tick all boxes ) this could double for bulk transfer to another category.

That would need a filter, so you can filter specific status, category or agent related tickets in order to move or delete. We already have datatabels in v0.2.0 , so lets move this issue to v0.2.0
