### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by a7medo778** [thekordy/ticketit#536]
hey guys, i have 2 questions:
1- how can i actually change the ticket status ?
2- how can i change the default ticket naming schema

**Comment by thekordy** [comment]
1- ticket status
2- no naming schema, just ticket title

![Ticketi demo   Ticket  test](https://user-images.githubusercontent.com/11343048/70474805-88935500-1ad3-11ea-9811-00dd44d3ae2a.png)
