### ISSUE TITLE
kordy/ticketit/src/Views/bootstrap4/shared/nav.blade.php

### ISSUE THREAD

**Issue by Polazi** [thekordy/ticketit#538]
I'm using the quick installer and following the instructions on customizing Ticketit functions, 
specifically on TicketController. I did exactly what the tutorial said, but the i got this error:

`Facade\Ignition\Exceptions\ViewException Action Kordy\Ticketit\Controllers\TicketsController@index not defined. (View: /var/www/html/vendor/kordy/ticketit/src/Views/bootstrap4/shared/nav.blade.php)`

I change the /home route in web.php to:

`Route::get('/home', function(){
	return redirect(action('\App\Http\Controllers\MyTicketsController@index'));
});`

#342 is pretty similar to my error, and i saw that is possible to override vendor views. I belive that if i could override nav.blade.php i wold be able to fix it.

i tried to follow the steps from  https://github.com/thekordy/ticketit/issues/342#issuecomment-320501273 but it didn't work.

What am i doing wrong? In my project i will have to override most views and all the methods from TicketsController. That is the way for doing what i need?

**Comment by thekordy** [comment]
I think it's only `nav.blade.php` that needs to be overridden.
