### ISSUE TITLE
Package container-interop/container-interop, phpunit/phpunit-mock-objects, skyscanner/jsonpath is abandoned

### ISSUE THREAD

**Issue by clarkevans7** [thekordy/ticketit#543]
Installing Ticketit with another Laravel APP so installing manually. 

I go to install using composer 
- composer require 'kordy/ticketit:0.*' 
 and I run into these issues. 

1:  Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
2:   Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
3: Package skyscanner/jsonpath is abandoned, you should avoid using it. Use galbar/jsonpath instead.

Now I know it says use psr/container and  galbar/jsonpath instead but kind of a noob and haven't had much luck finding how to add these manually also there wasn't any package for phpunit.

Running Laravel 5.4

If someone could point me in the right direction that would be great, thank you.

**Comment by thekordy** [comment]
@clarkevans7 These aren't direct dependencies of ticketit. Maybe a dependency requires them. You could take a look on composer.lock and find out which packages require them and let us know if it's related to ticketit dependencies.
