### ISSUE TITLE
Branch Naming

### ISSUE THREAD

**Issue by fusiondesign** [thekordy/ticketit#55]
Our branches are named 0.7, 0.2, and 1.0. I believe 0.2 should be 1.1 or 2.0? Either way, I'd like to get naming sorted out so I can properly sync branches :)

I see you are already doing stuff, maybe you know :P

**Comment by fusiondesign** [comment]
Or maybe 1.0 -> 0.1

**Comment by thekordy** [comment]
Naming branches the same as the version number (branch v0.1.0 with version tag v0.1.0) makes some confusion to git, so I renamed branches differently from version.

For versions numbers, I am following [Semantic Versioning 2.0.0](http://semver.org) standard for not confusing people

**Comment by thekordy** [comment]
Now I realized what I have done :/ .. I named it 1.0 instead of 0.1

**Comment by fusiondesign** [comment]
=) No prob, just wanted to make sure not too many people pulled that ver.

**Comment by thekordy** [comment]
> not too many people pulled that ver.

Yes, I know :( ... I didn't know naming branches the same as versions would make problems .. But I hope this is a one time change
