### ISSUE TITLE
Route [tickets.data] not defined

### ISSUE THREAD

**Issue by pcm0nk** [thekordy/ticketit#554]
Hi, After moving my laravel project to another computer I am facing this issue 
```Facade\Ignition\Exceptions\ViewException
Route [tickets.data] not defined. (View: C:\wamp64\newroot\vendor\kordy\ticketit\src\Views\bootstrap4\index.blade.php)
```
I have Changed the routes in ticketit_settings (both value and default) to C:\wamp64\newroot\vendor/kordy/ticketit/src/routes.php
I have also did php artisan config:clear , php artisan cache:clear , php artisan config:cahce
unfortunately still I have no luck
the route http://localhost/tickets-admin gets open ( Im logged in with a admin user)
the route http://localhost/tickets-install is 404
running Laravel 6.17.1
running kordy ticket  v0.4.9
how can I fix this ?

**Comment by thekordy** [comment]
Please install a fresh version on the new computer. Or empty the data from settings db table.

Further you could use `php artisan route:list` and `php artisan route:clear` to debug the issue
