### ISSUE TITLE
How to use email notifications?

### ISSUE THREAD

**Issue by cnluminous** [thekordy/ticketit#555]
How to use email notifications?I changed .env and config/mail.php, but I couldn't get mail.

**Comment by thekordy** [comment]
Please follow laravel docs https://laravel.com/docs/6.x/mail

**Comment by cnluminous** [comment]
I have executed the following command as per the operation of the document:
`composer require guzzlehttp/guzzle
`
`php artisan make:mail OrderShipped
`
SMTP service is available
