### ISSUE TITLE
How to localize ticketit

### ISSUE THREAD

**Issue by Hodakh** [thekordy/ticketit#562]
hi,
I have installed ticketit successfully and I want to change its language to Persian but I don't know how. 
According to [https://laravel.com/docs/master/localization#overriding-package-language-files ](url) I copied files from vendor\kordy\ticketit\src\Translations\fa to resources\lang\vendor\ticketit\fa but nothing changed. I'd be thankful if someone could help me.

**Comment by thekordy** [comment]
Have you configured the locale name ‘App::setLocale($locale);’ ?

https://laravel.com/docs/6.x/localization#configuring-the-locale
