### ISSUE TITLE
Graphics error

### ISSUE THREAD

**Issue by macaxpower** [thekordy/ticketit#566]
<img width="1440" alt="Captura de Tela 2020-09-14 às 18 52 40" src="https://user-images.githubusercontent.com/44126396/93142051-a70a2a80-f6bb-11ea-8248-2e9bac6f4992.png">

I did the installation on my server but the graphics do not appear, can someone help me?

![WhatsApp Image 2020-09-14 at 18 42 46 (1)](https://user-images.githubusercontent.com/44126396/93142140-cdc86100-f6bb-11ea-848c-592aa9f6b75f.jpeg)

**Comment by cryptoprof** [comment]
Had the same problem. After changing single quote to double quote at line 217
ticketit/src/Views/bootstrap4/admin/index.blade.php
like this
`    <script type="text/javascript"  
            src='https://www.google.com/jsapi?autoload={  
            "modules":[{  
              "name":"visualization",  
              "version":"1",  
              "packages":["corechart"]  
            }]  
          }'></script>`
all graphs are displayed.

**Comment by macaxpower** [comment]
@cryptoprof  🥇 
Thank you very much 👍 
it worked for me
