### ISSUE TITLE
Error when install package

### ISSUE THREAD

**Issue by hdhamid1371** [thekordy/ticketit#567]
hi
when i install package appear this error
what's the problem?

![issue](https://user-images.githubusercontent.com/13962284/94024290-166ed100-fdc4-11ea-9869-237c1be95f94.JPG)

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Could not load package mews/purifier in http://repo.packagist.org: [UnexpectedValueException] Could not parse versi
  on constraint ~4.*: Invalid version string "~4.*"

  [UnexpectedValueException]
  Could not parse version constraint ~4.*: Invalid version string "~4.*"

**Comment by sencerturgut** [comment]
same issue here

**Comment by hdhamid1371** [comment]
i solve this issue
you should install Dependents...
**Dependents that are getting installed and configured automatically by Ticketit (no action required from you)

LaravelCollective HTML
Laravel Datatables
HTML Purifier

1- install laravel
2- run 
 composer self-update && composer update
3- install Dependents 
then install the package 
composer require kordy/ticketit:0.*

**Comment by thekordy** [comment]
Related to mews/purifier, there's an [active ticket for this issue](https://github.com/mewebstudio/Purifier/issues/141). 
There's a solution is suggest on the ticket:
`composer self-update && composer update`
