### ISSUE TITLE
composer require 'kordy/ticketit:0.*'

### ISSUE THREAD

**Issue by kennedywee** [thekordy/ticketit#571]
![image](https://user-images.githubusercontent.com/34017640/96826606-3b5b7000-1466-11eb-9451-615e9378cd91.png)

I get this during installation. 

Idk anything.

Imma Noob

Newbie here

**Comment by thekordy** [comment]
@kennedywee  Could you please try `composer require kordy/ticketit:0.*` without the single quote `'`, it's probably a typo in our docs. And let me know please if that is the case

**Comment by kennedywee** [comment]
@thekordy thank you for your reply.

The installation now is working without the single quote. 

Thank you so much!
