### ISSUE TITLE
DataTables config to allow for style alterations

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#59]
DataTables has a lot of configurable options:
https://www.datatables.net/examples/basic_init/filter_only.html

Possible to put these in: config\datatables.php ?

How much work is involved to make overall use of DataTables On/Off a config option ?

`````` /*
```     * Ticket List Table Types: Choose which table design you prefer
```     * Default: datatables
```     * Options: datatables, basichtml
```     */
```     'table_lists_type'=> 'datatables',
``````

**Comment by fusiondesign** [comment]
Datatables has tons of alterations for Bootstrap 3, 2, 1, jQuery UI (Themeroller), and more. I think it would add a lot of bloat but I'm open to suggestion and easily persuaded haha..

Let me know what is kinda the failing point of Datatables for you. The reason I ask is because I think we'd be doing a ton of "cross-developing" to maintain both version with future updates. And the HTML version would take a lot of code to make sort and order/search.

**Comment by fishmad** [comment]
I've become used to bootstrap responsive tables that allow for horizontal sliding on small mobile devices, I cringe a little when relying on heavy JavaScript so much because when something breaks it's a lot harder to troubleshoot. I've been using another package for column sorting in the past and it worked fine but I realised today it's doesn't support SQL joins natively so I'm happy to use Datatables. I just like the idea of graceful fails if something is updated and breaks that we have a fallback option, at the end of the day I think there is enough skills between the three of us to stamp out any potential bugs pretty promptly.

**Comment by fishmad** [comment]
Keep it simple stupid, if you you feel it adds bloat than give my idea a miss - lean works better for everyone and easier to customise. Happy to close this if everyone agrees DataTables is the way to go, I'm sure it has responsive options that I have not yet tried and it's probably designed to fail gracefully if a user has JavaScript disabled.

**Comment by fusiondesign** [comment]
I've been using Datatables in production at 32 of my stores in the US, as well as 4 other stores locally. Over 300 employees hammer my Gift Certificates daily. It may be a bit heavy on the JS but I'm sure we can have a graceful fallback. In fact, I know how we can have a graceful fallback:

We need an interface. If we code to an interface we can call $table->render() and automagically just have whatever (html, datatables, etc) version we want.

**Comment by fusiondesign** [comment]
An interface will force each implementation HtmlTable, DataTablesTable to adhere to the same methods. So we'd have a method to fetch data, a method to format the data and one to render it. Then we can just update one file for each and not have to jump all around our code.

**Comment by fishmad** [comment]
Ok sounds like it's been tried and tested pretty hard. Your the man I have faith.

**Comment by fusiondesign** [comment]
Thanks homie, I've watched every single episode of laracasts probably twice. Never got to use so many of the skills floating in my brain until Github. My clients needs are a little simple sometimes! No more CRUD zzZzzzzzZz

**Comment by fusiondesign** [comment]
Did ya see what I did with the config in the PR?

**Comment by fishmad** [comment]
No I'll check it out now.

**Comment by datune** [comment]
I would advise using datatables only where it actually adds real value, not just for the sake of implementing it. In fact, ideally the application should work without datatables, and implement it only as an added feature, and not the other way around ;-)

**Comment by thekordy** [comment]
@datune I always imagined a lot of things for the tickets front page, but no time at all, so for the time being, datatables does a great job such as fast searching and sorting by any of the available columns.
