### ISSUE TITLE
Truthy statements

### ISSUE THREAD

**Issue by fusiondesign** [thekordy/ticketit#60]
Kordy, how do you feel about switching to booleans for the config file vs yes or no? It would make sense with our language transition.

**Comment by fusiondesign** [comment]
The reason I ask is because our database will want 0 or 1 in the boolean column and it would prevent a lot of ticketit_config table mutators, as well as giving the added benefit of not having to compare values with an if statement.

**Comment by fusiondesign** [comment]
ie
if ($settings->notify_agent) 

vs if ($settings->notify_agent === 'yes')

**Comment by thekordy** [comment]
I agree with that, and i was thinking that when users upgrade, we should implement some function to transfer their custom settings in config/ticketit.php to the database, so we maintain the compatibility

**Comment by fusiondesign** [comment]
So was I, to be honest. That's why a large portion of the config is still in the getSettings() method. I already know what to do :)
