### ISSUE TITLE
Installed latest commit v0.2 - Method style does not exist.

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#66]
ErrorException in Macroable.php line 81:
Method style does not exist. (View: C:\OneDrive\resources\views\layouts\master.blade.php) (View: C:\OneDrive\resources\views\layouts\master.blade.php)

**Comment by fishmad** [comment]
{!! Html::style('css/custom.css') !!}

Wonder why this would break on the update.

**Comment by thekordy** [comment]
May be because of this commit 2d77c7cb7cccd7d0966720aeaed3bd25f65f360c  where i registered the Html from within the provider

**Comment by thekordy** [comment]
It's my bad, I found the issue

**Comment by thekordy** [comment]
Are we good? :)

**Comment by fishmad** [comment]
All good.
