### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by thekordy** [thekordy/ticketit#68]
@fishmad @FusionDesign .. dears, I am going to work on the dashboard this week, to add some statistics and numbers, I am interested to know what do you think we should show in the dashboards.

**Comment by fishmad** [comment]
These are just some ideas:
- Open Tickets (Total)
- Open Tickets per Category
- Closed Tickets
- Unanswered Tickets / Tickets with no response from an Agent
- Average response time / how many days it takes to complete tickets
- Most active ticket: Category
- Most active ticket responder: Agent
- Overdue Tickets 

Agent sign-in message/reminder (this could be a navbar thing):
- You have been assign _#_ tickets {links}
- You have _#_ unresolved tickets to review {links}

RBAC:
- Admin can see everything.
- Agents can see only Dashboard statistics for Categories he is Joined in.

Higher level RBAC:
- Agents can filter results by Categories he is Joined in.
- Agents can filter to show only tickets he was directly involved with.
- Agents can filter by:
  - Ticket categories 
  - Priorities
  - Statuses: open, pending, assigned by, assigned to, completed.

**Comment by thekordy** [comment]
Very nice ideas

**Comment by fishmad** [comment]
Im concerened Brian has been very inactive, hope everything is ok 👌

**Comment by thekordy** [comment]
Actually me too .. I hope he is fine

**Comment by fusiondesign** [comment]
I'm back! I've been fighting with Arch Linux on both of my development machines, quoting problems on Invoice Ninja for my company, customer issues with the change to a Ticket based service from email, and financial problems. Ugh owning a company can be hell sometimes.

You two have been doing awesome work while I've been gone. Very nice! Right now I'm re-importing all my projects, settings up SSH rsync scripts and creating a Twitter bot to help me manage my social networks so I can keep working.

**Comment by thekordy** [comment]
Glade to see you online again :)  ... Wish you good luck with your company :+1:

**Comment by thekordy** [comment]
Current dashboard :)

![laravel - tickets system dashboard 2015-10-24 03-54-49](https://cloud.githubusercontent.com/assets/11343048/10708278/367487d2-7a03-11e5-8b4e-1956b1e97155.png)

To Do: 
Adding number of tickets (open, closed) to the tickets nav for users and agents

**Comment by fishmad** [comment]
That looks awesome.. 👍 cant wait to try it tonight.

**Comment by fishmad** [comment]
WOW, this is something special, better than I imagined it could be.

I noticed when I use the paginate links in users tab it works fine but on page load it defaults back to the Categories Tab.

Welldone @thekordy this work is fantastic.

**Comment by thekordy** [comment]
Thank you .. I am very pleased to see you like it  :)

**Comment by thekordy** [comment]
Added two pie charts for the tickets shares per category and per agent
![laravel - tickets system dashboard 2015-10-24 15-44-58](https://cloud.githubusercontent.com/assets/11343048/10710782/61539758-7a68-11e5-99da-2b6cfc3f9ab3.png)

**Comment by thekordy** [comment]
current nav bar

![laravel - helpdesk main page 2015-10-24 17-39-16](https://cloud.githubusercontent.com/assets/11343048/10711276/42dd8852-7a76-11e5-915e-80f35ff53a43.png)

**Comment by thekordy** [comment]
I will keep it couple of days for testing, then let's launch the v0.2 version to the world :) .. I believe it became amazing in a lot of ways thanks to you both Brian and Lee :+1:  ... I really can't wait to bring it to the light :)

**Comment by thekordy** [comment]
Dear Brian @FusionDesign , please if you have got any time, would you please install v0.2 on the demo site? and you can use Seeds/TicketitTableSeeder to generate as many demo data as you wish .. just copy it to someplace like app/http/controllers , correct namespace, adjust demo data parameters for demo data volume .. and fire it :+1:

**Comment by fusiondesign** [comment]
Yes absolutely, I’ve got a client I’m working on for 4 more hours then I’ll be good to go.

FUSION DESIGN

Owner of Fusion Design

1 (269) 910-4457

"Walking on water and developing software from a specification are easy if both are frozen." 

 https://www.facebook.com/fusion.design.me Facebook |  https://www.twitter.com/_FusionDesign Twitter |  https://plus.google.com/+FusionDesignKalamazoo Google+ |  https://github.com/FusionDesign Github |  https://www.linkedin.com/in/fusiondesignme LinkedIn

 http://fusiondesign.me/

**Comment by fishmad** [comment]
Trying to run the seeder on its own through composer so I can view dashboard in more detail.
but I'm getting error.

C:\laravel>php artisan db:seed --class=Kordy\Ticketit\Seeds\TicketitTableSeeder

  [ErrorException]
  Trying to get property of non-object

LOG:
[2015-10-25 09:01:36] local.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\laravel\vendor\kordy\ticketit\src\Controllers\NotificationsController.php:67
Stack trace:
#0 C:\laravel\vendor\kordy\ticketit\src\Controllers\NotificationsController.php(67): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', 'C:\OneDrive\lar...', 67, Array)

**Comment by fishmad** [comment]
Got it,

had to comment out line 66 and 67 in the NotificationsController.php because it would try to send emails, I did try to disable status_notification in admin configuration first.

```
    public function newTicketNotifyAgent(Ticket $ticket)
    {
        $notification_owner = auth()->user();
        $template = "ticketit::emails.assigned";
        $data = [
            'ticket' => serialize($ticket),
            'notification_owner' => serialize($notification_owner),
        ];
//        $this->sendNotification($template, $data, $ticket, $notification_owner,
//            $notification_owner->name . trans('ticketit::lang.notify-created-ticket') . $ticket->subject, 'agent');
    }
```

Can uncomment once its seeded.

**Comment by thekordy** [comment]
What I do is installing ticketit on fresh db,  login with admin, from the
configuration panel disable all email notifications (the last four)
settings, run the seeder.

For some reason disabling only email notification doesn't stop
notifications

**Comment by thekordy** [comment]
![laravel - configuration settings 2015-10-25 19-12-05](https://cloud.githubusercontent.com/assets/11343048/10716787/5586adc2-7b4c-11e5-946d-8fa98826c87e.png)

**Comment by thekordy** [comment]
also you will need to increase the max execution time
