### ISSUE TITLE
Unregistered Users able to Create New Ticket by Webform or Email

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#69]
Having used a Webhosting Management System in the past that had built in ticket support system: its called WHMCS, it had a feature that allows unregistered users to create support tickets or enquiries by:

a) directly visiting the site and creating a ticket by filling out the form (registered and unregistered users)
b) send an email to a predefined email address that is hooked into a cron job that pipes the incoming email to the database (if the incoming email has an existing ticket number in the subject line it would append an existing support ticket - if not, it creates a new ticket). applies to both registered and unregistered users.

How achievable is a.?
is b. something we could look to incorporate in the future?

**Comment by thekordy** [comment]
That is very odd! I was thinking about that today :)

Let's put it in our planned features, I am totally interested in both the
guest form and the email piping features.

**Comment by borger** [comment]
+1!
