### ISSUE TITLE
Close ticket

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#7]
It would be nice if there was such functionality. For example in the config file there could be a close_status_id item. Lets assume that it is set to 5 and there's a status called 'Closed' in the database with id of 5. Then when an admin sets a ticket's status to 5 - closed, the user is not allowed adding comments any more.

**Comment by thekordy** [comment]
That's a very good idea, and we might make the option to decide the start
and closing statuses directly at statuses admin panel

**Comment by FusionDesign** [comment]
I can add this tonight, I'm going to be doing a bunch of stuff to my internal version (just a different theme) -- so I'll cross port anything I do and see if I can get themes working so I won't have to maintain two versions :)

**Comment by thekordy** [comment]
Your contributions are very appreciated :+1:

**Comment by FusionDesign** [comment]
Complete and Reopen ticket has been added with latest PR.

**Comment by thekordy** [comment]
Done in v0.1.0

**Comment by FusionDesign** [comment]
I saw that! I'm overworked, I just pushed up a WIP commit to my 0.1.0 fork branch around DataTables. They are not being rendered yet and I've still got a lot of refactoring to do but I'm hoping I can push something decent after some rest.
