### ISSUE TITLE
Attachments to tickets

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#70]
@thekordy @FusionDesign  What's your thoughts on being able to upload / attach images or other files to support tickets.

Something like dropzonejs that allows users to drag/drop or upload attachments via Ajax in real time as part of new ticket creation or ticket update.

GitHub uses a similar function in these issue forums and I love the convenience of dragging screen dumps in the posts - pictures worth a thousand words.
I'd think both agent and user can use it, and we can restrict mime types and upload sizes easily enough 

We could bake it in just like bootstrap and jquery and have it as an optional enable/disable in admin config.

http://www.dropzonejs.com/

Laracast has done tutorial on its implementation and use 
https://laracasts.com/series/build-project-flyer-with-me/episodes/11

Would need a new table attachment to tickets.

**Comment by thekordy** [comment]
I think it's the right time to start adding these cool features such as the file upload and the email piping .. What do you think about adding them in the next release v0.3.0 planned features? I think we can do it ;)

**Comment by datune** [comment]
Having attachments available in tickets would open up the ability to start thinking about frontend widgets that would allow site visitors to easily submit an issue with a screenshot of the site, similar to something like say, usersnap ;-)

However, unless I missed them somewhere, I don't see any tests for this application? If you have not written any tests, I would really recommend freezing development with the .02 version and add them while it is still relatively manageable to do.

**Comment by thekordy** [comment]
@datune  Can't agree more .. I may dedicate the first couple patches to the 0.2 for the tests
