### ISSUE TITLE
Lots of Queries

### ISSUE THREAD

**Issue by MightySCollins** [thekordy/ticketit#71]
Hi

I love the ticket panel, it works really well and looks good I am just slightly concerned at the number of queries it used. The new dashboard (which is great) does quite a few SQL queries in my install it did 106. We were easily able to drop it down to 72 by removing the `Cache::forget('settings')` on line 42 of Setting.php but I wanted to know if you know any other quick ways to reduce the number of queries it is doing and especially reduce the number of duplicates.

You can see the debug bar results below
![screenshot1](https://cloud.githubusercontent.com/assets/8594759/10712698/87dd9c62-7a99-11e5-9fdc-96e56a6540da.png)
![screenshot2](https://cloud.githubusercontent.com/assets/8594759/10712699/87df8158-7a99-11e5-8701-7f47e03b18e6.png)
![screenshot3](https://cloud.githubusercontent.com/assets/8594759/10712700/87e57982-7a99-11e5-9309-01d052bc4b6d.png)

I was also confused at a few of your queries for example 

``` sql
select count(*) as aggregate from `ticketit` where `ticketit`.`agent_id` = '1' and `ticketit`.`agent_id` is not null and `completed_at` is null
```

Well surely if the `agent_id` is equal to 1 it will not be null (This might just be the laravel query builder though)

Sorry for the criticism I really like your system and I do know that you are still actively working on 0.2

**Comment by thekordy** [comment]
Hi Mighty, I agree with you. This issue will be my priority before releasing 0.2 
Thank you for giving your feedback, it's very appreciated here :+1:

**Comment by MightySCollins** [comment]
Thanks again for the system, it's great. Keep up the good work

**Comment by fusiondesign** [comment]
Just getting my feet wet again. I'm am LOVING the admin console. Finally got my sync scripts setup, was just testing them with a simple update. Seems Sublime also treats your code much better on this new setup. No spacing issues.

**Comment by thekordy** [comment]
Thank you Brian and welcome back .. We missed you here :)
