### ISSUE TITLE
No routes

### ISSUE THREAD

**Issue by amarkotha366** [thekordy/ticketit#73]
I cant find any route after install.

Showing Error

NotFoundHttpException in RouteCollection.php line 161:

**Comment by thekordy** [comment]
seems that you have not completed the install process, make sure you complete the rest of the installation steps:

Step 2. After install, you have to add this line in your `config/app.php` in Service Providers section (1-2 minutes).

``` php
    Kordy\Ticketit\TicketitServiceProvider::class,
```

Step 3. [Setting up your master view for Ticketit integration (1-2 minutes)](https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template)

Step 4. Go ahead to http://your-project-url/tickets-install to finalize the installation (1-2 minutes)

Default ticketit front route: http://your-project-url/tickets

Default ticketit admin route: http://your-project-url/tickets-admin

**Comment by DanielAscher** [comment]
the problem here seems to be that - just as for me - there is no route for /tickets-install ... i get a 404 when trying to visit this page. yeah, i did edit my config/app.php

**Comment by MightySCollins** [comment]
It works fine for me, it does not add them to the file but after following the steps properly I could visit the URL.

**Comment by DanielAscher** [comment]
Do you see the route when doing an php artisan route:list? because i do not see it there. also did a composer dump-autoload with no luck

**Comment by thekordy** [comment]
@DanielAscher you won't find it in the routes list because the service provider use it only once (on the fly) when it sees ticketit tables are not yet migrated and the settings are not built.
You can find what i mean here https://github.com/thekordy/ticketit/blob/0.2/src/TicketitServiceProvider.php#L104

But what about the default routes, Do you see the default routes "tickets" and "tickets-admin" in the routes list?

**Comment by thekordy** [comment]
Thank you @MightySCollins .. you are right .. it doesn't add the tickets-install to the routes list, if that is what you meant.

**Comment by DanielAscher** [comment]
oh i see, i need to be logged in. Funnily, the default routes are not there either (in artisan route:list) (should they?).
I did do the migrations, but via artisan.

**Comment by thekordy** [comment]
@DanielAscher I asked because they should not :) .. at least not before finishing the ticket-install step

**Comment by yelgazin** [comment]
The same issue occurs. Laravel Framework version 5.1.23 (LTS)
Step 2. Ок.
Step 3. I could not find resources/views/master.blade.php file. Only exists welcome.blade.php. 
Step 4.  See nothing :-(

PS. Project locates in subfolder. http://someserver/it.

**Comment by thekordy** [comment]
@yelgazin please review [this issue first](https://github.com/thekordy/ticketit/issues/74) and tell me if you still got a problem

**Comment by yelgazin** [comment]
Step 3. See page.
Step 4. http://someserver/install-ticket  
NotFoundHttpException in RouteCollection.php line 161: ....

It seems like ServiceProvider doesn`t works as expected.

**Comment by thekordy** [comment]
> Step 4. http://someserver/install-ticket

It is http://someserver/<b>tickets-install</b>

**Comment by yelgazin** [comment]
Yes. It redirects to /auth/login with message NotFoundHttpException in RouteCollection.php line 161
A shame to admit, but I could not see any error in apache or larevel log.

**Comment by thekordy** [comment]
@yelgazin you have to be logged in first, if you have created users accounts, create one, and login, then go to the install link

**Comment by yelgazin** [comment]
@thekordy I have created user, but exception occurs. Could you advice me how to trace? Maybe be  error due to Centos...apache config or something else.

**Comment by thekordy** [comment]
@yelgazin What this message means is that laravel can't find this path `/auth/login` in the app/Http/routes.php file.

To activate the authentication system, you need three things to be done ([Laravel Authentication](http://laravel.com/docs/5.1/authentication)):
1. Migrate the user and password migration files (php artisan migrate)
2. Add the auth routes to the routes.php file
3. Create authentication views

I found this answer very helpful with full details http://stackoverflow.com/questions/32482109/how-can-you-add-back-authentication-to-laravel-5-1

Also you can just use the auth scaffolding package here https://github.com/bestmomo/scafold for the authentication views and routes setup. 

**Also do not forget to remove the Ticketit service provider class from the config/app.php temporary until you setup the authentication system, then add it back, login, then proceed to /tickets-install**

**Comment by yelgazin** [comment]
@thekordy  thank you. Now it works. Next step is to integrate in domain and auth with NTLM :-)

**Comment by thekordy** [comment]
@yelgazin Pleased to see it works for you. Thank you for using Ticketit :+1:

**Comment by gchimuel** [comment]
Is running the **php artisan config:clear** fixes the problem?

**Comment by souri84** [comment]
for me, I had to go to http://site.tld/public and it was good....
