### ISSUE TITLE
problem setting up

### ISSUE THREAD

**Issue by sicksand** [thekordy/ticketit#74]
Hi,

Discovered your helpdesk and I think it really suits me.

I have a problem bring it up to my local development

here are my steps.
1. composer create-project laravel/laravel helpdesk
2. cd helpdesk
3. composer require kordy/ticketit:0.*
4. nano config/app.php and add Kordy\Ticketit\TicketitServiceProvider::class, to the two service providers
5. run php artisan serve will cause me error homestead@homestead
6. nano .env and supply the username and password and manually create 'ticketit' database via phpmyadmin
7. run again php artisan serve and it throw error "[PDOException]  
   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticketit.migrati  
   ons' doesn't exist"

How do I go about it. I can't get it p and running. Really need help on this.

Thanks

**Comment by mavinothkumar** [comment]
What DB are you using ?

**Comment by sicksand** [comment]
hi,
i am using mysql

On Wed, Nov 4, 2015 at 12:19 AM, Vinoth Kumar notifications@github.com
wrote:

> What DB are you using ?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Mohammad Shafiq Bin Mohd Mustapa

**Comment by MightySCollins** [comment]
Laravel probably just needs the `migrations` table. Remove the table you created and just run `php artisan migrate`. That should make the table. I am mostly sure this is not a package issue.

**Comment by thekordy** [comment]
@sicksand remove the ticketit service provider from config/app .. then run the serve.
And let me remind you that you have to follow exactly the requirements and installation instructions in the same sequence or you will get many errors.

you can find the requirements and installation instructions here:
https://github.com/thekordy/ticketit/blob/0.2/README.md

**Comment by sicksand** [comment]
@thekordy 

I have followed the README.md but I am stuck at the integrating the master view. (https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template)

In my views folder there is no master.blade.php, I've created it and follow the instruction above. I've also change the routes to read master view file but it return empty.

**Comment by thekordy** [comment]
This is the master view I am using, also the auth views are included, just unzip the content into your laravel project root, following the same paths in the archive.

http://kordy.info/laravel_bootstrap_master_auth_views.zip

**Comment by sicksand** [comment]
@thekordy thanks for the file, after modifying the master file, i went to do this
php artisan vendor:publish --provider="Kordy\Ticketit\TicketitServiceProvider" --tag="config"

but the output is "Nothing to publish for tag [config]."

**Comment by thekordy** [comment]
There is no config file in the new version ;)

**Comment by sicksand** [comment]
@thekordy so what should i do next? i have point the browser to http://localhost:8000/tickets-install redirected to auth/login. there is no data in users table.

**Comment by thekordy** [comment]
then you need to register a new account for the admin (
http://localhost:8000/auth/register), then go again to
http://localhost:8000/tickets-install while you are logged in.

Also you might need to register more additional accounts to demonstrate
agents and users.

**Comment by sicksand** [comment]
@thekordy woohoo thanks. now the bootstrap seem not working from the master file. 
![image](https://cloud.githubusercontent.com/assets/305408/10932590/f717adb8-830c-11e5-831d-b5c1992837a5.png)
![image](https://cloud.githubusercontent.com/assets/305408/10932594/ffc9685c-830c-11e5-9377-44c977402110.png)

**Comment by sicksand** [comment]
![image](https://cloud.githubusercontent.com/assets/305408/10933030/7672318e-8310-11e5-9b55-08a5ffcab641.png)

seems the master.blade.php end up in cache. I have to delete it and remake it. now it is all good.
Thanks @thekordy
