### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by riansopian** [thekordy/ticketit#75]
Hi..

ticketit was installed on my project, but the ticketit is old version, how to update to newest version?

Best Regard

**Comment by thekordy** [comment]
Very simple: 
1. Make sure in the composer.json file has "kordy/ticketit": "0.*" in the "require" section
2. Then do this command "composer update"
3. Then in the browser go to "http://your-url/tickets-install"

That's it :)

**Comment by riansopian** [comment]
ok , and where I have to process all of the tickets that have been made?

**Comment by thekordy** [comment]
Backup your database first, then update. All tickets and settings should be
available and working after update.

**Comment by thekordy** [comment]
If you already did any customization to the ticketit views, then you will
to backup these views as well, and republish the new ticketit version
views, as we did a massive improvements to the ticketit views.

**Comment by riansopian** [comment]
I mean, the menu for the process that the tickets have already been settled or is being done, where the menu?

**Comment by thekordy** [comment]
Do you have resources/views/vendor/ticketit  directory in your laravel
project?

**Comment by riansopian** [comment]
yes i have,
Ticketit already in my project, and running, I've created a new ticket, and how to process the ticket?

**Comment by thekordy** [comment]
You have to use the new views in the new version, you have to replace your
current customized views in resources/views/vendor/ticketit directory with
the new version views in vendor/kordy/ticketit/src/Views , and then redo
the custom edits

**Comment by thekordy** [comment]
If after that the problem remains, please give me a screenshot and paste
here the page source, so I can be more helpful to you.

**Comment by rgilbert4307** [comment]
![image](https://cloud.githubusercontent.com/assets/5492396/10952201/9c0ee184-8352-11e5-8fe4-6fe7425bee7d.png)

V 0.2.0 works fine after installation except for the css formatting/displaying-not appealing as your demo(see attached). How can i quickly fix it to appear like the one on your demo. Thanks,

**Comment by thekordy** [comment]
@rgilbert4307 You have to include the bootstrap and jquery into your master views. 

If this is a fresh laravel project and you don't know where to start, please refer to #74 where I already provided many handful resources to boot laravel views faster.
