### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by DanielAscher** [thekordy/ticketit#78]
hi,
on domain/ticket-install laravel hit's a 500 error:

[2015-11-04 17:14:56] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 30 seconds exceeded' in /var/www/domain.xyz/vendor/symfony/console/Formatter/OutputFormatter.php:165

**Comment by thekordy** [comment]
May be something wrong happens when the script makes artisan commands, We still can process it manually to know which command causes the error in your laravel project.

**Manual install (alternative that bypasses /tickets-install):**

1) place the [ticketit.php config](https://github.com/thekordy/ticketit/blob/0.1/src/Config/ticketit.php) file in the your laravel project config folder
2) Modify the ticketit.php config settings
3) install ticketit migrations

``` php
php artisan vendor:publish --provider="Kordy\Ticketit\TicketitServiceProvider" --tag="db"
php artisan migrate
```

 4) seed the settings to the ticketit_settings table

``` php
php artisan db:seed --class=Kordy\\Ticketit\\Seeds\\SettingsTableSeeder
```

**Comment by DanielAscher** [comment]
first problem occures when trying to publish the migrations:

Nothing to publish for tag [db].

**Comment by thekordy** [comment]
Sorry it is my mistake, The db tag is now present.
update the package

``` php
cd vendor/kordy/ticketit
git pull
cd ../../../
```

and then proceed again with the manual installation

**Comment by DanielAscher** [comment]
installed seems to work. Migrations succeeded, BUT: I can't access the ticket-admin site. It says that i'm not allowed to view this page.  I even set the "ticketit_admin" manually to 1 in my users table.
It also seems that ticketit is not reading the ticketit.php from /config/ as i actually set the user-id in there, but it did not alter the mysql data. The set master.blade.php i set in the config did not work either, it looked for a master in /resources/views/ rather then the configured /master/views/layouts/master.blade.php

**Comment by thekordy** [comment]
It does not look for the ticketit_admin flag at the moment (I will put this on my tasks list). Also it loads the config/ticketit.php only the first time when it seeds the settings table, so adding user id to the admin ids array won't give any effect unless it is done before settings table seeding.

**Solution:**
1. If you have can edit the database, then got to the ticketit_settings table and look for "admin_ids" slug, edit its value (replace 1 with the user id)
2. in `vendor/kordy/ticketit/src/Models/Settings.php` uncomment line 47:

``` php
//Cache::forget('settings');
```

to become

``` php
Cache::forget('settings');
```

**Comment by DanielAscher** [comment]
okay, this worked. I'm now able to see the admin. Another problem occured: i could create a ticket, and the number of tickets increases, but i can not see a ticket

**Comment by kasirye** [comment]
The auto installation is a good idea, but it seems "php artisan" command is not running from a script... 
its also not possible to allocate another directory for a blade template...

**Comment by thekordy** [comment]
@DanielAscher so you can access tickets-admin , but when you go to /tickets you don't see any ticket?

**Comment by DanielAscher** [comment]
exactly. i can see it when i go to /tickets/1 though

**Comment by goutamwms** [comment]
Hi, i was able to install properly . but can't seed . So i am unable to see data in ticket admin . Can you please help .

**Comment by rgilbert4307** [comment]
![image](https://cloud.githubusercontent.com/assets/5492396/10999049/e705e04e-84aa-11e5-8659-cac366aa5f38.png)

@thekordy I am experiencing the same problem as @DanielAscher. The system is properly installed but it can't list the tickets. Please assist.

**Comment by fusiondesign** [comment]
Whats your dev console say for XHR errors?

**Comment by thekordy** [comment]
@goutamwms why you can not seed? is it because of an error? Would you please provide more details about what you have done and what you are trying to do?

**Comment by thekordy** [comment]
@FusionDesign Yes, I think I've got your point :+1:   .. @rgilbert4307 and @DanielAscher seems like datatables javascript is not loaded, are you sure you added "@yield('footer')" in your master template? 
If not, then please review this wiki page on how to integrate Ticketit with your master template https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template

**Comment by fusiondesign** [comment]
That has to be it!

**Comment by DanielAscher** [comment]
That was it. I really did miss the footer.

**Comment by thekordy** [comment]
@DanielAscher glade to see your problem is solved, Thank you for using Ticketit :)

**Comment by fusiondesign** [comment]
Kordy, I’m putting in your sqlite database today. Had to write up a massive quote!

FUSION DESIGN

Owner of Fusion Design

"Walking on water and developing software from a specification are easy if both are frozen." 

 https://www.facebook.com/fusion.design.me Facebook |  https://www.twitter.com/_FusionDesign Twitter |  https://plus.google.com/+FusionDesignKalamazoo Google+ |  https://github.com/FusionDesign Github |  https://www.linkedin.com/in/fusiondesignme LinkedIn

 http://fusiondesign.me/

**Comment by goutamwms** [comment]
Hi thekordy , please see the attached image .
![error](https://cloud.githubusercontent.com/assets/11768019/11180374/5abdddf2-8c80-11e5-8f44-0002945f20dc.png)

**Comment by thekordy** [comment]
@goutamwms Hello, Actually .. The demo seeder is not stable, I just added it as a help tool for developers (who want to generate demo contents) to build on the top of it. 
So my recommendation is to make a new controller, copy the demo seeder class content into it, adjust it as your needs, extend the php maximum execution time, run it once.

**Comment by goutamwms** [comment]
thekordy , can you please upload a full working code ..

**Comment by thekordy** [comment]
@goutamwms .. working code of what?
