### ISSUE TITLE
Email queue doesn't work

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#8]
Hi!
When `'queue_emails' => 'no'`, everything works fine, the email is sent. However if I try queued emails, I get the following message from the queue worker:

```
[ErrorException]                                                                                                                             
  Trying to get property of non-object (View: /var/www/resources/views/vendor/ticketit/emails/comment_notification.blade.php)  
                    
  [ErrorException]                      
  Trying to get property of non-object 
```

My queues are configured of course, I'm using  database driver.

I started debugging, I dumped `$comment` inside `comment_notification.blade.php` and `$comment` is an array however it is supposed to be an object, that's the problem.

I'm suggesting you the following:

Use the array version of the comment and the ticket and in the views reference the properties as array keys. For example in function newComment():

`$data = ['comment' => $comment->toArray(), 'ticket' => $ticket->toArray()];`

Hope that helps. I didn't try this, but it should work I think

**Comment by thekordy** [comment]
It's my fault, i have not given it enough testing. I will look into it and
get back to you.

**Comment by thekordy** [comment]
The solution you suggested works, but i used another way to fix it by serializing the object before queue and then unserialize in the views, so people can use all ticket related models information in views (category name, status name, colors, ..)
