### ISSUE TITLE
Different templates for backend and frontend

### ISSUE THREAD

**Issue by Nimfus** [thekordy/ticketit#80]
Greetings!

Discovered this great library today and trying to implement it into my Laravel 5.1 project. Everything goes well until I tried to create different templates (master template) for frontend and backend. 
Now Ive got master_template looks like 'backend.master.blade.php' and It's accessible only for administrator of the page and I would like users to use another template, for example 'frontend.master.blade.php'.
It would be great if somebody could help me with this, I can't deal with on my own due to I'm new to Laravel and this library also.

Thanks in advance!

**Comment by thekordy** [comment]
Hello :)

Well .. Laravel does not provide Roles system by default, you will need to alter the users table to add another column for user role, or to make a role table and a user-roles pivot for a more scalable solution.
Then you create a model with a check function like hasRole($role) , so you can check users roles, and use that check at the function you want to switch between templates and contents, something like

``` php
if($request->user()->hasRole('admin')) return view('admin')->with('admin_content', $admin_content);
else return view('user')->with('user_content', $user_content);
```

Also you don't switch "master' template which all its job is to build the structure (header, body, footer), but you switch the content
so the master template (resources/views/master.blade.php) would be something like:

``` html
<html>
    <head>
        ...
    </head>
    <body>
       ..
       @yield('content')
       <footer> .. </footer>
    </body>
</html>
```

And the admin template (resources/views/admin.blade.php) would be something like:

``` html
@extends('master')
@section('content')
     admin content here {{ $admin_content }}
@stop
```

And the user template (resources/views/user.blade.php) would be something like:

``` html
@extends('master')
@section('content')
     user content here {{ $user_content }}
@stop
```

I find this gist very helpful to give you a fast push to start building roles system:
https://gist.github.com/drawmyattention/8cb599ee5dc0af5f4246

**Comment by Nimfus** [comment]
Thank you very much for answer!

I've got a role based system, so I will try to separate views just as you recommended.

Thanks again!
