### ISSUE TITLE
Missing the two Pie Charts

### ISSUE THREAD

**Issue by fishmad** [thekordy/ticketit#82]
Any ideas as to why I don't have them anymore?
![capture](https://cloud.githubusercontent.com/assets/12012101/10989841/75675a12-84a0-11e5-8f0b-91479735129d.JPG)

**Comment by thekordy** [comment]
No idea .. what about the inspection console? could you please paste this page source?

**Comment by thekordy** [comment]
Hello Lee, any news?

**Comment by fishmad** [comment]
I will have another play tommorow try figure this out, wondering if its a limitation of running a localhost setup.

**Comment by thekordy** [comment]
Dude, I am very pleased for seeing you again, you have been off for a long time. How have you been?

**Comment by fishmad** [comment]
Hi Kordy, I'm good been busy with work but I'm still here..

I've just compared my view source html code to your demo site and I'm seeing a small error my snippet below appears to be missing comma's after the square brackets ["dfhsdgfhsf"],

```
        // performance line chart
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ["Month", "Technical", "Billing", "Customer Services"],
                                                            ["October 2015", 3.8,2.3,5.5],
                                                                                ["November 2015", 0,0,0]
                                                                                ["December 2015", 0,0,0]
                                                ]);
```

![2015-12-12_13-30-42](https://cloud.githubusercontent.com/assets/12012101/11759696/ffdb04e6-a0d4-11e5-9f4c-0cf8e6187eca.jpg)

**Comment by fishmad** [comment]
\laravel-plus\vendor\kordy\ticketit\src\Views\admin\index.blade.php

line 260

```
                       ["{{ $month }}", {!! implode(',', $records) !!}]
```

add comma to end:            

```
                       ["{{ $month }}", {!! implode(',', $records) !!}],
```

All charts now working.. :-)

@Kordy Can you check this and add fix if all ok - add to next commit.

![24](https://cloud.githubusercontent.com/assets/12012101/11759926/e959aab4-a0da-11e5-80b9-0f89b6e73fe8.jpg)

**Comment by thekordy** [comment]
I don't know why it was working before on my machine
