### ISSUE TITLE
Call to a member function prepare() on null

### ISSUE THREAD

**Issue by SnehalSatardekar** [thekordy/ticketit#83]
Hello

I have installed this plugin on laravel 5.1, done migration and added provide in config/app.php.

But now when I try to run my project it shows me error as 

"FatalErrorException in Connection.php line 319:
Call to a member function prepare() on null"

Could someone please help me with this?

**Comment by thekordy** [comment]
To be able to help you, Please make sure you fulfilled the [pre-requirements](https://github.com/thekordy/ticketit/blob/0.2/README.md#requirements) and followed the 4 steps mentioned [here](https://github.com/thekordy/ticketit/blob/0.2/README.md#installation-4-8-minutes)

After that please mention the URL you were visiting when you've got the error, the exact steps you did in installation, the laravel error log

**Comment by SnehalSatardekar** [comment]
@thekordy 

Steps followed are:
1. added "kordy/ticketit": "0.*" in composer.json
2. done composer update
3. added provider in config/app.php

Now I just hit "http://my_url/tickets-install" url and then it shows me the error

also config folder is not there in installed version.

Can I use the same with mongodb?
