### ISSUE TITLE
Admin Settings not refreshed

### ISSUE THREAD

**Issue by datune** [thekordy/ticketit#86]
Making a change to the configuration is not applied unless I manually delete the cache folder. 

For example, changing the default_reopen_status_id in a production environment is not going to actually change until the cache is deleted. 

Steps to verify:
1. Login as admin, create ticket
2. Change the default_reopen_status_id in your configuration
3. Close your ticket
4. Reopen your ticket

The reopened ticket will not have the default_reopen_status_id you just set in your configuration, it will have the previously applied value.

**Comment by thekordy** [comment]
@datune Thank you for your feedback, This is a real problem I am aware of it. I will work on it so when any update to the settings should reset the cache as well.

**Comment by thekordy** [comment]
In the mean while (as a work around), you may enable (uncomment) the cache forget in [Settings Model](https://github.com/thekordy/ticketit/blob/0.2/src/Models/Setting.php#L47), that will remove settings cache every time.

**Comment by thekordy** [comment]
Fixed in v0.2.1
