### ISSUE TITLE
Form alias overrides app config

### ISSUE THREAD

**Issue by Gummibeer** [thekordy/ticketit#91]
If anyone has it's own FormBuilder or a customized one of the "default" the ServiceProvider breaks it - would be nice if there is any config for this or and other Alias for this package internal or the Facade directly and not via alias. But this has destroyed my application and I had to remove the service provider until this is fixed.

**Comment by thekordy** [comment]
I am terribly sorry for this issue, I hope this update would fix it.

**Comment by Gummibeer** [comment]
Looks good - I will test it today and give feedback. Thanks for the quick response and fix! :)

**Comment by Gummibeer** [comment]
Which version do I have to load via composer to get this change? `dev-master` or is there already a tag?

**Comment by thekordy** [comment]
I haven't released the new patch yet, you have two ways to install yet

1) Install the packagist dev package

``` shell
composer require kordy/ticketit:0.2.1.x-dev
```

2) or to install it like normal and just go to `vendor/kordy/ticketit` and make `git pull`

**Comment by Gummibeer** [comment]
Ok, this has solved my Problem.

But I recommend a config entry for this alias `'form-alias' => 'Form',` cause if you change it without this fallback all old versions will break - with this option it's possible to set it to whatever the dev want and don't break the old versions.

**Comment by Gummibeer** [comment]
Or a config to prevent this alias and use directly the customized one with the `Form`alias.

**Comment by thekordy** [comment]
That is a very good idea, it is even better than what I did. I will try to implement it in the installation process.

**Comment by Gummibeer** [comment]
And just for me: why do you use DB settings and not the laravel config files and use an installation process with views and not the laravel package way: `artisan vendor:publish, configs and so on?

**Comment by thekordy** [comment]
We were using it, there is a discussion here about switching to db for configuration in order for some features we were planning for.
Actually we still use it, as at the installation, the system will look for the config/ticketit.php config file and insert its settings into the db.

**Comment by Gummibeer** [comment]
Ok, but it makes the things a lot more complicated. Changing settings in the database is much harder than changing the config file.
Also for deployments (dev, stage, live) and the DB settings can't be customized by `.env`.

It's one of the only reasons why I'm thinking about do the job my own cause it's so much to do to get a customized version of this package.
