### ISSUE TITLE
Tickets missing from Active page

### ISSUE THREAD

**Issue by tmcdon89** [thekordy/ticketit#92]
I have been integrating the system in with an app I've been working on and its been going pretty smooth. However I've now submitted 4 tickets from the admin account and none are showing up in the "My Tickets" page. They are registered because the "Active Tickets" link shows 4 tickets, but there is nothing there when you browse to it. 

I've checked the database tickets table and the tickets are there and filled out.
I'm not getting any errors so I'm not sure where to look first on this. 

Thanks

**Comment by thekordy** [comment]
Would you please show us a screenshot of the tickets page? and for the agents and administrators pages if possible?

**Comment by tmcdon89** [comment]
I believe these are the screens you mean, correct?
I'm also including a screenshot of the ticketit table in my database. All 4 tickets were created using the Create Ticket interface. The one completed entry was set manual with sql just to see if tickets were showing up in the completed page (no go there either).

Thanks for the help!

![screen shot 2015-12-09 at 7 37 33 am](https://cloud.githubusercontent.com/assets/8714188/11686661/c00a21ce-9e47-11e5-84db-6e4ad1781bd5.png)

![screen shot 2015-12-09 at 7 34 38 am](https://cloud.githubusercontent.com/assets/8714188/11686617/84360276-9e47-11e5-85d3-34a900c73c01.png)
![screen shot 2015-12-09 at 7 35 01 am](https://cloud.githubusercontent.com/assets/8714188/11686621/87e37d68-9e47-11e5-91e1-50726f96990c.png)
![screen shot 2015-12-09 at 7 35 18 am](https://cloud.githubusercontent.com/assets/8714188/11686623/8a4253f4-9e47-11e5-85bb-e309c0942fb1.png)

**Comment by tmcdon89** [comment]
Well this is embarrassing! I didn't upload the @yield('footer') adjustment to my layout. Sorry to waste your time.

**Comment by thekordy** [comment]
Never mind, glade to see it's working for you.
