### ISSUE TITLE
Direction of Project

### ISSUE THREAD

**Issue by tmcdon89** [thekordy/ticketit#94]
Hi, I'm very interested in this project. That being said, I'm curious as to the ultimate goal of the project?

Is this a ticketing system targeted at internal IT or for a HelpDesk type company servicing multiple clients?

The latter would be the most useful to me so I'm hoping thats the direction. 
Some things to look at (excuse me if its already been suggested)

1) Update and/or Create new tickets from incoming emails
2) Have a "work time" for tickets and comments (I've begun implementing this into my installation)
3)Private comments (not visible to the customer account, this is useful for teams)
4)Companies that users and by extension tickets can be linked to
5)Agent teams/groups 
6)Ability to assign tickets to Agent, Agent Group, or both
7)Ability for agent to assign owner of ticket for customers that call in by phone
8)Service Level Agreements (SLAs) where specific actions/escalations are taken based on ticket timelines

I'd love to help in implementing and furthering the project, but I don't want to waste everyones time if its not a feature set desired by the project owners. 

Tom

**Comment by thekordy** [comment]
I have not thought about the multi-company before, how that work?
Other thank that, I find all of your points very interesting, actually many of them are already discussed and planned (find issues with feature development label) but no one got time yet to start on them, so you are very welcomed to participate on any of them or any of the ones pointed here.

**Comment by tmcdon89** [comment]
The Companies would basically allow another filter that you can do some interesting things with in the future. Such as having Customer admins who can view all tickets from their Company only, sorting of tickets for incoming emails based on domains linked to Companies etc... Customers shouldn't have to be linked to a company.

Its just a higher level tier of sorting for your customers:
Company
         Customers

I'm going to approach the time keeping first as it should be relatively straight forward.
I've been considering the best way to track it and I'm thinking that it should be a column on the comments table. This way all time on a ticket can be kept track of, but also what the time was spent on via the comment. The biggest change this would require is that comments be editable (which I think is a good idea regardless). That way if an agent forgot to record time they could come back and do it.

**Comment by thekordy** [comment]
The company access is a very interesting idea, but for me I would make it lower priority than other mentioned above.
I will make a new branch for the new planned features, you can fork it and apply new features, and i will give you a hand on some of them, I am very interested in attachments and creating tickets by email.
