### ISSUE TITLE
Only working as admin

### ISSUE THREAD

**Issue by jetwes** [thekordy/ticketit#96]
First - compliment for the great package.
I had a couple of problems during installation - but everything is working well now - if the user has the admin-flag. Seems to be something with the settings - but I don't know why...
If a non admin tries to acces /tickets this error is thrown:
ErrorException in Setting.php line 56:
Trying to get property of non-object (View: /home/www/p279869/html/portal/resources/views/vendor/ticketit/shared/nav.blade.php) (View: /home/www/p279869/html/portal/resources/views/vendor/ticketit/shared/nav.blade.php) (View: /home/www/p279869/html/portal/resources/views/vendor/ticketit/shared/nav.blade.php)
in Setting.php line 56
at CompilerEngine->handleViewException(object(ErrorException), '1') in PhpEngine.php line 44

**Comment by thekordy** [comment]
I am so sorry for this issue, please go to `vendor/kordy/ticketit` and make `git pull` to get the last update. I hope this update fixes your issue

**Comment by jetwes** [comment]
Thanks! That's it.
