### ISSUE TITLE
Can't not show tickets

### ISSUE THREAD

**Issue by chi07** [thekordy/ticketit#98]
![my website - helpdesk main page](https://cloud.githubusercontent.com/assets/12810993/11761465/69fafb08-a0f6-11e5-9cdd-b4af7f922f27.png)

Everything works well but, it has not shown tickets. Please help me

**Comment by thekordy** [comment]
You need to add footer section into your master view, please read this wiki on [integrating ticket it with your template](https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template)

**Comment by chi07** [comment]
OK. Working well. Thanks @thekordy :)

**Comment by thekordy** [comment]
You are welcome

**Comment by bahman2216** [comment]
Not work for me in last version, I also put 

> @yield('footer')
